### DISCUSSION TITLE
min_num_seeds not working

### DISCUSSION THREAD

**Discussion by tordenflesk** [StuffAnThings/qbit_manage#362] [Q&A]
Why wouldn't min_num_seeds work here?
~2700 torrents get paused while on less that 5 seeders.
```
  _OPS:
    priority: 12
    include_any_tags:
    - _OPS
    max_seeding_time: 131400
    min_seeding_time: 43800
    min_num_seeds: 5
    cleanup: false
    add_group_to_tag: false
  _RED:
    priority: 13
    include_any_tags:
    - _RED
    max_seeding_time: 262800
    min_seeding_time: 131400
    min_num_seeds: 5
    cleanup: false
    add_group_to_tag: false
```
