### DISCUSSION TITLE
Apprise Configuration for Email Only

### DISCUSSION THREAD

**Discussion by animosity022** [StuffAnThings/qbit_manage#445] [Q&A]
I'm trying to figure out how to just use my Amazon SES that I use in other spots. I have no API URL, but I do have the notifiy URL.

```
[2023-11-08 10:00:47,839] [__init__:231]              [ERROR]    | Config Error: apprise sub-attribute api_url not found                                              |
                                                                 | apprise sub-attribute api_url added to config                                                      |
[2023-11-08 10:00:47,839] [__init__:232]              [INFO]     | Apprise Connection Failed
```

Key removed:

```
apprise:
  # Mandatory to fill out the notification url/urls based on the notification services provided by apprise. https://github.com/caronc/apprise/wiki
  notify_url:
   WORKING SES COMMAND
  api_url:
```

I'm not sure if I'm doing something silly or have a config issue somewhere else.

**Comment by bakerboy448** [comment]
`api_url` is mandatory when using the `apprise:` integration — qbm isn't calling Apprise directly, it's calling a separate [apprise-api](https://github.com/caronc/apprise-api) HTTP server and expects `api_url` to point at that server's base URL (it does a `GET {api_url}/status` health check on startup — see `modules/apprise.py`). `notify_url` is where your actual per-service string goes (e.g. your working SES `mailto://`/`mailtos://` URL).

So you need two things, not one:
1. An apprise-api instance running somewhere (e.g. `docker run caronc/apprise-api`), reachable from qbm.
2. Config:
```yaml
apprise:
  api_url: http://apprise-api:8000   # the apprise-api server, not your SES URL
  notify_url:
    - mailtos://your-working-ses-string-here
```

Removing `api_url` entirely isn't valid — both keys are required (`docs/Config-Setup.md` apprise section). If you don't want to run a separate apprise-api container, use the `webhooks:`/`notifiarr:` path instead, or send SES notifications through a different mechanism outside qbm.
