### DISCUSSION TITLE
Attempting noHL Cleanup on develop

### DISCUSSION THREAD

**Discussion by undaunt** [StuffAnThings/qbit_manage#516] [Q&A] [answered]
Hello,

I'm attempting to delete non-HL files after a minimum seed time of 30 days, such as in the case Radarr replaces a movie and I've met the minimum tracker enforce seed times.

It's not letting me set the max seed time as lower than the min seed time, nor the max ratio as 0. Basically I'm trying to let the files seed for as long as possible until such time they are safe to be deleted, so I don't want to set a max ratio.

On the new develop version I'm getting warnings such as the following during test:

`Config Error: min_seeding_time (43200) is greater than max_seeding_time (-1) for the grouping 'noHL-movies'. |
2024-04-01T22:10:13.837737623Z | min_seeding_time must be less than or equal to max_seeding_time.`
`Config Error: min_seeding_time (43200) is set, but max_ratio (-1) is not set for the grouping 'noHL-movies'. |
2024-04-01T22:10:36.836036015Z | max_ratio must be greater than 0 when min_seeding_time is set.`
`Config Error: min_seeding_time (43200) is set, but max_ratio (0.0) is not set for the grouping 'noHL-movies'. |
2024-04-01T22:11:00.358253334Z | max_ratio must be greater than 0 when min_seeding_time is set.`

What is the recommended approach? Config below. Yes, I have dry-run on for testing. Thank you.

```
commands:
  dry_run: true
  cross_seed: false
  recheck: false
  cat_update: true
  tag_update: true
  rem_unregistered: true
  tag_tracker_error: true
  rem_orphaned: true
  tag_nohardlinks: true
  share_limits: true
  skip_cleanup: false
  skip_qb_version_check: false

qbt:
  host: gluetun-movies:8081
  user:
  pass:

settings:
  force_auto_tmm: true
  tracker_error_tag: issue
  nohardlinks_tag: noHL
  share_limits_tag: ~share_limit
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
  ignoreTags_OnUpdate:
  # Core tags
  - issue
  - noHL
  - cross-seed
  - MinSeedTimeNotReached
  - MinSeedsNotMet
  - LastActiveLimitNotReached
  # Custom tags
  - upload
  - source
  - seadex
  - multipart
  - edition
  - cut
  # Content type
  - anime
  - comedy
  - film
  - sports
  cross_seed_tag: cross-seed
  cat_filter_completed: true
  share_limits_filter_completed: true
  tag_nohardlinks_filter_completed: true
  force_retag_all: false

directory:
  cross_seed: /downloads/watched/
  root_dir: /downloads/data/
  recycle_bin: /downloads/recycled/
  torrents_dir: /torrents/
  orphaned_dir: /downloads/orphaned/
  remote_dir: /downloads/data/

nohardlinks:
- Imported - Anime
- Imported - Movies:
    exclude_tags:
    - upload
    - source
- Seed - Anime
- Seed - Movies:
    exclude_tags:
    - upload
    - source

share_limits:
  noHL-movies:
    priority: 1
    include_all_tags: noHL
    exclude_any_tags:
    - upload
    - source
    categories:
    - Imported - Movies
    - Seed - Movies
    max_ratio: 0
    max_seeding_time: 43200
    min_seeding_time: 43200 # 30 days
    cleanup: true
```
