### DISCUSSION TITLE
Share Limits not removing torrent

### DISCUSSION THREAD

**Discussion by hollanbm** [StuffAnThings/qbit_manage#518] [General]
I'm trying to use the share_limits feature to automatically remove/delete a torrent once it has reached the configured limits. (ratio 5.0, or 6-8 weeks seed time)

However, nothing is being removed, the torrents are stopped. But not removed. The torrents have the `IPTorrents` tag, and the `~share_limit_1.iptorrents` tag assigned to them

I'm just not sure if my config is to blame, or if the feature doesn't work as I expect. Any help or advice is much appreciated.

I've removed the portions of my config that aren't related to the `share_limits` feature

```yaml
commands:
  share_limits: true

settings:
  share_limits_tag: ~share_limit
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has at least one or more of the tags defined here. Otherwise torrents will not be tagged if tags exist.
  - noHL
  - issue
  - cross-seed
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
  share_limits_filter_completed: true

tracker:
  iptorrents|ssl.empirehost.me|routing.bgp.technology|localhost.stackoverflow.tech:
    tag:
    - IPTorrents
  # The "other" key is a special keyword and if defined will tag any other trackers that don't match the above trackers into this tag
  other:
    tag: other

share_limits:
  iptorrents:
    priority: 1
    cleanup: true
    last_active: 1440 # 1 day
    max_ratio: 5.0
    max_seeding_time: 80640 # 8 weeks
    min_num_seeds: 10
    min_seeding_time: 60480 # 6 weeks
    include_any_tags:
    - IPTorrents
```
