### DISCUSSION TITLE
Is there a way to have it NOT create tags/categories?

### DISCUSSION THREAD

**Discussion by devanteweary** [StuffAnThings/qbit_manage#587] [Q&A] [answered]
Hey guys,

So long story short, my ultimate goal with qbitmanage is to keep my private tracker torrents seeding forever.

Attempting to do this by trying to get qbitmanage to change the category of my private trackers (which I set up under trackers: in the config.) to "Seeding". Under share limits, I have it set a tag also called Seeding and change share limits to unlimited for anything categorized as Seeding.

For example, this is what I'm _trying_ to do.

- Download torrent from privatetracker.com
- qbitmanage recognizes privatetracker.com and sets category to "Seeding".
- qbitmanage sets this torrent to unlimited seeding. (currently doing this via share_limits)

Here's what I have currently:

```
tracker:
  private_tracker:
     tag: Seeding
     cat: Seeding

share_limits:
  Seeding:
     priority: 1
     categories:
     - Seeding
     max_ratio: -1
     max_seeding_time: -1
     cleanup: false
     custom_tag: Seeding
```

FOr the most part, it seems like it's gonna work, but on my dry runs, I notice it's ALSO creating tags based on trackers it doesn't recognize.
Also, it's created categories and I'm not sure exactly why but I don't want it to CREATE anything. 

Here's a dry run I just did....
It's creating a tag called explodie.org and a couple of categories: Movies and Unsorted. These categories don't exist in Qbittorrent.
The Movies folder is associated with a category I have called "Videos - Movies" and my .....\Unsorted folder is the default save path for my completed torrents.

![image](https://github.com/StuffAnThings/qbit_manage/assets/29805497/92a1ba87-7f81-4fa2-be87-6115668b6b85)

Alrighty thanks for any info or advice!
And for qbitmanage altogether. Very useful!

Thank you!
