### DISCUSSION TITLE
Trying to setup for constant seeding until I have no hardlinks.

### DISCUSSION THREAD

**Discussion by luckycold** [StuffAnThings/qbit_manage#594] [Q&A] [answered]
I have a setup that works okay but isn't preferable for trackers I want to seed indefinitely for when it comes to content I keep on my server. 
Here are the conditions I'm trying to meet:
1. Seed for as long as I have hard-links as a minimum.
2. If there is no hard-links, then check if I need to meet a minimum seed time for a tracker.
3. If there is no hard-links and minimum seed time is met then delete the torrent.

My current (less then ideal) config:
```yaml
qbt:
  # qBittorrent parameters
  host: REDACTED
  user: REDACTED
  pass: REDACTED

settings:
  force_auto_tmm: true  # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: issue  # Will set the tag of any torrents that do not have a working tracker.
  nohardlinks_tag: noHL # Will set the tag of any torrents with no hardlinks.
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has at least one or more of the tags defined here. Otherwise torrents will not be tagged if tags exist.
  - noHL
  - issue
  share_limits_tag: ~share_limit
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
  force_retag_all: false
  cross_seed_tag: cross-seed
  cat_filter_completed: true
  share_limits_filter_completed: true
  tag_nohardlinks_filter_completed: true
directory:
  root_dir: /data/downloads/torrents
  remote_dir: /data/downloads/torrents
  cross_seed: /data/downloads/torrents/cross-seed-data
  recycle_bin: /data/downloads/torrents/.RecycleBin
  torrents_dir:
  orphaned_dir: /data/downloads/torrents/orphaned_data
cat:
  # Category & Path Parameters
  # <Category Name> : <save_path>  # Path of your save directory.
  radarr: /data/downloads/torrents/radarr
  sonarr: /data/downloads/torrents/sonarr
  lidarr: /data/downloads/torrents/lidarr
  readarr: /data/downloads/torrents/readarr
  prowlarr: /data/downloads/torrents/prowlarr
  cross-seed-data: /data/downloads/torrents/cross-seed-data
  torrents: /data/downloads/torrents
tracker:
  ssl.empirehost:
    tag:
    - iptorrents
    - private
  myanonamouse:
    tag:
    - myanonamouse
    - private
  home.opsfet:
    tag:
    - orpheus
    - private
  migoto.sugoimusic:
    tag:
    - sugoimusic
    - private
  nebulance.io:
    tag:
    - nebulance
    - private
  nyaa.tracker.wf:
    tag: nyaa
  tracker.pixelcove.me:
    tag:
    - pixelcove
    - private
  thegeeks.click:
    tag:
    - thegeeks
    - private
  open.nyaatorrents.info:
    tag: nyaa
  anidex.moe:
    tag: anidex
  tracker.anirena.com:
    tag: anirena
  tracker.revolutiontt.me:
    tag:
    - revolutiontt
    - private

  tracker.openbittorrent.com:
    tag: tracker.openbittorrent.com
  tracker.tfile.co:
    tag: tracker.tfile.co
  bigfoot1942.sektori.org:
    tag: bigfoot1942.sektori.org
  open.stealth.si:
    tag: open.stealth.si
  bt1.archive.org:
    tag: bt1.archive.org
  bt.ocremix.org:
    tag: bt.ocremix.org
  tracker.anthelion.me:
    tag:
    - anthelion
    - private
  blutopia.cc:
    tag:
    - blutopia
    - private
  onlyencodes.cc:
    tag:
    - onlyencodes
    - private
  torrent.ubuntu.com:
    tag: torrent.ubuntu.com
  tracker.foreverpirates.co:
    tag: tracker.foreverpirates.co
  trk.publictracker.xyz:
    tag: trk.publictracker.xyz
  tracker.nanoha.org:
    tag: tracker.nanoha.org
  tracker.nwps.ws:
    tag: tracker.nwps.ws
  tracker.winglai.com:
    tag: tracker.winglai.com
  fr33dom.h33t.com:
    tag: fr33dom.h33t.com
  torrent.gresille.org:
    tag: torrent.gresille.org
  tracker.trackerfix.com:
    tag: tracker.trackerfix.com
  tracker.windsormetalbattery.com:
    tag: tracker.windsormetalbattery.com
  torrent-tracker.ru:
    tag: torrent-tracker.ru
  tracker.best-torrents.net:
    tag: tracker.best-torrents.net
  announce.torrentsmd.com:
    tag: announce.torrentsmd.com
  tracker.thepiratebay.org:
    tag: tracker.thepiratebay.org
  tracker.istole.it:
    tag: tracker.istole.it
  tracker.publicbt.com:
    tag: tracker.publicbt.com
  exodus.1337x.org:
    tag: exodus.1337x.org
  genesis.1337x.org:
    tag: genesis.1337x.org
  tracker.ilibr.org:
    tag: tracker.ilibr.org
  tracker.csze.com:
    tag: tracker.csze.com
  10.rarbg.com:
    tag: 10.rarbg.com
  pow7.com:
    tag: pow7.com
  exodus.desync.com:
    tag: exodus.desync.com
  routing.bgp.technology:
    tag: routing.bgp.technology
  localhost.stackoverflow.tech:
    tag: localhost.stackoverflow.tech
  tracker.opentrackr.org:
    tag: tracker.opentrackr.org
  opentracker.i2p.rocks:
    tag: opentracker.i2p.rocks
nohardlinks:
- sonarr
- radarr
- cross-seed-data

share_limits:
  default:
    priority: 999
    exclude_any_tags:
    - private
    - cross-seed
    - keep
    cleanup: false
  noHL:
    priority: 998
    categories:
    - sonarr
    - radarr
    - cross-seed-data
    include_any_tags:
    - noHL
    exclude_any_tags:
    - private
    - keep
    - games
    cleanup: true
    max_seeding_time: 10
  1DayMin:
    priority: 1
    categories:
    - sonarr
    - radarr
    include_any_tags:
    - thegeeks
    include_all_tags:
    - private
    - noHL
    exclude_any_tags:
    - keep
    - games
    max_seeding_time: 1500
    add_group_to_tag: true
    cleanup: true
  3DaysMin:
    priority: 2
    categories:
    - sonarr
    - radarr
    include_any_tags:
    - myanonamouse
    include_all_tags:
    - private
    - noHL
    exclude_any_tags:
    - keep
    - games
    max_seeding_time: 4400
    add_group_to_tag: true
    cleanup: true
  5DaysMin:
    priority: 3
    categories:
    - sonarr
    - radarr
    include_any_tags:
    - nebulance
    - onlyencodes
    include_all_tags:
    - private
    - noHL
    exclude_any_tags:
    - keep
    - games
    max_seeding_time: 7300
    add_group_to_tag: true
    cleanup: true
  2WeeksMin:
    priority: 4
    categories:
    - sonarr
    - radarr
    include_any_tags:
    - iptorrents
    - blutopia
    include_all_tags:
    - private
    - noHL
    exclude_any_tags:
    - keep
    - games
    max_seeding_time: 21000
    add_group_to_tag: true
    cleanup: true
recyclebin:
  # Recycle Bin method of deletion will move files into the recycle bin (Located in /root_dir/.RecycleBin) instead of directly deleting them in qbit
  # By default the Recycle Bin will be emptied on every run of the qbit_manage script if empty_after_x_days is defined.
  enabled: true
  # <OPTIONAL> empty_after_x_days var:
  # Will automatically remove all files and folders in recycle bin after x days. (Checks every script run)
  # If this variable is not defined it, the RecycleBin will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 1
  save_torrents: false
  split_by_category: false
orphaned:
  # Orphaned files are those in the root_dir download directory that are not referenced by any active torrents.
  # Will automatically remove all files and folders in orphaned data after x days. (Checks every script run)
  # If this variable is not defined it, the orphaned data will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 14
  # File patterns that will not be considered orphaned files. Handy for generated files that aren't part of the torrent but belong with the torrent's files
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/temp/**
  - '**/*.!qB'
  - '**/_unpackerred'

apprise:
  api_url: REDACTED
  notify_url: 
    ntfy://REDACTED

notifiarr:
  # Notifiarr integration with webhooks
  # Leave Empty/Blank to disable
  # Mandatory to fill out API Key
  apikey: REDACTED
  # <OPTIONAL> Set to a unique value (could be your username on notifiarr for example)
  instance: REDACTED

webhooks:
  # Webhook notifications:
  # Possible values:
  # Set value to notifiarr if using notifiarr integration
  # Set value to apprise if using apprise integration
  # Set value to a valid webhook URL
  # Set value to nothing (leave Empty/Blank) to disable
  error: apprise
  run_start:
  function:
    rem_unregistered: apprise
    tag_tracker_error: apprise
    rem_orphaned: apprise
    share_limits:
    cleanup_dirs: apprise
  run_end:
```
