### DISCUSSION TITLE
Share limits: Max inactive time

### DISCUSSION THREAD

**Discussion by Minituff** [StuffAnThings/qbit_manage#636] [Ideas]
Hello, 

Proposing a new idea for share_limits if it doesn't exist already.

`max_inactive_time` = Will remove the torrent if it has been inactive for X amount of time.

For example, I could specify I want my torrents to use the min_seed_time for 14 days, but could allow the torrent to continue seeding until it has had no activity for 30 days, then qbit_manage could clean it up.

**Comment by bakerboy448** [comment]
This already exists — `max_last_active` on a `share_limits:` group does exactly this, layered with `min_seeding_time` as you described:
```yaml
share_limits:
  my_group:
    cleanup: true
    min_seeding_time: 14d      # keep seeding at least 14 days regardless of inactivity
    max_last_active: 30d       # once past min_seeding_time, delete after 30 days with no activity
```
`max_last_active` deletes (with `cleanup: true`) once a torrent has been inactive longer than the given duration; `min_seeding_time` overrides that and forces continued seeding (resetting share limits to unlimited) until the minimum is met. See `max_last_active` / `min_seeding_time` rows in the [share_limits config table](https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup#sharelimits).
