### DISCUSSION TITLE
How do I manage multiple hard drives?

### DISCUSSION THREAD

**Discussion by jordanlambrecht** [StuffAnThings/qbit_manage#659] [Q&A]
I have three different external drives: one for shows, one for movies, and one for anime. What's the best way to get things like NoHL, orphan checks, etc. to work well with that?

**Comment by bakerboy448** [comment]
`root_dir` is single-path by design — qbm forces it to one directory even if you pass a list (`modules/config.py`), and both noHL and orphan checks read that one `root_dir`/`remote_dir` pair.

For 3 separate drives, the documented approach is 3 separate qbm instances (3 containers or 3 scheduled runs), each with its own config pointing at its own `root_dir`, each scoped to the categories that live on that drive:
```yaml
# instance 1 config.yml — shows drive
directory:
  root_dir: /data/shows/
nohardlinks:
  shows:
---
# instance 2 config.yml — movies drive
directory:
  root_dir: /data/movies/
nohardlinks:
  movies:
```
See the "Multi-root setups" note under [directory: in Config-Setup](https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup#directory).
