### DISCUSSION TITLE
How to change port

### DISCUSSION THREAD

**Discussion by nothing2obvi** [StuffAnThings/qbit_manage#736] [Q&A]
I know this might sound like a silly question but I can't figure out how to make qbit_manage not use port 8080. I am using the python installation. Running this on my seedbox, I got in trouble for qbit_manage using port 8080. There's a list of ports I'm allowed to use. The `qbt` section of my config file looks like this (it doesn't connect using 8080):

```
qbt:
  # qBittorrent parameters
  host: 162.111.111.111:12345
  user: username
  pass: password
```

I'd appreciate any help. Thank you!
