### DISCUSSION TITLE
noHL tag only

### DISCUSSION THREAD

**Discussion by Shark1979xxx** [StuffAnThings/qbit_manage#771] [Q&A]
Hi all, I need to tag torrents without a physical link. Only this, no other management. I am not able to create a config file that only does this. It also inserts an "other" tag that in my case I renamed to "qbm". Would you be so kind as to pass me a config file that only executes the noHL tag? Please help me

**Comment by Shark1979xxx** [comment]
This is my config.yml
#190325 untested modify

```
commands:
  dry_run: false
  cross_seed: false
  recheck: false
  cat_update: false
  tag_update: true
  rem_unregistered: false #190325 true
  tag_tracker_error: false
  rem_orphaned: true
  tag_nohardlinks: true
  share_limits: false
  skip_qb_version_check: false
  skip_cleanup: true

qbt:
  host: http://172.20.0.1:8090
  user: '*****'
  pass: '*****'

settings:
  force_auto_tmm: false # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: issue # Will set the tag of any torrents that do not have a working tracker.
  nohardlinks_tag: noHL # Will set the tag of any torrents with no hardlinks.
  #190325 cat_filter_completed: true # Filters for completed torrents only when running cat_update command
  tag_nohardlinks_filter_completed: true # Filters for completed torrents only when running tag_nohardlinks command
  #190325 cat_update_all: true # Checks and udpates all torrent categories if set to True when running cat_update command, otherwise only update torrents that are uncategorized
  #190325 force_auto_tmm_ignore_tags: []
  #190325 disable_qbt_default_share_limits: true
  #190325 rem_unregistered_filter_completed: false
  tag_stalled_torrents: true
  rem_unregistered_ignore_list: []
  #190325 share_limits_tag: ~share_limit
  #190325 share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  #190325 share_limits_min_num_seeds_tag: MinSeedsNotMet
  #190325 share_limits_last_active_tag: LastActiveLimitNotReached
  #190325  share_limits_filter_completed: true

directory:
  #190325 cross_seed: ''
  root_dir: /data/torrents
  #190325 remote_dir: ''
  recycle_bin: /data/torrents/.RecycleBin
  orphaned_dir: /data/torrents/orphaned
  #190325 torrents_dir:

cat:
  films: /data/torrents/completed/films
  serie: /data/torrents/completed/serie

tracker:
  other:
    tag: qbm

nohardlinks:
  films:
  serie:
  #190325 cross-seed-link:
  ignore_root_dir: true

recyclebin:
  enabled: true
  empty_after_x_days: 120
  save_torrents: false
  split_by_category: false

orphaned:
  empty_after_x_days: 120
  max_orphaned_files_to_delete: 50
  exclude_patterns:
  - '**/.DS_Store'
  - '**/@eaDir/**'
  - '**/Thumbs.db'
  - '**/*.!qB'
  - '**/*_unpackerred'
  - /data/torrents/incompleted/**

#190325 webhooks:
  #190325 error:
  #190325 run_start:
  #190325 run_end:
  #190325 function:
    #190325 cross_seed:
    #190325 recheck:
    #190325 cat_update:
    #190325 tag_update:
    #190325 rem_unregistered:
    #190325 tag_tracker_error:
    #190325 rem_orphaned:
    #190325 tag_nohardlinks:
    #190325 share_limits:
    #190325 cleanup_dirs:
``` 
if i remove:

``` 
tracker:
  other:
    tag: qbm
``` 
noHL tag not work, but i don't want "qbm" tag
