### ISSUE TITLE
[Bug]: Globing pattern not working

### ISSUE THREAD

**Issue by DuzAwe** [StuffAnThings/qbit_manage#123]
### Describe the Bug

Currently have   - '*unpackerred'  - '**unpackerred' - '**/**unpackerred' in my excluded paths but any paths with _unpackerred  keep being moved to orphaned.

### Config

```yaml
# qBittorrent parameters
qbt:
  host: 192.168.0.27:8080
  user: duzawe
  pass: $F3c^Go4dMiu4564tqm
settings:
  force_auto_tmm: false
  tracker_error_tag: issue
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has one or more of the tags defined here.
    - noHL
    - issue
    - cross-seed
directory:
  # Do not remove these
  # Cross-seed var: </downloads/cross-seed/> #Output directory of cross-seed 
  # root_dir var: </downloads/keeps/> #Root downloads directory used to check for orphaned files
  # <OPTIONAL> remote_dir var: </your/path/here/> # Path of docker host mapping of root_dir
  cross_seed: /downloads/cross-seed
  root_dir: /downloads/keeps/
  remote_dir: /downloads/keeps/
  recycle_bin: /downloads/keeps/.RecycleBin
  torrents_dir:
cat:
  keeps: /downloads/keeps/
tracker:
  # <Tracker URL Keyword>: <Tag Name>
  beyond-hd:
    tag: Beyond-HD
  animebytes.tv:
    tag: AnimeBytes
  torrentleech:
    tag: TorrentLeech
    max_ratio: 2.0
    max_seeding_time: 21600
  tleechreload:
    tag: TorrentLeech
    max_ratio: 2.0
    max_seeding_time: 21600
  blutopia:
    tag: Blutopia
  baconbits:
    tag: BaconBits
  digitalcore:
    tag: DigitalCore
    max_ratio: 2.0
    max_seeding_time: 21600
  myanonamouse:
    tag: MyAnonaMouse
  torrentday:
    tag: TorrentDay
    max_ratio: 2.0
    max_seeding_time: 21600
  empirehost:
    tag: IPTorrents
    max_ratio: 2.0
    max_seeding_time: 21600
  td-peers:
    tag: TorrentDay
    max_ratio: 2.0
    max_seeding_time: 21600
  nebulance:
    tag: Nebulance
  anthelion:
    tag: Anthelion
  iptorrents:
    tag: IPTorrent
    max_ratio: 2.0
    max_seeding_time: 21600
  torrentseeds:
    tag: TorrentSeeds
  theempire:
    tag: TheEmpire
  peerjunkies:
    tag: PeerJunkies
  torrentdb:
    tag: TorrentDB
  filelist:
    tag: FileList
  nyaa:
    tag: Nyaa
    max_ratio: 2.0
    max_seeding_time: 21600
  skipthecommericals:
    tag: SkipTheCommericals
    max_ratio: 2.0
    max_seeding_time: 21600
  uhdbits.org:
    tag: uhdbits.org
  reactor.flro.org:
    tag: FileList
  morethantv:
    tag: MoreThanTV
  td.jumbohostpro.eu:
    tag: TorrentDay
    max_ratio: 2.0
    max_seeding_time: 21600
  routing.bgp.technology:
    tag: IPTorrents
    max_ratio: 2.0
    max_seeding_time: 21600
  localhost.stackoverflow.tech:
    tag: IPTorrents
    max_ratio: 2.0
    max_seeding_time: 21600
recyclebin:
  enabled: true
  empty_after_x_days: 3
  save_torrents: false
  split_by_category: false
orphaned:
  exclude_patterns:
    - '**/.DS_Store'
    - '**/Thumbs.db'
    - '**/@eaDir'
    - /data/torrents/temp/**
    - '**/*.!qB'
    - '*unpackerred'
    - '**unpackerred'
    - '**/**unpackerred'
webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    rem_orphaned:
    tag_nohardlinks:
    empty_recyclebin:
```

### Logs

https://gist.github.com/DuzAwe/5fee2a719a9f1eb8fe7e44df8d1e1000

### Installation

Docker

### Version Number

3.2.2

### What branch are you on?

master
