### ISSUE TITLE
error: unrecognized arguments: config.yml

### ISSUE THREAD

**Issue by ajhorvath20** [StuffAnThings/qbit_manage#14]
Help please :)

Hi, I am getting this message. Seem like I messed something in .yml but not sure what. I am also not sure about `cross-seed` paths. I am running `cross-seed` in docker so inside container `cross-seed` sees `/storage/data/.torrents`

I am using this from terminal

`python3 qbit_manage.py config.yml -m --dry-run --log LOGLEVEL INFO`

```
# qBittorrent parameters
qbt:
  host: '192.168.1.167:8080'
  user: 'username'
  pass: 'passWord'

directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/> #Output directory of cross-seed 
  # root_dir var: </your/path/here/> #Root downloads directory used to check for orphaned files
  # <OPTIONAL> remote_dir var: </your/path/here/> # Path of docker host mapping of root_dir
  cross_seed: '/mnt/data/.torrents/'
  root_dir:  '/mnt/data/.torrents/'
  remote_dir: '/storage/data/.torrents/'

# Category/Pathing Parameters
cat:
  # <Category Name> : <save_path> #Path of your save directory. Can be a keyword or full path
  movies: '/mnt/data/.torrents/movies'
  tv: '/mnt/data/.torrents/tv'

# Tag Parameters
tags:
  # <Tracker URL Keyword>: <Tag Name>
  beyond-hd: Beyond-HD
```
Thank you
