### ISSUE TITLE
[FR]: Allow multiple paths in category definition

### ISSUE THREAD

**Issue by ryanwalder** [StuffAnThings/qbit_manage#143]
### Is your feature request related to a problem? Please elaborate.

I use Radarr (with Hardlinks) and have multiple Root Folders within Radar, all passed to qbittorrent with the `film` tag:

```
/data/Films
/data/Bad Films
/data/Stand Up
/data/Documentaries
```
These then maps 1:1 to a Jellyfin Library so everything ends up in the right place simply by adding it to the right Radarr Root Folder.

I then have the `film` category pointing to `/data/Films`:

```yaml
cat:
  film: "/data/Films"
```

Unfortunately this means that using the `nohardlinks` functionality of qbit_manage think I have `noHL` for anything not in `/data/Films`

### Describe the solution you'd like

I would like the ability to set multiple directories for a category:

```yaml
cat:
  film:
    - "/data/Films"
    - "/data/Bad Films"
    - "/data/Stand Up"
    - "/data/Documentaries"
```

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

Not using `nohardlinks:film:cleanup: true`

### Who will this benefit?

Anyone with multiple destination directories for the same category in qbittorrent

**Comment by bakerboy448** [comment]
> I then have the film category pointing to /data/Films:

Downloading to your root folder is not supported by Radarr and causes weird behavior including dataloss.

**Comment by ryanwalder** [comment]
> > I then have the film category pointing to /data/Films:
> 
> Downloading to your root folder is not supported by Radarr and causes weird behavior including dataloss.
> 
> Your qbit categories can never and should never be the same as your root folder. This also triggers a healthcheck in radarr as well.

To be clear, these are the `Root Folders` in Radarr, where Radarr moves the files to. Not the `directory:root_dir` in qbit_manage

For clarity:

qbit_manage/config.yml:

```yaml
directory:
  cross_seed: /your/path/here/
  root_dir: /data/Uploads/Complete/torrents
  remote_dir: /data/Uploads/Complete/torrents
  recycle_bin: /data/Uploads/.RecycleBin
  torrents_dir: /data/Uploads/Complete/torrents
cat:
  film: /data/Films
```

radar `Root Folders`:

```
/data/Films
/data/Bad Films
/data/Stand Up
/data/Documentaries
```

So the feature request here is in qbit_manage config form is essentially:

```yaml
directory:
  cross_seed: /your/path/here/
  root_dir: /data/Uploads/Complete/torrents
  remote_dir: /data/Uploads/Complete/torrents
  recycle_bin: /data/Uploads/.RecycleBin
  torrents_dir: /data/Uploads/Complete/torrents
cat:
  film:
    - /data/Films
    - /data/Bad Films
    - /data/Stand Up
    - /data/Documentaries
```

**Comment by bakerboy448** [comment]
Cats in QBM are for the torrent category path.... not your root folders

It sounds like your setup doesn't actually facilitate hardlinks and your files are not hardlinked if QBM is marking your torrents as not hardlinked.

**Comment by ryanwalder** [comment]
For the sake of clarity I'll un-obfuscate the directory structure. I can assure you everything is using hardlinks.

```yaml
directory:
  cross_seed: /your/path/here/
  root_dir: /media/ftp/Uploads/Complete/torrents
  remote_dir: /media/ftp/Uploads/Complete/torrents
  recycle_bin: /media/ftp/Uploads/.RecycleBin
  torrents_dir: /media/ftp/Uploads/Complete/torrents
cat:
  film: /media/ftp/Films
```

The full chain of events for adding a Film:

1. Add film to Radarr using `/media/ftp/Films/Film Name (YYYY)` as the end directory
2. Radar searches my indexer
3. Radar adds torrent to my download client (qbittorrent)
    1.  The temp directory of `/media/ftp/Uploads/Incomplete`
    2.  Tags the torrent with the category `film`
5. Qbittorrent downloads the file
6. Qbittorrent completed the download and moves the file to `/media/ftp/Uploads/Complete/torrents/Movie.Name.mkv`
7. Radar creates a Hardlink to `/media/ftp/Films/Film Name (YYYY)/Movie.Name.mkv` and sets it as Downloaded/Complete in Radarr
8. qbit_manage (with nohardlinks:film:*) sees the hardlink so does not tag it as `noHL`
9. All is good

Now we do the same but with a Documentary:

1. Add film to Radarr using `/media/ftp/Documentaries/Documentary Name (YYYY)` as the end directory
2. Radar searches my indexer
3. Radar adds torrent to my download client (qbittorrent)
    1.  The temp directory of `/media/ftp/Uploads/Incomplete`
    2.  Tags the torrent with the category `film` (because radar can only set one category per download client)
5. Qbittorrent downloads the file
6. Qbittorrent completed the download and moves the file to `/media/ftp/Uploads/Complete/torrents/Documentary.Name.mkv`
7. Radar creates a Hardlink to `/media/ftp/Documentaries/Documentary Name (YYYY)/Documentary.Name.mkv` and sets it as Dowloaded/Complete in Radarr
8. qbit_manage (with nohardlinks:film:*) does not see the Hardlink (as it is in /media/ftp/Documentaries, not /media/ftp/Films)
9. qbit_manage tags the torrent in qbittorrent as `noHL`
10. All is not good

So the request here is to support multiple paths for a single category within qbit_manage.
