### ISSUE TITLE
[FR]: Change Category to predefined category 

### ISSUE THREAD

**Issue by TRaSH-** [StuffAnThings/qbit_manage#146]
### Is your feature request related to a problem? Please elaborate.

I'm using cross-seed and with seasons and sonarr it gives issues, because it will be added to qbt before it's fully imported and changed from Category to Post-Import Category
what results in to that you have for example 5 seasons that sonarr thinks it needs to import.

now the dev from cross seed made a work around that that works if you use the same download location for the both categories.

it reuses the current category and adds .cross-seed at the end to it.

![image](https://user-images.githubusercontent.com/6155095/184196256-b26dee41-448e-40d0-a434-31cc394f7784.png)

### Describe the solution you'd like

option that qbit manage changes the category to a predefined category

example:

```yml
cat:
  movies-hd: /data/.torrents/movies/hd
  movies-uhd: /data/.torrents/movies/uhd
  Radarr-HD.cross-seed: /data/.torrents/movies/hd
  Radarr-UHD.cross-seed: /data/.torrents/movies/uhd
  movies-hd.cross-seed: /data/.torrents/movies/hd
  movies-uhd.cross-seed: /data/.torrents/movies/uhd
# This changes the category to another category.
# usage: old-category: new-category 
# WARNING: if the paths are different and Default Torrent Management Mode is set to automatic the files could be moved !!!
change-cat:
  Radarr-HD.cross-seed: movies-hd
  Radarr-UHD.cross-seed: movies-uhd
  movies-hd.cross-seed: movies-hd
  movies-uhd.cross-seed: movies-uhd
```

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

Manual change the category :(

### Who will this benefit?

People use Cross-Seed and like a organized library
and other people with their own use case for what ever reason
