### ISSUE TITLE
[Bug]: orphaned_data folder isn't clearded with empty_after_x_days: 0

### ISSUE THREAD

**Issue by BaukeZwart** [StuffAnThings/qbit_manage#170]
### Describe the Bug

files are moved to orphaned_data folder, but the folder isn't cleared with `empty_after_x_days: 0`

### Config

```yaml
orphaned:
  empty_after_x_days: 0
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'
```

### Logs

https://logs.notifiarr.com/?d2de6142da0878ba#7sau2CsQkAHERLqw493Y6jG1K2SqTtxM8KF1wnyssQge

### Installation

Docker

### Version Number

3.3.0

### What branch are you on?

develop
