### ISSUE TITLE
[Bug]: Paused torrents are removed by qbit-manage when seed time or ratio are not met

### ISSUE THREAD

**Issue by Davo1624** [StuffAnThings/qbit_manage#173]
### Describe the Bug

If qbit-manage runs while a torrent that has not met the specified seed time or ratio goals is paused then said torrent is removed by qbit-manage. Currently the only way to avoid this behavious is to set the min_seeding_time to ensure a torrent is not removed before the seed goal (but not ratio) is met.

### Config

```yaml
nohardlinks:
  race:
    cleanup: true
    max_ratio: 1.1
    max_seeding_time: 2880
    exclude_tags:
    min_seeding_time: 1440
    limit_upload_speed:
  race.cross-seed:
    cleanup: true
    max_ratio: 1
    max_seeding_time: 1500
    exclude_tags:
    min_seeding_time: 0
    limit_upload_speed:
```
```


### Logs

none

### Screenshots

_No response_

### Installation

Docker

### Version Number

Hotio nightly cbc98aebc0705a844262121dbd0d08a505e9dcfa

### What branch are you on?

develop
