### ISSUE TITLE
[Bug]: Torrents which do not have trackers starting with http are not tagged

### ISSUE THREAD

**Issue by leunamd** [StuffAnThings/qbit_manage#183]
### Describe the Bug

From time to time it happens that I encounter torrents which only have udp protocol trackers and they do not get tagged properly, I have no problem whatsoever with other torrents which have http/https trackers.

The problem seems to be at [this line](https://github.com/StuffAnThings/qbit_manage/blob/da2c527e060278cdb7e3d5cd40d9574a096980e5/modules/qbittorrent.py#L276).
It seems like only torrents which have atleast a tracker starting with "http" get considered, that same http check is also used for other features in that same file.

### Config

```yaml
commands:
  # The commands defined below will IGNORE any commands used in command line and docker env variables.
  dry_run: false
  cross_seed: false
  recheck: false
  cat_update: false
  tag_update: true
  rem_unregistered: false
  tag_tracker_error: true
  rem_orphaned: true
  tag_nohardlinks: true
  skip_cleanup: false

qbt:
  # qBittorrent parameters
  host: qbittorrent:8080

  user:
  pass:
settings:
  force_auto_tmm: true  # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: issue  # Will set the tag of any torrents that do not have a working tracker.
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has one or more of the tags defined here.
  - noHL
  - issue
  - cross-seed
directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  # root_dir var: </your/path/here/>  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  # <OPTIONAL> remote_dir var: </your/path/here/>  # Path of docker host mapping of root_dir.
  # Must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # <OPTIONAL> torrents_dir var: </your/path/here/>  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin

  cross_seed: /your/path/here/
  root_dir: /data/torrents/
  remote_dir: /your/path/here/
  recycle_bin: /data/torrents/.RecycleBin
  torrents_dir: /qbittorrent/data/BT_backup
  orphaned_dir: /data/torrents/orphaned_data

tracker:
  opentrackr:
    tag: public
```

### Logs

https://gist.github.com/leunamd/e8701bd2edadccb57d6025e4be914a68

### Screenshots

![2022-11-26_18-42-07](https://user-images.githubusercontent.com/26379856/204102873-47105678-a51a-4ab2-bdae-4a20f30f4be7.png)

### Installation

Docker

### Version Number

3.3.1

### What branch are you on?

master
