### ISSUE TITLE
[Bug]: 'nohardlinks' overwrite 'Tracker' Share Limit and vice versa.

### ISSUE THREAD

**Issue by tordenflesk** [StuffAnThings/qbit_manage#190]
### Describe the Bug

Public torrents I wish to keep running get paused, and private torrents with tracker-specific min_seeding_time set get share limits wiped by nohardlinks

### Config

```yaml
qbt:
  host: 
  user: 
  pass: 

settings:
  force_auto_tmm: false
  tracker_error_tag: issue
  ignoreTags_OnUpdate:
  - noHL
  - issue
  - cross-seed

directory:
  cross_seed: /DATA01/downloads/watch/qbittorrent
  root_dir: /DATA01/downloads/complete
  recycle_bin: /DATA01/downloads/.RecycleBin
  torrents_dir: /config_QBT/BT_backup
  orphaned_dir: /DATA01/downloads/.orphaned_data
  remote_dir: /DATA01/downloads/complete

cat:
  BHD: /DATA01/downloads/complete/BHD
  BHD_FL: /DATA01/downloads/complete/BHD
  BTN: /DATA01/downloads/complete/BTN
  EMP: /DATA01/downloads/complete/EMP
  NB: /DATA01/downloads/complete/EMP
  RADARR.cross-seed: /DATA01/downloads/complete/RADARR
  RADARR: /DATA01/downloads/complete/RADARR
  SONARR.cross-seed: /DATA01/downloads/complete/SONARR
  SONARR: /DATA01/downloads/complete/SONARR
  TL: /DATA01/downloads/complete/TL
  rr.cross-seed: ''
  rr: ''

  complete: /DATA01/downloads/complete/
tracker:
  beyond-hd:
    tag: _BHD
    max_ratio: 1.1
    min_seeding_time: 10800
  landof.tv:
    tag: _BTN
    max_ratio: 1.1
    min_seeding_time: 10800
  tleechreload:
    tag: _TL
    max_ratio: 1.1
    min_seeding_time: 17280
  torrentleech:
    tag: _TL
    max_ratio: 1.1
    min_seeding_time: 17280
  superbits:
    tag: _SB
    max_ratio: 1.1
    min_seeding_time: 4320
  sptracker:
    tag: _SB
    max_ratio: 1.1
    min_seeding_time: 4320
  norbits:
    tag: _NB
    max_ratio: 1.1
  cathoderaytube:
    tag: _CRT
    max_ratio: 1.1
  tracker.empornium.sx:
    tag: _EMP
    max_ratio: 1.1
  tracker.cinemaz.to:
    tag: _CZ
    max_ratio: 0.9
    min_seeding_time: 28320
  other:
    tag: _PBLC
    max_ratio: 1.0
    limit_upload_speed: 150
nohardlinks:
  RADARR:
    cleanup: true
    resume_torrent_after_untagging_noHL: false
    exclude_tags:
    max_ratio: -1
    max_seeding_time:
    min_seeding_time: 
    limit_upload_speed:
  SONARR:
    cleanup: true
    resume_torrent_after_untagging_noHL: false
    exclude_tags:
    max_ratio: -1
    max_seeding_time:
    min_seeding_time:
    limit_upload_speed:
  RADARR.cross-seed:
    cleanup: true
    resume_torrent_after_untagging_noHL: false
    exclude_tags:
    max_ratio: -1
    max_seeding_time:
    min_seeding_time:
    limit_upload_speed:
  SONARR.cross-seed:
    cleanup: true
    resume_torrent_after_untagging_noHL: false
    exclude_tags:
    max_ratio: -1
    max_seeding_time:
    min_seeding_time:
    limit_upload_speed:
  BTN:
    cleanup: true
    resume_torrent_after_untagging_noHL: false
    exclude_tags:
    max_ratio: -1
    max_seeding_time:
    min_seeding_time:
    limit_upload_speed:
  BHD:
    cleanup: true
    resume_torrent_after_untagging_noHL: false
    exclude_tags:
    max_ratio: -1
    max_seeding_time:
    min_seeding_time:
    limit_upload_speed:
  BHD_FL:
    cleanup: true
    resume_torrent_after_untagging_noHL: false
    exclude_tags:
    max_ratio: -1
    max_seeding_time:
    min_seeding_time:
    limit_upload_speed:
  NB:
    cleanup: true
    resume_torrent_after_untagging_noHL: false
    exclude_tags:
    max_ratio: -1
    max_seeding_time:
    min_seeding_time:
    limit_upload_speed:
  rr:
    cleanup: false
    max_ratio: -1
    resume_torrent_after_untagging_noHL: false
    exclude_tags:
    max_seeding_time:
    min_seeding_time:
    limit_upload_speed:
  rr.cross-seed:
    cleanup: false
    max_ratio: -1
    resume_torrent_after_untagging_noHL: false
    exclude_tags:
    max_seeding_time:
    min_seeding_time:
    limit_upload_speed:
recyclebin:
  enabled: true
  empty_after_x_days: 3
  split_by_category: false
  save_torrents: false

orphaned:
  empty_after_x_days: 6
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'
  - '**/*.mkv'

bhd:
  apikey: 

webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    cleanup_dirs:
```

### Logs

https://gist.github.com/tordenflesk/c4aacc4a1a1797ca4186f99d8603df63

### Screenshots

https://i.imgur.com/WhtYrg8.png

### Installation

Docker

### Version Number

3.4

### What branch are you on?

master

**Comment by bobokun** [comment]
To answer the public torrents paused. That's because it met the share limits. You will have to delete them manually once they reach paused state as there is currently no way to delete them for now.

**Comment by tordenflesk** [comment]
> 

I've tried deleting the settings, they get re-added. Does *_seeding_time support -1?

**Comment by tordenflesk** [comment]
> To answer the public torrents paused. That's because it met the share limits. You will have to delete them manually once they reach paused state as there is currently no way to delete them for now.

I dont' want the rr torrents deleted, i want to keep them running indefinitely hence the max_ratio: -1

**Comment by tordenflesk** [comment]
The only thing I want nohardlinks to do is the cleanup and keep the rr/rr.cross-seed torents seeding indefinitely .

**Comment by bakerboy448** [comment]
> Does *_seeding_time support -1?

https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup#nohardlinks

**Comment by bakerboy448** [comment]
> The only thing I want nohardlinks to do is the cleanup and keep the rr/rr.cross-seed torents seeding indefinitely .

That's not what you've configured it to do

```
cleanup: false
    max_ratio: -1
    resume_torrent_after_untagging_noHL: false
    exclude_tags:
    max_seeding_time:
    min_seeding_time:
    limit_upload_speed:
```

It will maintain whatever the previous values are except set the ratio and only the ratio to unlimited.

I don't see what the issue is here.  You're telling QBM to set no ratio and re-reading your OP that is exactly what is happening - the torrents have no limits.

min_seeding_time is not a seed goal so there's literally nothing to wipe for that.
