### ISSUE TITLE
[FR]: Per-tracker settings for no-hardlink settings

### ISSUE THREAD

**Issue by 2fst4u** [StuffAnThings/qbit_manage#213]
### Is your feature request related to a problem? Please elaborate.

The no-hardlink settings are separated by category rather than tracker. Whereas the tracker settings for seed time and ratios are obviously Per-tracker.

When a torrent no longer has a hardlink, the no-hardlink settings take place but these have to be applied to all torrents under a category the same rather than seperate settings per-tracker.

Different trackers have different seeding requirements so the same settings for everything in a category are not always appropriate.

### Describe the solution you'd like

Use the same tracker settings for the no-hardlink settings. An example configuration would look like this:

```
tracker:
  Tracker1:
    tag: tracker1
    max_ratio: 2
    max_seeding_time: 42300
  Tracker2:
    tag: tracker2
    max_ratio: 4
    max_seeding_time: 100000
  Tracker3:
    tag: tracker3
    max_ratio: 1.5
    max_seeding_time: 50000
nohardlinks:
  Tracker1:
    exclude_tags:
    cleanup: true
    max_ratio: 2
    max_seeding_time: 42300
    min_seeding_time: 10000
    limit_upload_speed:
    resume_torrent_after_untagging_noHL: true
  Tracker2:
    exclude_tags:
    cleanup: true
    max_ratio: 1
    max_seeding_time: 50000
    min_seeding_time: 10000
    limit_upload_speed:
    resume_torrent_after_untagging_noHL: true
  Tracker3:
    exclude_tags:
    cleanup: true
    max_ratio: 3
    max_seeding_time: 100000
    min_seeding_time: 100
    limit_upload_speed:
    resume_torrent_after_untagging_noHL: true
```

The reason for this is one tracker may have torrents in multiple categories (like Sonarr and Radarr) that the same settings need to apply to, but different trackers in the same category (tracker1 and tracker2) may have different setting requirements. So a single setting per category doesn't work.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

Nome

### Who will this benefit?

Anyone who uses trackers with different seed requirements and uses hardlinks.
