### ISSUE TITLE
[Bug]: File "qbit_manage.py", line 114     print(f"Config Error: Unable to find any config files in the pattern '{config_files}'.")

### ISSUE THREAD

**Issue by dizzie131** [StuffAnThings/qbit_manage#215]
### Describe the Bug

I have been running the script the same way for months, but today it is throwing an error.
`python ~/scripts/qbit_manage/qbit_manage.py -r --config-file ~/scripts/qbit_manage/config/` returns this error:

`File "/home/username/scripts/qbit_manage/qbit_manage.py", line 114
    print(f"Config Error: Unable to find any config files in the pattern '{config_files}'.")`

### Config

```yaml
# This is an example configuration file that documents all the options.
# It will need to be modified for your specific use case.
# Please refer to the link below for more details on how to set up the configuration file
# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

commands:
  # The commands defined below will IGNORE any commands used in command line and docker env variables.
  dry_run: false
  cross_seed: false
  recheck: true
  cat_update: true
  tag_update: true
  rem_unregistered: true
  tag_tracker_error: true
  rem_orphaned: true
  tag_nohardlinks: false
  skip_recycle: false

qbt:
  # qBittorrent parameters
  host: https://USERNAME.SEEDBOXPROVIDER.com/qbittorrent/
  user: USER
  pass: PASS

settings:
  force_auto_tmm: true  # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: issue  # Will set the tag of any torrents that do not have a working tracker.
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has one or more of the tags defined here.
  - nohl
  - issue
  - cross-seed
  - master
  - racetv
  - autobrr
  - iptcrossseed
  - uploaded
  - framestor
directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  # root_dir var: </your/path/here/>  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  # <OPTIONAL> remote_dir var: </your/path/here/>  # Path of docker host mapping of root_dir.
  # Must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # <OPTIONAL> torrents_dir var: </your/path/here/>  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin

  cross_seed: /home/USERNAME/watch/qbittorrent/
  root_dir: /home/USERNAME/Downloads/Completed/
 # remote_dir: "/mnt/user/data/torrents/"
  recycle_bin: /home/USERNAME/Downloads/.RecycleBin
  torrents_dir: /home/USERNAME/.local/share/qBittorrent/BT_backup

  remote_dir: /home/USERNAME/Downloads/Completed/
cat:
  # Category & Path Parameters
  # <Category Name> : <save_path>  # Path of your save directory.
  Movie: /home/USERNAME/Downloads/Movie/
  TV: /home/USERNAME/Downloads/TV/
  Books: /home/USERNAME/Downloads/Books/
  Music: /home/USERNAME/Downloads/Music/
  Software: /home/USERNAME/Downloads/Software/
  GGn: /home/USERNAME/Downloads/ggn
  TFER: /home/USERNAME/Downloads/tfer
  qbittorrent: /home/USERNAME/downloads/qbittorrent/
  Completed: /home/USERNAME/Downloads/Completed/
  race: /home/USERNAME/Downloads/race/
  EMP: /home/USERNAME/Downloads/EMP/
cat_change:
  # This moves all the torrents from one category to another category. This executes on --cat-update
  # WARNING: if the paths are different and Default Torrent Management Mode is set to automatic the files could be moved !!!
  # <Old Category Name> : <New Category>
#  Radarr: Movie
  #Radarr-UHD.crod
  #movies-hd.cross-seed: movies-hd
  #movies-uhd.cross-seed: movies-uhd


tracker:
  # Tag Parameters
  # <Tracker URL Keyword>:    # <MANDATORY> This is the keyword in the tracker url
  # <MANDATORY> Set tag name. Can be a list of tags or a single tag
  #   tag: <Tag Name>
  # <OPTIONAL> Will set the torrent Maximum share ratio until torrent is stopped from seeding/uploading. -2 means the global limit should be used, -1 means no limit.
  #   max_ratio: 5.0
  # <OPTIONAL> Will set the torrent Maximum seeding time (min) until torrent is stopped from seeding. -2 means the global limit should be used, -1 means no limit.
  #   max_seeding_time: 129600
  # <OPTIONAL> Will limit the upload speed KiB/s (KiloBytes/second) (-1 sets the limit to infinity)
  #   limit_upload_speed: 150
  # <OPTIONAL> Set this to the notifiarr react name. This is used to add indexer reactions to the notifications sent by Notifiarr
  #   notifiarr: <notifiarr indexer>
  # animebytes.tv:
   #   tag: AnimeBytes
    #  notifiarr: animebytes
#   avistaz:
 #   tag:
  #  max_ratio: 5.0
   # max_seeding_time: 129600
    #limit_upload_speed: 150
#    notifiarr: avistaz
  beyond-hd:
    tag: [BHD, media]
  blutopia:
    tag: [BLU, media]
    notifiarr: [BLU, media]
#   cartoonchaos:
#    tag: CartoonChaos
#   digitalcore:
#    tag: DigitalCore
#    max_ratio: 5.0
#    notifiarr: digitalcore
  gazellegames:
    tag: GGn
  hdts:
    tag: HDTorrents
#    max_seeding_time: 129600
#  landof.tv:
#    tag: BroadcasTheNet
#    notifiarr: broadcasthenet
  myanonamouse:
    tag: MaM
#  passthepopcorn:
#    tag: PTP
#    notifiarr: passthepopcorn
#  privatehd:
#    tag: PrivateHD
#    notifiarr:
  tleechreload:
    tag: [TL, media]
#    notifiarr: torrentleech
#  torrentdb:
#    tag: TorrentDB
#    notifiarr: torrentdb
  torrentleech:
    tag: [TL, media]
    notifiarr: torrentleech
  tv-vault:
    tag: TVV

  t.myanonamouse.net:
    tag: MaM
  reactor.filelist.io:
    tag: [FL, media]

  nebulance.io:
    tag: [NBL, media]
  flacsfor.me:
    tag: RED
  aither.cc:
    tag: [ATH, media]

  tracker.morethantv.me:
    tag: [MTV, media]
  uhdbits.org:
    tag: [UHDb, media]
  tracker.pixelcove.me:
    tag: PXC
  routing.bgp.technology:
    tag: [IPT, media]
  home.opsfet.ch:
    tag: OPS
  reactor.flro.org:
    tag: [FL, media]
  tracker.anthelion.me:
    tag: ANT
  tracker.empornium.sx:
    tag: [EMP, media]
  tracker.happyfappy.org:
    tag: tracker.happyfappy.org
nohardlinks:
  # Tag Movies/Series that are not hard linked
  # Mandatory to fill out directory parameter above to use this function (root_dir/remote_dir)
  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
  TV:
    exclude_tags:
    cleanup: false

    max_ratio:
    max_seeding_time:
    min_seeding_time: 0
    limit_upload_speed:
recyclebin:
  # Recycle Bin method of deletion will move files into the recycle bin (Located in /root_dir/.RecycleBin) instead of directly deleting them in qbit
  # By default the Recycle Bin will be emptied on every run of the qbit_manage script if empty_after_x_days is defined.
  enabled: true
  # <OPTIONAL> empty_after_x_days var: 
  # Will automatically remove all files and folders in recycle bin after x days. (Checks every script run)
  # If this variable is not defined it, the RecycleBin will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 10
  # <OPTIONAL> save_torrents var:
  # If this option is set to true you MUST fill out the torrents_dir in the directory attribute.
  # This will save a copy of your .torrent and .fastresume file in the recycle bin before deleting it from qbittorrent
  save_torrents: true
  # <OPTIONAL> split_by_category var:
  # This will split the recycle bin folder by the save path defined in the `cat` attribute 
  # and add the base folder name of the recycle bin that was defined in the `recycle_bin` sub-attribute under directory.
  split_by_category: true

orphaned:
  # Orphaned files are those in the root_dir download directory that are not referenced by any active torrents.
  # File patterns that will not be considered orphaned files. Handy for generated files that aren't part of the torrent but belong with the torrent's files
  empty_after_x_days: 10
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'

#apprise:
  # Apprise integration with webhooks
  # Leave Empty/Blank to disable
  # Mandatory to fill out the url of your apprise API endpoint
 # api_url:
  # Mandatory to fill out the notification url/urls based on the notification services provided by apprise. https://github.com/caronc/apprise/wiki
 # notify_url:

notifiarr:
  # Notifiarr integration with webhooks
  # Leave Empty/Blank to disable
  # Mandatory to fill out API Key
  apikey: APIKEY
  # <OPTIONAL> Set to a unique value (could be your username on notifiarr for example)
  instance:

webhooks:
  # Webhook notifications:
  # Possible values:
  # Set value to notifiarr if using notifiarr integration
  # Set value to apprise if using apprise integration
  # Set value to a valid webhook URL
  # Leave Empty/Blank to disable
  error: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  function:
    cross_seed: notifiarr
    recheck: notifiarr
    cat_update: apprise
    tag_update: notifiarr
    rem_unregistered: notifiarr
    tag_tracker_error: notifiarr
    rem_orphaned: notifiarr
    tag_nohardlinks: notifiarr
    empty_recyclebin: notifiarr



bhd:
apikey: APIKEY
```

### Logs

https://gist.githubusercontent.com/dizzie131/ff1468dc492f2b72f43fbd5d0b5787f5/raw/df1da4da878857106468d671a56d3acfd26b0928/qbit.log

### Installation

Local

### Version Number

unsure

### What branch are you on?

master
