### ISSUE TITLE
[Bug]: Ratio setting from tracker not kept when noHL is applied.

### ISSUE THREAD

**Issue by Quafley** [StuffAnThings/qbit_manage#218]
### Describe the Bug

Let's start with what the docs say. Within the https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup#nohardlinks, the wiki states that the default value of max_ratio is none. Please look at the config for my current setup; note I have only added what is relevant to this report.

Flow:
Both series and anime are within one sonarr instance. After that, both are added to 1 qbit instance under the category sonarr. When completed, c_sonarr. This issue is only relevant for the tag 'nyaa'. I have configured it with a max ratio of 1 and an upload speed limit of 512kbps. This works great; everything is paused after a ratio of 1 has been hit.

When the noHL tag is applied to torrents, the upload speed is kept as is. This is good. The max_ratio, however, is removed and replaced with an unlimited ratio. This is also apparent in the logs I have included with this report.

Either the docs don't state the correct default value, or this is a bug where the ratio of a tracker is replaced with -1 when nothing is specified.

### Config

```yaml
tracker:
  nyaa:
    tag: nyaa
    notifiarr: nyaa
    max_ratio: 1
    limit_upload_speed: 512

nohardlinks:
  sonarr_c:
    exclude_tags:
    cleanup: true
    max_seeding_time: 28800
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
```

### Logs

https://gist.github.com/Quafley/09335ccc8a04541f989bf2fd32c301b2

### Screenshots

![image](https://user-images.githubusercontent.com/44779473/216036828-230b17b1-5da4-4e90-8b19-d22c89ac030c.png)

### Installation

Unraid

### Version Number

3.4.2

### What branch are you on?

master
