### ISSUE TITLE
[Bug]: Unable to open the folder

### ISSUE THREAD

**Issue by pentago** [StuffAnThings/qbit_manage#222]
### Describe the Bug

The process shows the [error message](https://i.imgur.com/N21tZTc.png) saying it can't open a directory while it clearly can and nothing prevents it.

Error message:
```
| Nohardlink Error: Unable to open the folder Resident.Alien.S01.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-TRiToN. Please make sure folder exists and qbit_manage has access to this directory. |
| Uncaught Exception                                                                                 |
Traceback (most recent call last):
  File "/app/qbit_manage.py", line 541, in <module>
    start_loop()
  File "/app/qbit_manage.py", line 308, in start_loop
    start()
  File "/app/qbit_manage.py", line 402, in start
    num_tagged, num_untagged, num_deleted, num_deleted_contents = cfg.qbt.tag_nohardlinks()
  File "/app/modules/qbittorrent.py", line 521, in tag_nohardlinks
    has_nohardlinks = util.nohardlink(torrent["content_path"].replace(root_dir, remote_dir), self.config.notify)
  File "/app/modules/util.py", line 291, in nohardlink
    largest_file_size = os.stat(sorted_files[0]).st_size
IndexError: list index out of range
```
Proof it can access it:
![image](https://i.imgur.com/y0Ug3Pv.png)

### Config

```yaml
# This is an example configuration file that documents all the options.
# It will need to be modified for your specific use case.
# Please refer to the link below for more details on how to set up the configuration file
# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

commands:
  # The commands defined below will IGNORE any commands used in command line and docker env variables.
  dry_run: true
  cross_seed: false
  recheck: false
  cat_update: false
  tag_update: false
  rem_unregistered: true
  tag_tracker_error: true
  rem_orphaned: true
  tag_nohardlinks: true
  skip_cleanup: false

qbt:
  # qBittorrent parameters
  host: qbittorrent:8080
  user: ''
  pass: ''

settings:
  force_auto_tmm: false  # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: issue  # Will set the tag of any torrents that do not have a working tracker.
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has one or more of the tags defined here.
  - noHL
  - issue
  - cross-seed

directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  # root_dir var: </your/path/here/>  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  # <OPTIONAL> remote_dir var: </your/path/here/>  # Path of docker host mapping of root_dir.
  # Must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # <OPTIONAL> torrents_dir var: </your/path/here/>  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin

  cross_seed: ''
  root_dir: /storage/downloads
  remote_dir: ''
  recycle_bin: /storage/downloads/.RecycleBin
  torrents_dir: /qbittorrent/data/BT_backup
  orphaned_dir: /storage/orphaned_data

cat:
  # Category & Path Parameters
  # <Category Name> : <save_path>  # Path of your save directory.
  movies: /storage/downloads
  movie-completed: /storage/movies
  tv: /storage/downloads
  tv-completed: /storage/tv
  music: /storage/downloads
  music-completed: /storage/music
  mma: /storage/mma
  mma-completed: /storage/mma

cat_change:
  # This moves all the torrents from one category to another category. This executes on --cat-update
  # WARNING: if the paths are different and Default Torrent Management Mode is set to automatic the files could be moved !!!
  # <Old Category Name> : <New Category>
  # Radarr-HD.cross-seed: movies-hd
  # Radarr-UHD.cross-seed: movies-uhd
  # movies-hd.cross-seed: movies-hd
  # movies-uhd.cross-seed: movies-uhd

tracker:
  # Tag Parameters
  # <Tracker URL Keyword>:    # <MANDATORY> This is the keyword in the tracker url
  # <MANDATORY> Set tag name. Can be a list of tags or a single tag
  #   tag: <Tag Name>
  # <OPTIONAL> Will set the torrent Maximum share ratio until torrent is stopped from seeding/uploading. -2 means the global limit should be used, -1 means no limit.
  #   max_ratio: 5.0
  # <OPTIONAL> Will set the torrent Maximum seeding time (min) until torrent is stopped from seeding. -2 means the global limit should be used, -1 means no limit.
  #   max_seeding_time: 129600
  # <OPTIONAL> Will ensure that noHL torrents from this tracker are not deleted by cleanup variable if torrent has not yet met the minimum seeding time (min).
  #   min_seeding_time: 2000
  # <OPTIONAL> Will limit the upload speed KiB/s (KiloBytes/second) (-1 means no limit)
  #   limit_upload_speed: 150
  # <OPTIONAL> Set this to the notifiarr react name. This is used to add indexer reactions to the notifications sent by Notifiarr
  #   notifiarr: <notifiarr indexer>
  avistaz:
    tag: AZ
  beyond-hd:
    tag: BHD
  blutopia:
    tag: BT
  digitalcore:
    tag: DC
  hdts:
    tag: HDT
  landof.tv:
    tag: BTN
  myanonamouse:
    tag: MAM
  passthepopcorn:
    tag: PTP
  privatehd:
    tag: PHD
  torrentdb:
    tag: TDB
  torrentleech:
    tag: TL
  tleechreload:
    tag: TL
  tv-vault:
    tag: TV-Vault
  immortalseed:
    tag: IS
  hd-space:
    tag: HDS
  iptorrents:
    tag: IPT
  mma-torrents:
    tag: MMA
  torrentseeds:
    tag: TS
  # The "other" key is a special keyword and if defined will tag any other trackers that don't match the above trackers into this tag
  other:
    tag: other

nohardlinks:
  # Tag Movies/Series that are not hard linked
  # Mandatory to fill out directory parameter above to use this function (root_dir/remote_dir)

  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
  movie-completed:
    # <OPTIONAL> exclude_tags var: Will exclude the following tags when searching through the category.
    # exclude_tags:
    #   - Beyond-HD
    #   - AnimeBytes
    #   - MaM
    # <OPTIONAL> cleanup var: WARNING!! Setting this as true Will remove and delete contents of any torrents that have a noHL tag and meets share limits
    cleanup: true
    # <OPTIONAL> max_ratio var: Will set the torrent Maximum share ratio until torrent is stopped from seeding/uploading
    # max_ratio: 4.0
    # <OPTIONAL> max seeding time var: Will set the torrent Maximum seeding time (min) until torrent is stopped from seeding
    max_seeding_time: 14444
    # <OPTIONAL> Limit Upload Speed var: Will limit the upload speed KiB/s (KiloBytes/second) (`-1` : No Limit)
    # limit_upload_speed:
    # <OPTIONAL> min seeding time var: Will prevent torrent deletion by cleanup variable if torrent has not yet minimum seeding time (min).
    # Delete this key from a category's config to use the tracker's configured min_seeding_time. Will default to 0 if not specified for the category or tracker.
    # min_seeding_time: 43200
    # <OPTIONAL> resume_torrent_after_untagging_noHL var: If a torrent was previously tagged as NoHL and now has hardlinks, this variable will resume your torrent after changing share limits
    resume_torrent_after_untagging_noHL: false

  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
    exclude_tags:
  tv-completed:
    # <OPTIONAL> exclude_tags var: Will exclude the following tags when searching through the category.
    # exclude_tags:
    #   - Beyond-HD
    #   - AnimeBytes
    #   - MaM
    # <OPTIONAL> cleanup var: WARNING!! Setting this as true Will remove and delete contents of any torrents that have a noHL tag and meets share limits
    cleanup: true
    # <OPTIONAL> max_ratio var: Will set the torrent Maximum share ratio until torrent is stopped from seeding/uploading
    # max_ratio: 4.0
    # <OPTIONAL> max seeding time var: Will set the torrent Maximum seeding time (min) until torrent is stopped from seeding
    max_seeding_time: 14444
    # <OPTIONAL> Limit Upload Speed var: Will limit the upload speed KiB/s (KiloBytes/second) (`-1` : No Limit)
    # limit_upload_speed:
    # <OPTIONAL> min seeding time var: Will prevent torrent deletion by cleanup variable if torrent has not yet minimum seeding time (min).
    # Delete this key from a category's config to use the tracker's configured min_seeding_time. Will default to 0 if not specified for the category or tracker.
    # min_seeding_time: 43200
    # <OPTIONAL> resume_torrent_after_untagging_noHL var: If a torrent was previously tagged as NoHL and now has hardlinks, this variable will resume your torrent after changing share limits
    resume_torrent_after_untagging_noHL: false

  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
    exclude_tags:
  music-completed:
    # <OPTIONAL> exclude_tags var: Will exclude the following tags when searching through the category.
    # exclude_tags:
    #   - Beyond-HD
    #   - AnimeBytes
    #   - MaM
    # <OPTIONAL> cleanup var: WARNING!! Setting this as true Will remove and delete contents of any torrents that have a noHL tag and meets share limits
    cleanup: true
    # <OPTIONAL> max_ratio var: Will set the torrent Maximum share ratio until torrent is stopped from seeding/uploading
    # max_ratio: 4.0
    # <OPTIONAL> max seeding time var: Will set the torrent Maximum seeding time (min) until torrent is stopped from seeding
    max_seeding_time: 14444
    # <OPTIONAL> Limit Upload Speed var: Will limit the upload speed KiB/s (KiloBytes/second) (`-1` : No Limit)
    # limit_upload_speed:
    # <OPTIONAL> min seeding time var: Will prevent torrent deletion by cleanup variable if torrent has not yet minimum seeding time (min).
    # Delete this key from a category's config to use the tracker's configured min_seeding_time. Will default to 0 if not specified for the category or tracker.
    # min_seeding_time: 43200
    # <OPTIONAL> resume_torrent_after_untagging_noHL var: If a torrent was previously tagged as NoHL and now has hardlinks, this variable will resume your torrent after changing share limits
    resume_torrent_after_untagging_noHL: false

  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
    exclude_tags:
  mma-completed:
    # <OPTIONAL> exclude_tags var: Will exclude the following tags when searching through the category.
    # exclude_tags:
    #   - Beyond-HD
    #   - AnimeBytes
    #   - MaM
    # <OPTIONAL> cleanup var: WARNING!! Setting this as true Will remove and delete contents of any torrents that have a noHL tag and meets share limits
    cleanup: true
    # <OPTIONAL> max_ratio var: Will set the torrent Maximum share ratio until torrent is stopped from seeding/uploading
    # max_ratio: 4.0
    # <OPTIONAL> max seeding time var: Will set the torrent Maximum seeding time (min) until torrent is stopped from seeding
    max_seeding_time: 14444
    # <OPTIONAL> Limit Upload Speed var: Will limit the upload speed KiB/s (KiloBytes/second) (`-1` : No Limit)
    # limit_upload_speed:
    # <OPTIONAL> min seeding time var: Will prevent torrent deletion by cleanup variable if torrent has not yet minimum seeding time (min).
    # Delete this key from a category's config to use the tracker's configured min_seeding_time. Will default to 0 if not specified for the category or tracker.
    # min_seeding_time: 43200
    # <OPTIONAL> resume_torrent_after_untagging_noHL var: If a torrent was previously tagged as NoHL and now has hardlinks, this variable will resume your torrent after changing share limits
    resume_torrent_after_untagging_noHL: false

    exclude_tags:
recyclebin:
  # Recycle Bin method of deletion will move files into the recycle bin (Located in /root_dir/.RecycleBin) instead of directly deleting them in qbit
  # By default the Recycle Bin will be emptied on every run of the qbit_manage script if empty_after_x_days is defined.
  enabled: true
  # <OPTIONAL> empty_after_x_days var:
  # Will automatically remove all files and folders in recycle bin after x days. (Checks every script run)
  # If this variable is not defined it, the RecycleBin will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 15
  # <OPTIONAL> save_torrents var:
  # If this option is set to true you MUST fill out the torrents_dir in the directory attribute.
  # This will save a copy of your .torrent and .fastresume file in the recycle bin before deleting it from qbittorrent
  save_torrents: true
  # <OPTIONAL> split_by_category var:
  # This will split the recycle bin folder by the save path defined in the `cat` attribute
  # and add the base folder name of the recycle bin that was defined in the `recycle_bin` sub-attribute under directory.
  split_by_category: true

orphaned:
  # Orphaned files are those in the root_dir download directory that are not referenced by any active torrents.
  # Will automatically remove all files and folders in orphaned data after x days. (Checks every script run)
  # If this variable is not defined it, the orphaned data will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 15
  # File patterns that will not be considered orphaned files. Handy for generated files that aren't part of the torrent but belong with the torrent's files
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'

apprise:
  # # Apprise integration with webhooks
  # # Leave Empty/Blank to disable
  # # Mandatory to fill out the url of your apprise API endpoint
  # api_url:
  # # Mandatory to fill out the notification url/urls based on the notification services provided by apprise. https://github.com/caronc/apprise/wiki
  # notify_url:

notifiarr:
  # # Notifiarr integration with webhooks
  # # Leave Empty/Blank to disable
  # # Mandatory to fill out API Key
  # apikey:
  # # <OPTIONAL> Set to a unique value (could be your username on notifiarr for example)
  # instance:

webhooks:
  # Webhook notifications:
  # Possible values:
  # Set value to notifiarr if using notifiarr integration
  # Set value to apprise if using apprise integration
  # Set value to a valid webhook URL
  # Leave Empty/Blank to disable
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    cleanup_dirs:
```

### Logs

https://gist.githubusercontent.com/pentago/85aebc7cd82e71757c0c86d429fda4c3/raw/09973b0908bdceb42cae3f15e538c0c922331eaf/qbit_manage.log

### Installation

Docker

### Version Number

3.4.2

### What branch are you on?

master
