### ISSUE TITLE
[Bug]: Torrents not getting removed from qbittorrent after meeting either `max_ratio` or `max_seeding_time` defined for the tracker

### ISSUE THREAD

**Issue by aaearon** [StuffAnThings/qbit_manage#229]
### Describe the Bug

Torrents are not getting removed from qbittorrent after meeting the defined `max_ratio` or `max_seeding_time` defined for their tracker. The torrents are just paused with the expectation that they are removed after subsequent runs of qbit_manage.

### Config

```yaml
settings:
  force_auto_tmm: false  # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: issue  # Will set the tag of any torrents that do not have a working tracker.
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has one or more of the tags defined here.
  - noHL
  - issue
  - cross-seed
directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  # root_dir var: </your/path/here/>  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  # <OPTIONAL> remote_dir var: </your/path/here/>  # Path of docker host mapping of root_dir.
  # Must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # <OPTIONAL> torrents_dir var: </your/path/here/>  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin
  cross_seed: /home/aaearon/downloads/qbittorrent/
  root_dir: /home/aaearon/downloads/qbittorrent/
  remote_dir: /home/aaearon/downloads/qbittorrent/
  orphaned_dir: /home/aaearon/downloads/qbittorrent/orphaned_data
  torrents_dir:

cat:
  # Category & Path Parameters
  # <Category Name> : <save_path>  # Path of your save directory.
  radarr: /home/aaearon/downloads/qbittorrent/movies
  tv-sonarr: /home/aaearon/downloads/qbittorrent/tv
  other: /home/aaearon/downloads/qbittorrent
  other.cross-seed: /home/aaearon/downloads/qbittorrent/other
  radarr.cross-seed: /home/aaearon/downloads/qbittorrent/movies
  tv-sonarr.cross-seed: /home/aaearon/downloads/qbittorrent/tv

cat_change:
  # This moves all the torrents from one category to another category. This executes on --cat-update
  # WARNING: if the paths are different and Default Torrent Management Mode is set to automatic the files could be moved !!!
  # <Old Category Name> : <New Category>
  radarr.cross-seed: radarr
  tv-sonarr.cross-seed: tv-sonarr
  other.cross-seed: other

tracker:
  # Tag Parameters
  # <Tracker URL Keyword>:    # <MANDATORY> This is the keyword in the tracker url
  # <MANDATORY> Set tag name. Can be a list of tags or a single tag
  #   tag: <Tag Name>
  # <OPTIONAL> Will set the torrent Maximum share ratio until torrent is stopped from seeding/uploading. -2 means the global limit should be used, -1 means no limit.
  #   max_ratio: 5.0
  # <OPTIONAL> Will set the torrent Maximum seeding time (min) until torrent is stopped from seeding. -2 means the global limit should be used, -1 means no limit.
  #   max_seeding_time: 129600
  # <OPTIONAL> Will ensure that noHL torrents from this tracker are not deleted by cleanup variable if torrent has not yet met the minimum seeding time (min).
  #   min_seeding_time: 2000
  # <OPTIONAL> Will limit the upload speed KiB/s (KiloBytes/second) (-1 means no limit)
  #   limit_upload_speed: 150
  # <OPTIONAL> Set this to the notifiarr react name. This is used to add indexer reactions to the notifications sent by Notifiarr
  #   notifiarr: <notifiarr indexer>
  # iptorrents
  empirehost:
    tag: iptorrents
    max_ratio: 1.05
    # 14 days
    max_seeding_time: 20170
  # BroadcastTheNet
  landof.tv:
    tag: broadcasthenet
    max_ratio: 1.05
    # 5 days
    max_seeding_time: 7560
  # TorrentDay
  jumbohostpro:
    tag: torrentday
    max_ratio: 1.05
    # 3 days
    max_seeding_time: 4330
  # TorrentSeeds
  torrentseeds:
    tag: torrentseeds
    max_ratio: 1.05
    # 5 days
    max_seeding_time: 7300
  # Hawke-Uno
  hawke.uno:
    tag: huno
    # 5 days
    max_seeding_time: 7300
  # TorrentLeech
  torrentleech:
    tag: torrentleech
    max_ratio: 1.05
    # 8 days
    max_seeding_time: 11620
  # AlphaRatio
  alpharatio:
    tag: alpharatio
    max_ratio: 1.05
    # 7 days
    max_seeding_time: 10180
# HDBits
  hdbits:
    tag: hdbits
  other:
    tag: other

nohardlinks:
  # Tag Movies/Series that are not hard linked
  # Mandatory to fill out directory parameter above to use this function (root_dir/remote_dir)
  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
  radarr:
    # <OPTIONAL> exclude_tags var: Will exclude the following tags when searching through the category.
    exclude_tags:
    # - hdbits
    # <OPTIONAL> cleanup var: WARNING!! Setting this as true Will remove and delete contents of any torrents that have a noHL tag and meets share limits
    cleanup: true
    # <OPTIONAL> max_ratio var: Will set the torrent Maximum share ratio until torrent is stopped from seeding/uploading
    # max_ratio: 4.0
    # <OPTIONAL> max seeding time var: Will set the torrent Maximum seeding time (min) until torrent is stopped from seeding
    # max_seeding_time: 86400
    # <OPTIONAL> Limit Upload Speed var: Will limit the upload speed KiB/s (KiloBytes/second) (`-1` : No Limit)
    # limit_upload_speed:
    # <OPTIONAL> min seeding time var: Will prevent torrent deletion by cleanup variable if torrent has not yet minimum seeding time (min).
    # Delete this key from a category's config to use the tracker's configured min_seeding_time. Will default to 0 if not specified for the category or tracker.
    # min_seeding_time: 43200
    # <OPTIONAL> resume_torrent_after_untagging_noHL var: If a torrent was previously tagged as NoHL and now has hardlinks, this variable will resume your torrent after changing share limits
    resume_torrent_after_untagging_noHL: true
  # Can have additional categories set with separate ratio/seeding times defined.
  tv-sonarr:
    # <OPTIONAL> exclude_tags var: Will exclude the following tags when searching through the category.
    exclude_tags:
    # - hdbits
    # <OPTIONAL> cleanup var: WARNING!! Setting this as true Will remove and delete contents of any torrents that have a noHL tag and meets share limits
    cleanup: true
    # <OPTIONAL> max_ratio var: Will set the torrent Maximum share ratio until torrent is stopped from seeding/uploading
    # max_ratio: 4.0
    # <OPTIONAL> max seeding time var: Will set the torrent Maximum seeding time (min) until torrent is stopped from seeding
    # max_seeding_time: 86400
    # <OPTIONAL> Limit Upload Speed var: Will limit the upload speed KiB/s (KiloBytes/second) (`-1` : No Limit)
    # limit_upload_speed:
    # <OPTIONAL> min seeding time var: Will prevent torrent deletion by cleanup variable if torrent has not yet minimum seeding time (min).
    # min_seeding_time: # Not specified for this category; tracker's value will be used. Will default to 0 if not specified for the category or tracker.
    # <OPTIONAL> resume_torrent_after_untagging_noHL var: If a torrent was previously tagged as NoHL and now has hardlinks, this variable will resume your torrent after changing share limits
    resume_torrent_after_untagging_noHL: true
  other:
    cleanup: true
    exclude_tags:
    resume_torrent_after_untagging_noHL: true

recyclebin:
  # Recycle Bin method of deletion will move files into the recycle bin (Located in /root_dir/.RecycleBin) instead of directly deleting them in qbit
  # By default the Recycle Bin will be emptied on every run of the qbit_manage script if empty_after_x_days is defined.
  enabled: false
  # <OPTIONAL> empty_after_x_days var:
  # Will automatically remove all files and folders in recycle bin after x days. (Checks every script run)
  # If this variable is not defined it, the RecycleBin will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 60
  # <OPTIONAL> save_torrents var:
  # If this option is set to true you MUST fill out the torrents_dir in the directory attribute.
  # This will save a copy of your .torrent and .fastresume file in the recycle bin before deleting it from qbittorrent
  save_torrents: true
  # <OPTIONAL> split_by_category var:
  # This will split the recycle bin folder by the save path defined in the `cat` attribute
  # and add the base folder name of the recycle bin that was defined in the `recycle_bin` sub-attribute under directory.
  split_by_category: false

orphaned:
  # Orphaned files are those in the root_dir download directory that are not referenced by any active torrents.
  # Will automatically remove all files and folders in orphaned data after x days. (Checks every script run)
  # If this variable is not defined it, the orphaned data will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 0
  # File patterns that will not be considered orphaned files. Handy for generated files that aren't part of the torrent but belong with the torrent's files
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'

# apprise:
  # Apprise integration with webhooks
  # Leave Empty/Blank to disable
  # Mandatory to fill out the url of your apprise API endpoint
  # api_url: http://apprise-api:8000
  # Mandatory to fill out the notification url/urls based on the notification services provided by apprise. https://github.com/caronc/apprise/wiki
  # notify_url:

# notifiarr:
  # Notifiarr integration with webhooks
  # Leave Empty/Blank to disable
  # Mandatory to fill out API Key
  # apikey: ####################################
  # <OPTIONAL> Set to a unique value (could be your username on notifiarr for example)
  # instance:

# webhooks:
  # Webhook notifications:
  # Possible values:
  # Set value to notifiarr if using notifiarr integration
  # Set value to apprise if using apprise integration
  # Set value to a valid webhook URL
  # Leave Empty/Blank to disable
  # error: https://mywebhookurl.com/qbt_manage
  # run_start: notifiarr
  # run_end: apprise
  # function:
  #   cross_seed: https://mywebhookurl.com/qbt_manage
  #   recheck: notifiarr
  #   cat_update: apprise
  #   tag_update: notifiarr
  #   rem_unregistered: notifiarr
  #   tag_tracker_error: notifiarr
  #   rem_orphaned: notifiarr
  #   tag_nohardlinks: notifiarr
  #   cleanup_dirs: notifiarr

# bhd:
  # BHD Integration used for checking unregistered torrents
  # apikey:
webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    cleanup_dirs:
```

### Logs

https://gist.github.com/aaearon/c29276c825a19caf614e1233fafb6048

### Screenshots

![image](https://user-images.githubusercontent.com/812640/220427420-969ad2c4-4331-4640-af67-1cc0a229996f.png)

### Installation

Local

### Version Number

3.4.3

### What branch are you on?

master
