### ISSUE TITLE
cant get categories anymore

### ISSUE THREAD

**Issue by DuzAwe** [StuffAnThings/qbit_manage#25]
Hi, 

Scripts been working for awhile tagging and catting. I want to use it to remove orphaned files but it was clearing out my whole folder.
I'm now getting this when I try to use it normally.

```
Traceback (most recent call last):
  File "/mnt/user/scripts/qbit/qbit_manage.py", line 629, in <module>
    run()
  File "/mnt/user/scripts/qbit/qbit_manage.py", line 622, in run
    rem_unregistered()
  File "/mnt/user/scripts/qbit/qbit_manage.py", line 354, in rem_unregistered
    torrentdict = get_torrent_info(torrent_list)
  File "/mnt/user/scripts/qbit/qbit_manage.py", line 181, in get_torrent_info
    category = get_category(save_path)
  File "/mnt/user/scripts/qbit/qbit_manage.py", line 140, in get_category
    for i, f in cat_path.items():
AttributeError: 'str' object has no attribute 'items'
```

Config

```
directory:
  # Do not remove these
  # Cross-seed var: </downloads/cross-seed/> #Output directory of cross-seed 
  # root_dir var: </downloads/keeps/> #Root downloads directory used to check for orphaned files
  # <OPTIONAL> remote_dir var: </your/path/here/> # Path of docker host mapping of root_dir
  cross_seed: '/mnt/user/Downloads/cross-seed/'
  root_dir: '/mnt/user/Downloads/keeps/'
  remote_dir: '/mnt/user/Downloads/keeps/'

# Category/Pathing Parameters
cat:
  # <Category Name> : <save_path> #Path of your save directory. Can be a keyword or full path
  Cross:'keeps'
  LongTerm:'keeps'
  Refund:'keeps'
  Upload:'keeps'
  radarr:'keeps'
  tv-sonarr:'keeps'

# Tag Parameter
tags:
  # <Tracker URL Keyword>: <Tag Name>
  beyond-hd: Beyond-HD
  animebytes.tv: AnimeBytes
  torrentleech: TorrentLeech
  tleechreload: TorrentLeech
  blutopia: Blutopia
  baconbits: BaconBits
  digitalcore: DigitalCore
  myanonamouse: MyAnonaMouse
  torrentday: TorrentDay
  empirehost: IPTorrents
  td-peers: TorrentDay
  nebulance: Nebulance
  anthelion: Anthelion
  iptorrents: IPTorrents
  torrentseeds: TorrentSeeds
  theempire: TheEmpire
  peerjunkies: PeerJunkies
  torrentdb: TorrentDB
  filelist: FileList
  nyaa: Nyaa
```

**Comment by Drazzilb08** [comment]
I assume you're using this in a docker container? 
Unraid possibly?
By the looks of your config file it appears it is set up improperly

If you are in fact using a docker container I seriously doubt your path within the container contains `/mnt/user/` 

Example within my container I have `/mnt/user/data/:/data/`
So within my config file I have 
Root_sir set to `/data/.torrents/`
And remote_dir set to `/mnt/user/data/.torrents`

**Comment by DuzAwe** [comment]
That would be correct for the cats and yes It is unraid. 

Ah so I had it inverted it should be as bellow?

I'm still getting the same error.  I don't necessarily need cats set up but the script wont seem to run -r or -ro if its not.

```
directory:
  # Do not remove these
  # Cross-seed var: </downloads/cross-seed/> #Output directory of cross-seed 
  cross_seed: '/mnt/user/Downloads/cross-seed/'
  root_dir: '/downloads/keeps/'
  remote_dir: '/mnt/user/downloads/keeps/'
```


Thank you for the help btw.

**Comment by Drazzilb08** [comment]
I'm just not sure why you're wanting to take all categories and set them to keeps. This is especially confusing if you have automatic torrent management set within qbit. Ideally you'd set a save path in my case
`/data/.torrents/movies:'movies'`
Since the anything in the movies directory will be forced to have the movies category. and if auto torrent mgmt is set it will be moved to that directory. 

Example of my readarr instance
```yaml

```

**Comment by DuzAwe** [comment]
I previously had anything that was had an empty cat in qbit being put in to a cross cat. If I take out the cat section I get errors.

```
python3 /mnt/user/scripts/qbit/qbit_manage.py -c /mnt/user/scripts/qbit/config.yml -ms --dry-run
Traceback (most recent call last):
  File "/mnt/user/scripts/qbit/qbit_manage.py", line 629, in <module>
    run()
  File "/mnt/user/scripts/qbit/qbit_manage.py", line 620, in run
    update_category()
  File "/mnt/user/scripts/qbit/qbit_manage.py", line 297, in update_category
    new_cat = get_category(torrent.save_path)
  File "/mnt/user/scripts/qbit/qbit_manage.py", line 139, in get_category
    cat_path = cfg["cat"]
KeyError: 'cat'
```

And when I put it back in 
```
root@TheLibrary:~# nano /mnt/user/scripts/qbit/config.ymlroot@TheLibrary:~# python3 /mnt/user/scripts/qbit/qbit_manage.py -c /mnt/user/scripts/qbit/config.yml -ms --dry-run
Traceback (most recent call last):
  File "/mnt/user/scripts/qbit/qbit_manage.py", line 629, in <module>
    run()
  File "/mnt/user/scripts/qbit/qbit_manage.py", line 620, in run
    update_category()
  File "/mnt/user/scripts/qbit/qbit_manage.py", line 297, in update_category
    new_cat = get_category(torrent.save_path)
  File "/mnt/user/scripts/qbit/qbit_manage.py", line 140, in get_category
    for i, f in cat_path.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

I have fixed the D it was late when I looked at it yesterday. Above errors are with it fixed.

**Comment by Drazzilb08** [comment]
Interesting. 
I guess final question. Are you adding all your categories in? It will throw errors if not all your categories that are in qbit aren't added.

As far as them all being thrown as orphaned files. 

Any files that do not have an associated torrent will be thrown into the orphaned folder so that you can deal with it as you wish.

**Comment by DuzAwe** [comment]
All are added, unless uncategorised counts as one?

On the orphaned files its finding 1000+ files I can assure you that is incorrect.

**Comment by Drazzilb08** [comment]
Can you please provide an updated config file to review?

**Comment by bobokun** [comment]
Please update to the latest development branch code. Category/tag is no longer mandatory for -r and -ro

**Comment by DuzAwe** [comment]
That seems to have it fixed 👍 -r and -ro working now without issue.  -m still throwing issues, Ideally this should just cat anything that does not already have a category from the qbit cats. It had done previously. 

updated config that still throws errors for cat stuff.
v.1
```
directory:
  # Do not remove these
  # Cross-seed var: </downloads/cross-seed/> #Output directory of cross-seed 
  # root_dir var: </downloads/keeps/> #Root downloads directory used to check for orphaned files
  # <OPTIONAL> remote_dir var: </your/path/here/> # Path of docker host mapping of root_dir
  cross_seed: '/mnt/user/Downloads/cross-seed/'
  root_dir: '/downloads/keeps/'
  remote_dir: '/mnt/user/Downloads/keeps/'

cat:
  # <Category Name> : <save_path> #Path of your save directory. Can be a keyword or full path
  Cross:
  LongTerm:
  Refund:
  Upload:
  books:
  radarr:
  tv-sonarr:

# Tag Parameter
tags:
  # <Tracker URL Keyword>: <Tag Name>
  beyond-hd: Beyond-HD
  animebytes.tv: AnimeBytes
  torrentleech: TorrentLeech
  tleechreload: TorrentLeech
  blutopia: Blutopia
  baconbits: BaconBits
  digitalcore: DigitalCore
  myanonamouse: MyAnonaMouse
  torrentday: TorrentDay
  empirehost: IPTorrents
  td-peers: TorrentDay
  nebulance: Nebulance
  anthelion: Anthelion
  iptorrents: IPTorrents
  torrentseeds: TorrentSeeds
  theempire: TheEmpire
  peerjunkies: PeerJunkies
  torrentdb: TorrentDB
  filelist: FileList
  nyaa: Nyaa
```

v.2
```

cat:
  # <Category Name> : <save_path> #Path of your save directory. Can be a keyword or full path
  Cross: 'keeps'
  LongTerm: 'keeps'
  Refund: 'keeps'
  Upload: 'keeps'
  books: 'keeps'
  radarr: 'keeps'
  tv-sonarr: 'keeps'

```
v.3
```

cat:
  # <Category Name> : <save_path> #Path of your save directory. Can be a keyword or full path
  Cross: '/downloads/keeps/'
  LongTerm: '/downloads/keeps/'
  Refund: '/downloads/keeps/'
  Upload: '/downloads/keeps/'
  books: '/downloads/keeps/'
  radarr: '/downloads/keeps/'
  tv-sonarr: 'keeps'
```
