### ISSUE TITLE
[FR]: Remove torrents at category and tracker level

### ISSUE THREAD

**Issue by Siriussee** [StuffAnThings/qbit_manage#259]
### Is your feature request related to a problem? Please elaborate.

I want to use the `no_hardlink` module to remove torrents automatically. However, it is not an easy job with the current config:
```
nohardlinks:
  cache:
    exclude_tags:
    - tracker_A_tag
    - tracker_B_tag
    - .... all of the trackers except tracker X which you really want to deal with
    cleanup: true
    min_seeding_time: 43200 # tracker X has a 0.5 day h&r rule
```

### Describe the solution you'd like

A new attribute `include_tag` solves it well. The tedious config can now be simplified as:
```
nohardlinks:
  cache:
    include_tag:
    - tracker_X_tag
    cleanup: true
    min_seeding_time: 43200  # tracker X has a 0.5 day h&r rule
```

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

A 3rd party repo, [autoremove](https://github.com/jerrymakesjelly/autoremove-torrents) does a similar job. However, it is no longer maintained and does not work with `qbit >= 4.5`. 

### Who will this benefit?

Freeleech torrent racers.

**Comment by bakerboy448** [comment]
I don't see why this is needed?
Set the values at the tracker level and then just don't set them at the noHL level?

min seed time has no impact until the ratio goal comes into play

**Comment by Siriussee** [comment]
Actually, what I am thinking is controlling the life span of torrents at the tracker level. And what I proposed happened to reuse part of the functionality of NoHL. I am also happy to have an individual module (say, "clear cache") to do this job.
```
clearcache:
  cache: # cat name
    include_tag:
    - tracker_X
    cleanup: true
    max_seeding_time: 43200  # delete after seeding 0.5 d, or
    max_ratio: 2 # delete after seeding double the size of the torrent
```
