### ISSUE TITLE
[Bug]: QBM crashes when cross-seed is enabled

### ISSUE THREAD

**Issue by BaukeZwart** [StuffAnThings/qbit_manage#260]
### Describe the Bug

When enabling cross-seed qbm regularly crashes with the following error below.
Ofthen when running qbm a second time immediately after the crash with same config it runs without errors.

### Config

```yaml
# Please refer to the link below for more details on how to set up the configuration file
# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

commands:
  dry_run: false
  cross_seed: false
  recheck: false
  cat_update: true
  tag_update: true
  rem_unregistered: true
  tag_tracker_error: true
  rem_orphaned: true
  tag_nohardlinks: true
  skip_cleanup: false

qbt:
  host: http://127.0.0.1:XXXXXX
  user: REDACTED
  pass: REDACTED

settings:
  force_auto_tmm: true
  tracker_error_tag: issue
  nohardlinks_tag: noHL
  ignoreTags_OnUpdate:
    - noHL
    - issue
    - cross-seed
    - upgraderr
    - race

directory:
  root_dir: /home/REDACTED/torrents/qbittorrent
  remote_dir: /home/REDACTED/torrents/qbittorrent
  cross_seed: /home/REDACTED/torrents/qbittorrent/cross-seed
  recycle_bin: /home/REDACTED/torrents/qbittorrent/.RecycleBin
  torrents_dir: /home/REDACTED/.local/share/qBittorrent/BT_backup
  orphaned_dir: /home/REDACTED/torrents/qbittorrent/orphaned_data

cat:
  radarr: /home/REDACTED/torrents/qbittorrent/movies
  radarr.cross-seed: /home/REDACTED/torrents/qbittorrent/movies
  movies: /home/REDACTED/torrents/qbittorrent/movies
  movies.cross-seed: /home/REDACTED/torrents/qbittorrent/movies
  movies-lts: /home/REDACTED/torrents/qbittorrent/movies
  movies-lts.cross-seed: /home/REDACTED/torrents/qbittorrent/movies
  race-movies: /home/REDACTED/torrents/qbittorrent/race-movies
  race-movies.cross-seed: /home/REDACTED/torrents/qbittorrent/race-movies
  race-movies-lts: /home/REDACTED/torrents/qbittorrent/race-movies
  race-movies-lts.cross-seed: /home/REDACTED/torrents/qbittorrent/race-movies
  sonarr: /home/REDACTED/torrents/qbittorrent/tv
  sonarr.cross-seed: /home/REDACTED/torrents/qbittorrent/tv
  tv: /home/REDACTED/torrents/qbittorrent/tv
  tv.cross-seed: /home/REDACTED/torrents/qbittorrent/tv
  tv-lts: /home/REDACTED/torrents/qbittorrent/tv
  tv-lts.cross-seed: /home/REDACTED/torrents/qbittorrent/tv
  race-tv: /home/REDACTED/torrents/qbittorrent/race-tv
  race-tv.cross-seed: /home/REDACTED/torrents/qbittorrent/race-tv
  race-tv-lts: /home/REDACTED/torrents/qbittorrent/race-tv
  race-tv-lts.cross-seed: /home/REDACTED/torrents/qbittorrent/race-tv

  qbittorrent: /home/REDACTED/torrents/qbittorrent/
cat_change:
  radarr.cross-seed: movies
  radarr-lts.cross-seed: movies-lts
  movies.cross-seed: movies
  movies-lts.cross-seed: movies-lts
  race-movies.cross-seed: race-movies
  race-movies-lts.cross-seed: race-movies-lts
  sonarr.cross-seed: tv
  sonarr-lts.cross-seed: tv-lts
  tv.cross-seed: tv
  tv-lts.cross-seed: tv-lts
  race-tv.cross-seed: race-tv
  race-tv-lts.cross-seed: race-tv-lts

tracker:
  beyond-hd:
    tag: BeyondHD
    notifiarr: BeyondHD
  blutopia:
    tag: Blutopia
    notifiarr: Blutopia
  hdts:
    tag: HDTorrents
    notifiarr: HDTorrents
  torrentleech:
    tag: Torrentleech
    notifiarr: Torrentleech
  tleechreload:
    tag: Torrentleech
    notifiarr: Torrentleech
  td:
    tag: TorrentDay
    notifiarr: TorrentDay
  jumbohostpro:
    tag: TorrentDay
    notifiarr: TorrentDay
  stackoverflow:
    tag: IPTorrents
    notifiarr: IPTorrents
  bgp.technology:
    tag: IPTorrents
    notifiarr: IPTorrents
  empirehost:
    tag: IPTorrents
    notifiarr: IPTorrents
  torrentseeds:
    tag: TorrentSeeds
    notifiarr: TorrentSeeds
  aither:
    tag: Aither
    notifiarr: Aither
  reactor.filelist:
    tag: FileList
    notifiarr: FileList
  reactor.flro:
    tag: FileList
    notifiarr: FileList
  immortalseed:
    tag: Immortalseed
    notifiarr: Immortalseed
  digitalcore:
    tag: DigitalCore
    notifiarr: DigitalCore
  hawke.uno:
    tag: HUNO
    notifiarr: HUNO
  privatehd:
    tag: PrivateHD
    notifiarr: PrivateHD
  scenetime:
    tag: SceneTime
    notifiarr: SceneTime
  morethantv:
    tag: MoreThanTV
    notifiarr: MoreThanTV
  nebulance.io:
    tag: Nebulance
    notifiarr: Nebulance
  superbits:
    tag: Superbits
    notifiarr: Superbits
  sptracker:
    tag: Superbits
    notifiarr: Superbits
  hd-space:
    tag: HD-Space
    notifiarr: HD-Space
  uhdbits:
    tag: UHDBits
    notifiarr: UHDBits
  anthelion:
    tag: Anthelion
    notifiarr: Anthelion

nohardlinks:
  movies-lts:
    exclude_tags:
    cleanup: true
    max_seeding_time: 14400
    min_seeding_time:
    max_ratio:
    limit_upload_speed:
    resume_torrent_after_untagging_noHL: true
  tv-lts:
    exclude_tags:
    cleanup: true
    max_seeding_time: 14400
    min_seeding_time:
    max_ratio:
    limit_upload_speed:
    resume_torrent_after_untagging_noHL: true
  race-movies-lts:
    exclude_tags:
    cleanup: true
    max_seeding_time: 14400
    min_seeding_time:
    max_ratio:
    limit_upload_speed:
    resume_torrent_after_untagging_noHL: true
  race-tv-lts:
    exclude_tags:
    cleanup: true
    max_seeding_time: 14400
    min_seeding_time:
    max_ratio:
    limit_upload_speed:
    resume_torrent_after_untagging_noHL: true

recyclebin:
  enabled: false
  empty_after_x_days: 1
  save_torrents: false
  split_by_category: false

orphaned:
  empty_after_x_days: 0
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'

notifiarr:
  apikey: REDACTED
  instance: hostedbydesign

webhooks:
  error: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  function:
    cross_seed:
    recheck: notifiarr
    cat_update: notifiarr
    tag_update: notifiarr
    rem_unregistered: notifiarr
    rem_orphaned: notifiarr
    tag_nohardlinks: notifiarr
    cleanup_dirs: notifiarr
    tag_tracker_error: notifiarr

bhd:
  apikey: REDACTED
```

### Logs

https://gist.github.com/BaukeZwart/cf006afd6c6f515a7b860773d1f43e0b

### Installation

Local

### Version Number

3.5.1

### What branch are you on?

develop
