### ISSUE TITLE
[Bug]: AttributeError: 'Qbt' object has no attribute 'global_max_ratioget_category'

### ISSUE THREAD

**Issue by pax0707** [StuffAnThings/qbit_manage#270]
### Describe the Bug

When a new crossseed torrent is found it breaks with error:

AttributeError: 'Qbt' object has no attribute 'global_max_ratioget_category'

### Config

```yaml
# This is an example configuration file that documents all the options.
# It will need to be modified for your specific use case.
# Please refer to the link below for more details on how to set up the configuration file
# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

commands:
  # The commands defined below will IGNORE any commands used in command line and docker env variables.
  dry_run: false
  cross_seed: true
  recheck: true
  cat_update: false
  tag_update: true
  rem_unregistered: true
  tag_tracker_error: true
  rem_orphaned: true
  tag_nohardlinks: true
  skip_cleanup: false

qbt:
  # qBittorrent parameters
  host: localhost:9098
  user: xxx
  pass: xxx

settings:
  force_auto_tmm: false  # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: ===ERROR===  # Will set the tag of any torrents that do not have a working tracker.
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has one or more of the tags defined here.
  - ===NOHL===
  - ===ERROR===
  - cross-seed
  nohardlinks_tag: ===NOHL===
directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  # root_dir var: </your/path/here/>  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  # <OPTIONAL> remote_dir var: </your/path/here/>  # Path of docker host mapping of root_dir.
  # Must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # <OPTIONAL> torrents_dir var: </your/path/here/>  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin

  cross_seed: D:\QBT\Torrents\CS\cross-seed
  root_dir: D:\QBT\Done\
  remote_dir: D:\QBT\Done\
  recycle_bin: D:\QBT\Recycle\
  torrents_dir: C:\Users\pax07\AppData\Local\qBittorrent\BT_backup\
  orphaned_dir: D:\QBT\Orphaned\
cat:
  SERIES/SONARR: D:\QBT\Done\SERIES\SONARR\
  SERIES/MEDUSA: D:\QBT\Done\SERIES\Medusa\
  SERIES/101: D:\QBT\Done\SERIES\101\
  MOVIES/RADARR: D:\QBT\Done\MOVIES\RADARR\
  MOVIES/PTP: D:\QBT\Done\MOVIES\PTP\
  SITE/AlphaRatio: D:\QBT\Done\SITE\AlphaRatio\
  SITE/Keep Alive: D:\QBT\Done\SITE\Keep Alive\
  SERIES/B5: D:\QBT\Done\SERIES\B5\
  SITE: D:\QBT\Done\SITE\
  SITE/The Geeks: D:\QBT\Done\SITE\The Geeks\
  Redacted: D:\QBT\Done\SITE\Redacted\
  Done: D:\QBT\Done\
  Sonarr: D:\QBT\Done\SERIES\Sonarr\
tracker:
  # Tag Parameters
  # <Tracker URL Keyword>:    # <MANDATORY> This is the keyword in the tracker url
  # <MANDATORY> Set tag name. Can be a list of tags or a single tag
  #   tag: <Tag Name>
  # <OPTIONAL> Will set the torrent Maximum share ratio until torrent is stopped from seeding/uploading. -2 means the global limit should be used, -1 means no limit.
  #   max_ratio: 5.0
  # <OPTIONAL> Will set the torrent Maximum seeding time (min) until torrent is stopped from seeding. -2 means the global limit should be used, -1 means no limit.
  #   max_seeding_time: 129600
  # <OPTIONAL> Will ensure that noHL torrents from this tracker are not deleted by cleanup variable if torrent has not yet met the minimum seeding time (min).
  #   min_seeding_time: 2000
  # <OPTIONAL> Will limit the upload speed KiB/s (KiloBytes/second) (-1 sets the limit to infinity)
  #   limit_upload_speed: 150
  # <OPTIONAL> Set this to the notifiarr react name. This is used to add indexer reactions to the notifications sent by Notifiarr
  #   notifiarr: <notifiarr indexer>
  animebytes.tv:
    tag: AnimeBytes
    max_ratio: 3
  beyond-hd:
    tag: Beyond-HD
    max_ratio: -1
  gazellegames:
    tag: GazelleGames
    max_ratio: -1
  landof.tv:
    tag: BroadcasTheNet
    max_ratio: -1
  myanonamouse:
    tag: MyAnonamouse
    max_ratio: -1
  passthepopcorn:
    tag: PassThePopcorn
    max_ratio: -1
  tleechreload:
    tag: TorrentLeech
    max_ratio: 3
  torrentdb:
    tag: TorrentDB
    vmax_ratio: 3
  torrentleech:
    tag: TorrentLeech
    max_ratio: 3
  hdbits:
    tag: HDBits
    max_ratio: 5
  morethantv:
    tag: MoreThanTV
    max_ratio: 3
  filelist.io:
    tag: FileList
    max_ratio: 5
  stackoverflow.tech:
    tag: IPTorrents
    max_ratio: 3
  alpharatio.cc:
    tag: AlphaRatio
    max_ratio: 3
  torrenthr.org:
    tag: TorrentHR
    max_ratio: 5
  opsfet.ch:
    tag: Orpheus
    max_ratio: -1
  hd-space.pw:
    tag: HD-Space
    max_ratio: 3
  bit-hdtv.com:
    tag: BIT-HDTV
    max_ratio: 3
  bibliotik.me:
    tag: Bibliotik
    max_ratio: -1
  music-vid.com:
    tag: MusicVids
    max_ratio: -1
  flacsfor.me:
    tag: Redacted
    max_ratio: -1
  thegeeks.click:
    tag: TheGeeks
    max_ratio: 5
  immortalseed.me:
    tag: Imortalseed
    max_ratio: 3
  other:
    tag: ===OTHER===
    max_ratio: 3
nohardlinks:
  MOVIES/RADARR:
    exclude_tags:
    cleanup: false
  MOVIES/PTP:
    exclude_tags:
    cleanup: false
  SERIES/SONARR:
    exclude_tags:
    cleanup: false
recyclebin:
  # Recycle Bin method of deletion will move files into the recycle bin (Located in /root_dir/.RecycleBin) instead of directly deleting them in qbit
  # By default the Recycle Bin will be emptied on every run of the qbit_manage script if empty_after_x_days is defined.
  enabled: false
  # <OPTIONAL> empty_after_x_days var:
  # Will automatically remove all files and folders in recycle bin after x days. (Checks every script run)
  # If this variable is not defined it, the RecycleBin will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 60
  # <OPTIONAL> save_torrents var:
  # If this option is set to true you MUST fill out the torrents_dir in the directory attribute.
  # This will save a copy of your .torrent and .fastresume file in the recycle bin before deleting it from qbittorrent
  save_torrents: true
  # <OPTIONAL> split_by_category var:
  # This will split the recycle bin folder by the save path defined in the `cat` attribute
  # and add the base folder name of the recycle bin that was defined in the `recycle_bin` sub-attribute under directory.
  split_by_category: false

orphaned:
  # Orphaned files are those in the root_dir download directory that are not referenced by any active torrents.
  # Will automatically remove all files and folders in orphaned data after x days. (Checks every script run)
  # If this variable is not defined it, the orphaned data will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 60
  # File patterns that will not be considered orphaned files. Handy for generated files that aren't part of the torrent but belong with the torrent's files
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'

#apprise:
  # Apprise integration with webhooks
  # Leave Empty/Blank to disable
  # Mandatory to fill out the url of your apprise API endpoint
  #api_url:
  # Mandatory to fill out the notification url/urls based on the notification services provided by apprise. https://github.com/caronc/apprise/wiki
  #notify_url:

#notifiarr:
  # Notifiarr integration with webhooks
  # Leave Empty/Blank to disable
  # Mandatory to fill out API Key
  #apikey:
  # <OPTIONAL> Set to a unique value (could be your username on notifiarr for example)
  #instance:

webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    cleanup_dirs:

bhd:
  # BHD Integration used for checking unregistered torrents
  apikey: xxxx
```

### Logs

https://gist.github.com/pax0707/d1111049cd84eef62501495fda9e2c60

### Installation

Local

### Version Number

3.6.1

### What branch are you on?

master
