### ISSUE TITLE
[Bug]: Fresh Installation of the docker image fails to launch

### ISSUE THREAD

**Issue by AN1MATEK** [StuffAnThings/qbit_manage#282]
### Describe the Bug

After installing the docker image and initializing the configuration file, the main script seems to meet a critical error. It calls an internal function. 

### Config

```yaml
commands:
  # The commands defined below will IGNORE any commands used in command line and docker env variables.
  dry_run: true
  cross_seed: false
  recheck: false
  cat_update: false
  tag_update: true
  rem_unregistered: true
  tag_tracker_error: false
  rem_orphaned: true
  tag_nohardlinks: true
  skip_cleanup: false
settings:
  force_auto_tmm: false
  tracker_error_tag: issue
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has at least one or more of the tags defined here. Otherwise torrents will not be tagged if tags exist.
    - noHL
    - issue
    - cross-seed
  nohardlinks_tag: noHL
cat_change:
tracker:
  # Mandatory
  # Tag Parameters
  # <Tracker URL Keyword>:    # <MANDATORY> This is the keyword in the tracker url
  # <MANDATORY> Set tag name. Can be a list of tags or a single tag
  #   tag: <Tag Name>
  # <OPTIONAL> Will set the torrent Maximum share ratio until torrent is stopped from seeding/uploading. -2 means the global limit should be used, -1 means no limit.
  #   max_ratio: 5.0
  # <OPTIONAL> Will set the torrent Maximum seeding time (min) until torrent is stopped from seeding. -2 means the global limit should be used, -1 means no limit.
  #   max_seeding_time: 129600
  # <OPTIONAL> Will ensure that noHL torrents from this tracker are not deleted by cleanup variable if torrent has not yet met the minimum seeding time (min).
  #   min_seeding_time: 2000
  # <OPTIONAL> Will limit the upload speed KiB/s (KiloBytes/second) (-1 means no limit)
  #   limit_upload_speed: 150
  # <OPTIONAL> Set this to the notifiarr react name. This is used to add indexer reactions to the notifications sent by Notifiarr
  #   notifiarr: <notifiarr indexer>
  torrentleech:
    tag: TorrentLeech
  digitalcore:
    tag: DigitalCore
  empirehost:
    tag: IPTorrents
  cinemaz:
    tag: CinemaZ
  oldtoons:
    tag: Old Toons
  speed.connecting:
    tag: Speed.CD
  other:
    tag: other
apprise:
notifiarr:
webhooks:
bhd:
qbt:
  host: 10.1.1.5:8180  # Port is indeed 8180
  user: qbt
  pass: %PASSWORD%
directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  # root_dir var: </your/path/here/>  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  # <OPTIONAL> remote_dir var: </your/path/here/>  # Path of docker host mapping of root_dir.
  # Must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # <OPTIONAL> torrents_dir var: </your/path/here/>  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin

  cross_seed: /downloads/.cross-seed
  root_dir: /downloads
  remote_dir: /downloads
  recycle_bin: /downloads/.RecycleBin
  torrents_dir: /BT_Backup
  orphaned_dir: /downloads/orphaned
cat:
  Movies: /downloads/movies
  TV Shows: /downloads/tv
nohardlinks:
  # Tag Movies/Series that are not hard linked
  # Mandatory to fill out directory parameter above to use this function (root_dir/remote_dir)
  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
  AutoDL:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28.800
    limit_upload_speed: -1
    min_seeding_time: 21600
    resume_torrent_after_untagging_noHL: true
  Movies:
    exclude_tags:
      - cross-seed
    cleanup: false
    resume_torrent_after_untagging_noHL: true
  TV Shows:
    exclude_tags:
      - cross-seed
    cleanup: false
    resume_torrent_after_untagging_noHL: true
recyclebin:
  # Recycle Bin method of deletion will move files into the recycle bin (Located in /root_dir/.RecycleBin) instead of directly deleting them in qbit
  # By default the Recycle Bin will be emptied on every run of the qbit_manage script if empty_after_x_days is defined.
  enabled: true
  empty_after_x_days: 14
  save_torrents: true
  split_by_category: true
orphaned:
  # Orphaned files are those in the root_dir download directory that are not referenced by any active torrents.
  # Will automatically remove all files and folders in orphaned data after x days. (Checks every script run)
  # If this variable is not defined it, the orphaned data will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 60
  exclude_patterns:
    - '**/.DS_Store'
    - '**/Thumbs.db'
    - '**/@eaDir'
    - '**/*.!qB'
    - '**/_unpackerred'

-----------------------------------------------------

networks:
  default:
    name: download
    ipam:
      config:
        - subnet: 10.1.3.0/24
services:
  pia:
    networks:
      default:
        ipv4_address: 10.1.3.20
    image: thrnz/docker-wireguard-pia:latest
    container_name: pia
    volumes:
      # Auth token
      - ./pia/config:/pia/config
      # Forwarded port
      - ./pia/shared:/pia-shared
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - UMASK=${UMASK}
      # Region (swiss|de-frankfurt)
      - LOC=de-frankfurt
      - USER=${OPENVPN_USER}
      - PASS=${OPENVPN_PASSWORD}
      - PORT_FORWARDING=1
      - PORT_FILE=/pia-shared/new_port
      - LOCAL_NETWORK=10.1.1.0/24
    healthcheck:
      test: ping -c 1 https://www.quad9.net/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 8180:8180
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: nzb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ./nzb:/config
      - /mnt/WD/nzb:/nzb
      - /mnt/Backup/sabnzbd:/backup
    ports:
      - 8080:8080
    networks:
      default:
        ipv4_address: 10.1.3.11
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest        #libtorrentv1-release-4.5.0_v1.2.18-ls7
    container_name: qbt
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        - UMASK=${UMASK}
        - WEBUI_PORT=8180
    volumes:
        - ./qbt/config:/config
        - ./qbt/initd.qbt:/custom-cont-init.d
        - ./qbt/scripts:/scripts
        - ./pia/shared:/shared
        - /mnt/WD/torrent:/downloads
    restart: unless-stopped
    network_mode: service:pia

  cross-seed:
    image: crossseed/cross-seed:latest
    container_name: cs
    user: ${PGID}:${PUID}
    networks:
      default:
        ipv4_address: 10.1.3.12
    volumes:
      - ./cs:/config
      - /mnt/WD/torrent/.torrents:/torrents:ro # note that this volume can and should be mounted read-only
      - /mnt/WD/torrent/.cross-seed:/output
    command: daemon # this enables the daemon
    restart: unless-stopped

  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    user: ${PGID}:${PUID}
    environment:
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ./autobrr/config:/config
      - ./autobrr/logs:/logs
    ports:
      - 7474:7474
    networks:
      default:
        ipv4_address: 10.1.3.13

  qbit_manage:
    container_name: qbm
    image: bobokun/qbit_manage:latest
    user: ${PGID}:${PUID}
    volumes:
      - /home/pi/Containers/download/qbm:/config
      - /home/pi/Containers/download/qbm/config/qBittorrent/BT_backup:/BT_Backup
      - /mnt/WD/torrent:/downloads
    environment:
      - TZ=${TZ}
      - UMASK=${UMASK}
      - QBT_LOG_LEVEL=DEBUG
#      - QBT_DIVIDER==
#      - QBT_WIDTH=100
    networks:
      default:
        ipv4_address: 10.1.3.14
    restart: unless-stopped
```

### Logs

<script src="https://gist.github.com/AN1MATEK/a8b9c68bcb4402e11ebd2c63eb7ad339.js"></script>

### Installation

Docker

### Version Number

Ive tried many, but let's say v3.6.2

### What branch are you on?

master
