### ISSUE TITLE
[Bug]: Logs not respecting category choice for cross-seed torrent file injections.

### ISSUE THREAD

**Issue by yammes08** [StuffAnThings/qbit_manage#292]
### Describe the Bug

When using the cross-seed funtionality, to inject .torrent files that cross-seed itself has failed to inject, the logs appear to show them being added to an incorrect category. The category displayed would seem to be the fist alphabetical match with the same path. In qbit itself though, the torrent seems to be added to the correct category. Some users use multiple categories with the same path.

### Config

```yaml
# This is an example configuration file that documents all the options.
# It will need to be modified for your specific use case.
# Please refer to the link below for more details on how to set up the configuration file
# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

# qBittorrent parameters
qbt:
  host: qbittorrent-vpn:8080
  user: [redacted]
  pass: [redacted]

settings:
  force_auto_tmm: false
  tracker_error_tag: issue
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has one or more of the tags defined here.
  - noHL
  - issue
  - cross-seed
  nohardlinks_tag: noHL
directory:
  cross_seed: /cross-seed/
  root_dir: /data/torrents/
  remote_dir: /data/torrents/
  recycle_bin: /data/torrents/.RecycleBin
  torrents_dir: /qbit_appdata
  orphaned_dir: /data/torrents/orphaned_data
cat:
  bhdstudio-1080p: /data/torrents/movies
  bhdstudio-1080p.cross-seed: /data/torrents/movies
  bhdstudio-2160p: /data/torrents/movies-4k
  bhdstudio-2160p.cross-seed: /data/torrents/movies-4k
  cross-seed-data: /data/torrents/cross-seed-data
  cross-seed-data.cross-seed: /data/torrents/cross-seed-data
  framestor-1080p: /data/torrents/movies-4k
  framestor-1080p.cross-seed: /data/torrents/movies-4k
  framestor-2160p: /data/torrents/movies-4k
  framestor-2160p.cross-seed: /data/torrents/movies-4k
  movies: /data/torrents/movies
  movies-completed: /data/torrents/movies
  movies-completed.cross-seed: /data/torrents/movies
  movies.cross-seed: /data/torrents/movies
  movies-4k: /data/torrents/movies-4k
  movies-4k-completed: /data/torrents/movies-4k
  movies-4k-completed.cross-seed: /data/torrents/movies-4k
  movies-4k.cross-seed: /data/torrents/movies-4k
  music: /data/torrents/music
  music-completed: /data/torrents/music
  music-completed.cross-seed: /data/torrents/music
  music.cross-seed: /data/torrents/music
  ratio: /data/torrents/ratio
  ratio.cross-seed: /data/torrents/ratio
  tv: /data/torrents/tv
  tv-4k: /data/torrents/tv-4k
  tv-4k-completed: /data/torrents/tv-4k
  tv-4k-completed.cross-seed: /data/torrents/tv-4k
  tv-4k.cross-seed: /data/torrents/tv-4k
  tv-completed: /data/torrents/tv
  tv-completed.cross-seed: /data/torrents/tv
  tv.cross-seed: /data/torrents/tv
  books: /data/torrents/books
  books-completed: /data/torrents/books
  books.cross-seed: /data/torrents/books
  books-completed.cross-seed: /data/torrents/books
  torrents: /data/torrents/

tracker:
  tleechreload:
    tag: TorrentLeech
    limit_upload_speed: 128
  torrentleech:
    tag: TorrentLeech
    limit_upload_speed: 128
  cinemaz:
    tag: Cinemaz
  localhost.stackoverflow.tech:
    tag: IPTorrents
    limit_upload_speed: 128
  immortalseed.me:
    tag: Immortalseed
  digitalcore.club:
    tag: Digitalcore
  hawke.uno:
    tag: hawke-uno
  blutopia.xyz:
    tag: Blutopia
  blutopia.cc:
    tag: Blutopia
  hdts-announce.ru:
    tag: HDTorrents
  reactor.filelist.io:
    tag: FileList
    limit_upload_speed: 128
  reactor.flro.org:
    tag: FileList
    limit_upload_speed: 128
  beyond-hd:
    tag: Beyond-HD

  routing.bgp.technology:
    tag: routing.bgp.technology
nohardlinks:
  bhdstudio-1080p:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  bhdstudio-1080p.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  bhdstudio-2160p:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  bhdstudio-2160p.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  cross-seed-data:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  cross-seed-data.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  framestor-1080p:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  framestor-1080p.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  framestor-2160p:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  framestor-2160p.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  movies-completed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  movies-completed.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  movies.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  movies-4k-completed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  movies-4k-completed.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  movies-4k.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  music-completed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  music-completed.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  music.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  ratio:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  ratio.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  tv-4k-completed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  tv-4k-completed.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  tv-4k.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  tv-completed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  tv-completed.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  tv.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  books-completed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  books-completed.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true
  books.cross-seed:
    exclude_tags:
    cleanup: true
    max_ratio: 10.0
    max_seeding_time: 28800
    limit_upload_speed:
    min_seeding_time: 0
    resume_torrent_after_untagging_noHL: true

recyclebin:
  enabled: true
  empty_after_x_days: 3
  save_torrents: true
  split_by_category: false

orphaned:
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - '**/*.!qB'
  empty_after_x_days: 3

notifiarr:
  apikey: [redacted]
  instance: qBittorrent-VPN

webhooks:
  error: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  function:
    cross_seed: notifiarr
    recheck: notifiarr
    cat_update: notifiarr
    tag_update: notifiarr
    rem_unregistered: notifiarr
    rem_orphaned: notifiarr
    tag_nohardlinks: notifiarr
    empty_recyclebin: notifiarr
    tag_tracker_error:

bhd:
  apikey: [redacted]
```

### Logs

https://gist.github.com/yammes08/995d696469e0c9ff5563069f9205f6c0

### Installation

Unraid

### Version Number

3.6.3

### What branch are you on?

develop
