### ISSUE TITLE
[Bug]: 3.6.3 Uncaught Exception "No such file or directory"

### ISSUE THREAD

**Issue by tordenflesk** [StuffAnThings/qbit_manage#302]
### Describe the Bug

After upgrading to 3.6.3 there's an error trying to load a torrent that's no longer in the client.
This was also an issue on 'Develop', so i went back to 'Latest'. Now that 3.6.3 got pushed the error returns.

### Config

```yaml
qbt:
  host: X
  user: X
  pass: X

settings:
  force_auto_tmm: false
  tracker_error_tag: issue
  ignoreTags_OnUpdate:
  - noHL
  - issue
  - cross-seed

  nohardlinks_tag: noHL
directory:
  cross_seed: /DATA01/downloads/watch/qbittorrent
  root_dir: /DATA01/downloads/complete
  recycle_bin: /DATA01/downloads/.RecycleBin
  torrents_dir: /config_QBT/BT_backup
  orphaned_dir: /DATA01/downloads/.orphaned_data
  remote_dir: /DATA01/downloads/complete

cat:
  BHD: /DATA01/downloads/complete/BHD
  BTN: /DATA01/downloads/complete/BTN
  CZ: /DATA01/downloads/complete/CZ
  CZ.cross-seed: /DATA01/downloads/complete/CZ
  EMP: /DATA01/downloads/complete/EMP
  NB: /DATA01/downloads/complete/NB
  RADARR: /DATA01/downloads/complete/RADARR
  RADARR.cross-seed: /DATA01/downloads/complete/RADARR
  SONARR: /DATA01/downloads/complete/SONARR
  SONARR.cross-seed: /DATA01/downloads/complete/SONARR
  TL: /DATA01/downloads/complete/TL
  TL.cross-seed: /DATA01/downloads/complete/TL
  _RR.cross-seed: /DATA01/downloads/complete/RR
  _RR: /DATA01/downloads/complete/RR
  SB: /DATA01/downloads/complete/SB/

  complete: /DATA01/downloads/complete/
tracker:
  hdts-announce:
    tag: _HDT
    max_ratio: 1.1
    max_seeding_time: 13824
  beyond-hd:
    tag: _BHD
    max_ratio: 1.1
    max_seeding_time: 13824
  landof.tv:
    tag: _BTN
    max_ratio: 1.1
    max_seeding_time: 8640
  tleechreload:
    tag: _TL
    max_ratio: 1.1
    max_seeding_time: 13824
  torrentleech:
    tag: _TL
    max_ratio: 1.1
    max_seeding_time: 13824
  superbits:
    tag: _SB
    max_ratio: 1.1
    max_seeding_time: 3744
  sptracker:
    tag: _SB
    max_ratio: 1.1
    max_seeding_time: 3744
  norbits:
    tag: _NB
    max_ratio: 1.1
  cathode-ray:
    tag: _CRT
    max_ratio: 1.1
  tracker.empornium.sx:
    tag: _EMP
    max_ratio: 1.1
  tracker.cinemaz.to:
    tag: _CZ
    max_ratio: 0.91
    max_seeding_time: 28320
  other:
    tag: _PBLC
    max_ratio: 1.1
nohardlinks:
  RADARR:
    cleanup: true
    exclude_tags:
  RADARR.cross-seed:
    cleanup: true
    exclude_tags:
  SONARR:
    cleanup: true
    exclude_tags:
  SONARR.cross-seed:
    cleanup: true
    exclude_tags:
  BTN:
    cleanup: true
    exclude_tags:
  BHD:
    cleanup: true
    exclude_tags:
  NB:
    cleanup: true
    exclude_tags:
  _RR:
    cleanup: false
    max_ratio: -1
    exclude_tags:
  _RR.cross-seed:
    cleanup: false
    max_ratio: -1
    exclude_tags:
recyclebin:
  enabled: false
  empty_after_x_days: 3
  split_by_category: false
  save_torrents: false

orphaned:
  empty_after_x_days: 6
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'
  - '**/*.mkv'

bhd:
  apikey: 

webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    cleanup_dirs:
```

### Logs

https://gist.github.com/tordenflesk/4ad11224551455d77492d44895304a73

### Installation

Docker

### Version Number

3.6.3

### What branch are you on?

master
