### ISSUE TITLE
[Bug]: Setting noHL limits for a specific category to anything less than 1 results in noHL tag/seed limits being applied each run

### ISSUE THREAD

**Issue by Davo1624** [StuffAnThings/qbit_manage#306]
### Describe the Bug

If you set `max_seed_limits` for a noHL category to -2, -1 or leave it blank, qbit-manage will continue to apply the noHL tag and seed limits every run.

### Config

```yaml
tv-complete:
    cleanup: true
    max_ratio: -1
    max_seeding_time: -1
    exclude_tags:
    min_seeding_time: 0
    limit_upload_speed:
    resume_torrent_after_untagging_noHL: true
```

### Logs

https://0bin.net/paste/DsjObPDA#3ofrjKLs6dIHCDGBdb5zCkqbCyL+DZZa32qmj1F2kg7

### Installation

Docker

### Version Number

3.6.3

### What branch are you on?

develop
