### ISSUE TITLE
[Bug]: Migration document is wrong

### ISSUE THREAD

**Issue by nodiaque** [StuffAnThings/qbit_manage#324]
### Describe the Bug

In the migration document at https://github.com/StuffAnThings/qbit_manage/wiki/v4-Migration-Guide, there is an error. If you copy this, it won't work. The new config template show the right tag.

The line 
sharelimits:

should be
share_limits:

### Config

```yaml
cat:
- movies: “/data/torrents/movies”
- tv: “/data/torrents/tv”
tracker:
  Tracker-a:
    tag: a
  Tracker-b:
    tag: b
    Tracker-c:
    tag: c
nohardlinks:
- movies
- tv
sharelimits:
  group1.noHL:
    priority: 1
    include_any_tags:
    - a
    - b
    include_all_tags:
    - noHL
    categories:
    - movies
    max_ratio: 2
    max_seeding_time: 75
    cleanup: true
  group1:
    priority: 2
    include_any_tags:
    - a
    - b
    categories:
    - movies
    max_ratio: 5
    max_seeding_time: 100
  group2.noHL:
    priority: 3
    include_any_tags:
    - c
    include_all_tags:
    - noHL
    categories:
    - tv
    max_ratio: 1
    max_seeding_time: 25
  group2:
    priority: 4
    include_any_tags:
    - c
    categories:
    - tv
    max_ratio:
    max_seeding_time:
```

### Logs

no need

### Installation

Unraid

### Version Number

4.0.0

### What branch are you on?

master
