### ISSUE TITLE
[Bug]: Zero value max_seeding_time & max_ratio zero not being applied.

### ISSUE THREAD

**Issue by scragly** [StuffAnThings/qbit_manage#327]
### Describe the Bug

It's possible to set 0 ratio and 0 minutes seeding time as share limits withing qbittorrent. When set, the behaviour is the torrent will immediately stop when it completes it's download. 

When these values are set in share_limits, it appears it'll be sent to the function set_tags_and_limits where it'll encounter the following falsey check:

https://github.com/StuffAnThings/qbit_manage/blob/a36a28b52c8508712cd0604501309fcff2cb20dc/modules/core/share_limits.py#L308

This results in limits of zero being skipped in being applied to qbittorrent, as `if 0` evaluates to false despite it being a valid value.

### Config

```yaml
share_limits:
  restricted:
    priority: 99
    max_seeding_time: 0
    max_ratio: 0
    cleanup: false
```

### Logs

no relevant log

### Installation

Unraid

### Version Number

4.0.0

### What branch are you on?

master
