### ISSUE TITLE
[Bug]: sharelimit not applied

### ISSUE THREAD

**Issue by nodiaque** [StuffAnThings/qbit_manage#329]
### Describe the Bug

Have 121 torrent tagged as iptorrents, 101 as TorrentLeech. Have 2 group of share limit, one for each. In qbittorrent, all I see is 1 group with only 8 member. I tried removing all tag but that didn't help

### Config

```yaml
# This is an example configuration file that documents all the options.
# It will need to be modified for your specific use case.
# Please refer to the link below for more details on how to set up the configuration file
# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

commands:
  # The commands defined below will IGNORE any commands used in command line and docker env variables.
  dry_run: false
  cross_seed: false
  recheck: false
  cat_update: false
  tag_update: true
  rem_unregistered: true
  tag_tracker_error: true
  rem_orphaned: true
  tag_nohardlinks: false
  skip_cleanup: false
  share_limits: true
  skip_qb_version_check: true

qbt:
  # qBittorrent parameters
  host: ####:8079
  user: ##
  pass: ##

settings:
  nohardlinks_tag: noHL
  force_auto_tmm: false  # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: issue  # Will set the tag of any torrents that do not have a working tracker.
  share_limits_suffix_tag: share_limit
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has at least one or more of the tags defined here. Otherwise torrents will not be tagged if tags exist.
  - noHL
  - issue
  - cross-seed

directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  # root_dir var: </your/path/here/>  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  # <OPTIONAL> remote_dir var: </your/path/here/>  # Path of docker host mapping of root_dir.
  # Must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # <OPTIONAL> torrents_dir var: </your/path/here/>  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin

  cross_seed:
  root_dir: /downloads
  remote_dir: /downloads/
  orphaned_dir: /downloads/orphaned_data
  #torrents_dir:
  #recycle_bin: 
  torrents_dir:
cat:
  # Category & Path Parameters
  # <Category Name> : <save_path>  # Path of your save directory.
  Movies: /downloads/completed/movies
  TV Show: /downloads/completed/tv
  Music: /downloads/completed/musics
  Anime: /downloads/completed/anime

cat_change:
  # This moves all the torrents from one category to another category. This executes on --cat-update
  # WARNING: if the paths are different and Default Torrent Management Mode is set to automatic the files could be moved !!!
  # <Old Category Name> : <New Category>
  #Radarr-HD.cross-seed: movies-hd
  #Radarr-UHD.cross-seed: movies-uhd
  #movies-hd.cross-seed: movies-hd
  #movies-uhd.cross-seed: movies-uhd


tracker:
  # Mandatory
  # Tag Parameters
  # <Tracker URL Keyword>:    # <MANDATORY> This is the keyword in the tracker url
  # <MANDATORY> Set tag name. Can be a list of tags or a single tag
  #   tag: <Tag Name>
  # <OPTIONAL> Will set the torrent Maximum share ratio until torrent is stopped from seeding/uploading. -2 means the global limit should be used, -1 means no limit.
  #   max_ratio: 5.0
  # <OPTIONAL> Will set the torrent Maximum seeding time (min) until torrent is stopped from seeding. -2 means the global limit should be used, -1 means no limit.
  #   max_seeding_time: 129600
  # <OPTIONAL> Will ensure that noHL torrents from this tracker are not deleted by cleanup variable if torrent has not yet met the minimum seeding time (min).
  #   min_seeding_time: 2000
  # <OPTIONAL> Will limit the upload speed KiB/s (KiloBytes/second) (-1 means no limit)
  #   limit_upload_speed: 150
  # <OPTIONAL> Set this to the notifiarr react name. This is used to add indexer reactions to the notifications sent by Notifiarr
  #   notifiarr: <notifiarr indexer>
  animebytes.tv:
    tag: AnimeBytes
   # notifiarr: animebytes
  avistaz:
    tag: avistaz
   # notifiarr: avistaz
  beyond-hd:
    tag: [Beyond-HD, tag2, tag3]
   # notifiarr: beyondhd
  blutopia:
    tag: Blutopia
  #  notifiarr: blutopia
  cartoonchaos:
    tag: CartoonChaos
  digitalcore:
    tag: DigitalCore
   # max_ratio: 5.0
  #  notifiarr: digitalcore
  empirehost:
    tag: iptorrents
  gazellegames:
    tag: GGn
    #limit_upload_speed: 150
  hdts:
    tag: HDTorrents
 #   max_seeding_time: 129600
  joinpeers:
    tag: yggtorrent
  landof.tv:
    tag: BroadcasTheNet
  #  notifiarr: broadcasthenet
  myanonamouse:
    tag: MaM
  nyaa:
    tag: nyaa
  passthepopcorn:
    tag: PassThePopcorn
   # notifiarr: passthepopcorn
  privatehd:
    tag: PrivateHD
   # notifiarr:
  stackoverflow:
    tag: iptorrents
  supertracker:
    tag: yggtorrent
  tleechreload:
    tag: TorrentLeech
  #  notifiarr: torrentleech
  torrentdb:
    tag: TorrentDB
   # notifiarr: torrentdb
  torrentleech:
    tag: TorrentLeech
   # notifiarr: torrentleech
  tv-vault:
    tag: TV-Vault
  # The "other" key is a special keyword and if defined will tag any other trackers that don't match the above trackers into this tag
  other:
    tag:
  routing.bgp.technology:
    tag: routing.bgp.technology

nohardlinks:
 # Tag Movies/Series that are not hard linked outside the root directory
  # Mandatory to fill out directory parameter above to use this function (root_dir/remote_dir)
  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
- Movies:
      # <OPTIONAL> exclude_tags var: Will exclude torrents with any of the following tags when searching through the category.
      #exclude_tags:
       # - Beyond-HD
        #- AnimeBytes
       # - MaM
  # Can have additional categories set with separate ratio/seeding times defined.
- TV Show:
      # <OPTIONAL> exclude_tags var: Will exclude torrents with any of the following tags when searching through the category.
      #exclude_tags:
       # - Beyond-HD
        #- BroadcasTheNet
- Anime:
- Music:

share_limits:
  group1:
    priority: 1
    include_any_tags:
    - iptorrents
    max_seeding_time: 21000
    cleanup: true
  group2:
    priority: 2
    include_any_tags:
    - TorrentLeech
    min_seeding_time: 20160
    cleanup: true
recyclebin:
  # Recycle Bin method of deletion will move files into the recycle bin (Located in /root_dir/.RecycleBin) instead of directly deleting them in qbit
  # By default the Recycle Bin will be emptied on every run of the qbit_manage script if empty_after_x_days is defined.
  enabled: false
  # <OPTIONAL> empty_after_x_days var:
  # Will automatically remove all files and folders in recycle bin after x days. (Checks every script run)
  # If this variable is not defined it, the RecycleBin will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 7
  # <OPTIONAL> save_torrents var:
  # If this option is set to true you MUST fill out the torrents_dir in the directory attribute.
  # This will save a copy of your .torrent and .fastresume file in the recycle bin before deleting it from qbittorrent
  save_torrents: false
  # <OPTIONAL> split_by_category var:
  # This will split the recycle bin folder by the save path defined in the `cat` attribute
  # and add the base folder name of the recycle bin that was defined in the `recycle_bin` sub-attribute under directory.
  split_by_category: false

orphaned:
  # Orphaned files are those in the root_dir download directory that are not referenced by any active torrents.
  # Will automatically remove all files and folders in orphaned data after x days. (Checks every script run)
  # If this variable is not defined it, the orphaned data will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 7
  # File patterns that will not be considered orphaned files. Handy for generated files that aren't part of the torrent but belong with the torrent's files
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'
  - '**/_unpackerred'
  - /downloads/extractfile
  - /downloads/extractfile2
  - /downloads/sortfile
  - /downloads/theme/*
  - /downloads/torrents/*
  - '**/unpackerr.log'
  - /downloads/incomplete/*

#apprise:
  # Apprise integration with webhooks
  # Leave Empty/Blank to disable
  # Mandatory to fill out the url of your apprise API endpoint
 # api_url: http://apprise-api:8000
  # Mandatory to fill out the notification url/urls based on the notification services provided by apprise. https://github.com/caronc/apprise/wiki
  #notify_url:

#notifiarr:
  # Notifiarr integration with webhooks
  # Leave Empty/Blank to disable
  # Mandatory to fill out API Key
 # apikey: ####################################
  # <OPTIONAL> Set to a unique value (could be your username on notifiarr for example)
  #instance:

webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    cleanup_dirs:
    share_limits:
  # Webhook notifications:
  # Possible values:
  # Set value to notifiarr if using notifiarr integration
  # Set value to apprise if using apprise integration
  # Set value to a valid webhook URL
  # Set value to nothing (leave Empty/Blank) to disable
 # error: https://mywebhookurl.com/qbt_manage
  #run_start: notifiarr
  #run_end: apprise
  #function:
   # cross_seed: https://mywebhookurl.com/qbt_manage
    #recheck: notifiarr
    #cat_update: apprise
    #tag_update: notifiarr
    #rem_unregistered: notifiarr
    #tag_tracker_error: notifiarr
    #rem_orphaned: notifiarr
    #tag_nohardlinks: notifiarr
    #cleanup_dirs: notifiarr

#bhd:
  # BHD Integration used for checking unregistered torrents
#  apikey:
```

### Logs

https://gist.github.com/nodiaque/e62be21aeb44c16117b585c534910582

### Screenshots

![image](https://github.com/StuffAnThings/qbit_manage/assets/324425/0ac6274c-414f-4c45-acb9-4a2a6f51bd20)

### Installation

Unraid

### Version Number

4.0.0

### What branch are you on?

master
