### ISSUE TITLE
[Bug]: Config Error: nohardlinks must be a list of categories

### ISSUE THREAD

**Issue by davralin** [StuffAnThings/qbit_manage#332]
### Describe the Bug

I am struggling with the config, and even after minimizing the config to the bare minimum - based on the migration guide - It's still telling me that nohardlinks must be a list of categories.

I don't use hardlinks, so the best for me would be to disable it entirely - but since I minimized the config so much, and it's still telling me something is wrong - I believe it to be a bug.

The same thing happens if I remove `nohardlinks:` completely.

### Config

```yaml
commands:
  dry_run: true
  tag_tracker_error: true
  tag_update: true
  recheck: true
  cross_seed: false
  cat_update: false
  rem_unregistered: true
  rem_orphaned: true
  skip_cleanup: false
  tag_nohardlinks: false
  skip_qb_version_check: true
  share_limits: false

qbt:
  host: qbittorrent.media.svc.cluster.local:8080
  user:
  pass:

settings:
  force_auto_tmm: true
  tracker_error_tag: issue
  ignoreTags_OnUpdate:
  - issue
  share_limits_suffix_tag: share_limit

directory:
  root_dir: /data/downloads
  remote_dir: /data/downloads/
  cross_seed:
  orphaned_dir: /data/downloads/orphaned_data
  torrents_dir:

cat:
- movies: "/data/downloads/movie"
- tv: "/data/downloads/tv"

nohardlinks:
- movies
- tv
```

### Logs

https://gist.github.com/davralin/3550e1877dcfb9dc60be4716afbe41cb

### Installation

Docker

### Version Number

4.0.0 (Docker)

### What branch are you on?

master

**Comment by bobokun** [comment]
I can't seem to replicate this, can you try moving onto the develop branch and see if you have the same issue? I've tried removing the entire `nohardlinks` section in my config and setting `tag_nohardlinks: false` with no errors. Can you also try setting your logs to debug by setting `QBT_DEBUG=True` in your docker env variable?

**Comment by davralin** [comment]
That ended with:
https://gist.github.com/davralin/287cb78b6410bbe14b04da6800b8f0b2

Which is weird, because I don't have something that should end with this: `--tag-nohardlinks (QBT_TAG_NOHARDLINKS): True` in the second section.

**Comment by davralin** [comment]
Still the same config
````
commands:
  dry_run: true
  tag_tracker_error: true
  tag_update: true
  recheck: true
  cross_seed: false
  cat_update: false
  rem_unregistered: true
  rem_orphaned: true
  skip_cleanup: false
  tag_nohardlinks: false
  skip_qb_version_check: true
  share_limits: false

qbt:
  host: qbittorrent.media.svc.cluster.local:8080
  user:
  pass:

settings:
  force_auto_tmm: true
  tracker_error_tag: issue
  ignoreTags_OnUpdate:
  - issue
  share_limits_suffix_tag: share_limit

directory:
  root_dir: /data/downloads
  remote_dir: /data/downloads/
  cross_seed:
  orphaned_dir: /data/downloads/orphaned_data
  torrents_dir:

cat:
- movies: "/data/downloads/movie"
- tv: "/data/downloads/tv"
 ````

Tried running both expand, and unexpand on the file - no difference.
