### ISSUE TITLE
[Docs]: Clarity on how exactly min_seed_time works.

### ISSUE THREAD

**Issue by luckycold** [StuffAnThings/qbit_manage#384]
### What is the improvement or update you wish to see?

More clarity on when `min_seed_time` is supposed to work. An example of it being used properly would be very helpful.

### Is there any context that might help us understand?

I'm unsure if this is a bug. But I'll assume that it's just me being boneheaded, and clarity in the docs may help people like me.

So, it's unclear to me how to make minimum seed time work with no Hard Links purging for specific trackers.

`min_seed_time` is not clear if it should be structured like:

```yaml
tracker:
  ssl.empirehost:
    tag:
    - ip
share_limits:
  noHL:
    include_any_tags:
    - noHL
    category:
    - sonarr
    - radarr
    cleanup: true
    priority: 999
  2WeeksMin:
    priority: 1
    include_any_tags:
    - ip
    min_seeding_time: 20200
    add_group_to_tag: true
    cleanup: true
```

or if it should be formatted like so:
```yaml
tracker:
  ssl.empirehost:
    tag:
    - ip
share_limits:
  noHL:
    include_any_tags:
    - noHL
    category:
    - sonarr
    - radarr
    max_seeding_time: 10
    cleanup: true
    priority: 999
  2WeeksMin:
    priority: 1
    include_any_tags:
    - ip
    min_seeding_time: 20200
    add_group_to_tag: true
    cleanup: true
```

The aim is so that any torrents with no Hard Links get deleted but any torrents that require a certain seeding time prevent the cleanup from happening.

### Does the docs page already exist? Please link to it.

https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup#share_limits

**Comment by bakerboy448** [comment]
Min seed time doesn't do anything by itself as it's not a goal.

not sure where the question / confusion is?

> Will prevent torrent deletion by cleanup variable if torrent has not yet met minimum seeding time (minutes). If the torrent has not yet reached this minimum seeding time, it will change the share limits back to no limits and resume the torrent to continue seeding.

only max ratio or max seed time stop a torrent.

min is a min time to be used with max ratio primarily

**Comment by luckycold** [comment]
I've already reviewed the config and wiki several times, @bakerboy448. I probably wasn't perfectly clear. The issue I've been having is that I'm trying to purge all hard links by default. Hence, the first part of what I originally want is something like this:

```yaml
share_limits:
  noHL:
    include_any_tags:
    - noHL
    max_seeding_time: 10
    cleanup: true
    priority: 999
```

I want this to be the default state of things for all torrents.

But I have some trackers that I need a minimum time on, hence the latter part of:

```yaml
  2WeeksMin:
    priority: 1
    include_any_tags:
    - ip
    min_seeding_time: 20200
    cleanup: true
```

I'm trying to have the `max_seeding_time` stop its cleanup by using `min_seeding_time`. I've been looking at my torrents and noticed that having it set up like this ends up having my torrents get deleted within the first 10 minutes, ignoring the `min_seeding_time`. 

I figured that I'm likely using it wrong, hence why I'm asking for clarification here and have the docs explain accordingly. I'm not sure if it's because I have the priority backwards (which I've already tried to varying degrees), if maybe it's supposed to cleanup anyway when the minimum time is reached, or if I'm missing anything else. But to repeat, my intention is to do the following:

1. Delete all torrents without hard links by default
2. Prevent this default from running if I need a certain tracker to have a certain amount of time seeding

And I want to know what I need to fix in my current config that prevents me from reaching that end goal, if my situation seems like it's likely coming from a small proportion of bone headed users, then I'll accept that. But I'd still like to know what I can change in my config that would allow me to do what I specified above, because I've been tweaking this for months without it ever working properly.

My current config (which doesn't work) is something like this:

```yaml

tracker:
  ssl.empirehost:
    tag:
    - ip
share_limits:
  noHL:
    include_any_tags:
    - noHL
    category:
    - sonarr
    - radarr
    max_seeding_time: 10
    cleanup: true
    priority: 999
  2WeeksMin:
    priority: 1
    include_any_tags:
    - ip
    min_seeding_time: 20200
    add_group_to_tag: true
    cleanup: true

```

**Comment by bakerboy448** [comment]
> purge all hard links by default.

Not sure why one would want to not permaseed all hardlinks; all assume that's a typo and you want to not seed non-hardkinks torrents

```
tracker:
  ssl.empirehost:
    tag:
    - ip
share_limits:
  noHL:
    include_any_tags:
    - noHL
    category:
    - sonarr
    - radarr
    max_seeding_time: 10
    cleanup: true
    priority: 999
  2WeeksMin:
    priority: 1
    include_any_tags:
    - ip
    min_seeding_time: 20200
    add_group_to_tag: true
    cleanup: true
```

QBm is doing exactly what you told it to do. Remove all noHL torrents after they have seeded for 10 minutes.

> deleted within the first 10 minutes, ignoring the min_seeding_time.

it is not ignoring anything. You have not set any minimum for that share limit group.

share limits are not trackers, a torrent only meets a single share limit as clearly noted in the docs and config example.
