### ISSUE TITLE
[Bug]: QBM crashes when it can't find files in the recyclebin that it just deleted.

### ISSUE THREAD

**Issue by Quafley** [StuffAnThings/qbit_manage#388]
### Describe the Bug

The bug happens when QBM gets to the `Emptying Recycle Bin`. From what I can see from the DEBUG logs, it removes a file and then crashes because it can't find the file. I've not found the reason, nor can I run qbmwithout it infinitely looping. 

### Config

```yaml
# This is an example configuration file that documents all the options.
# It will need to be modified for your specific use case.
# Please refer to the link below for more details on how to set up the configuration file
# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

commands:
  share_limits: true
  cross_seed: false
  recheck: true
  cat_update: true
  tag_update: true
  rem_unregistered: true
  tag_tracker_error: true
  rem_orphaned: true
  tag_nohardlinks: true
  skip_cleanup: false
  skip_qb_version_check: true
  dry_run: false
qbt:
  # qBittorrent parameters
  host: qbittorrent:8080
  user: 
  pass: 
settings:
  force_auto_tmm: true
  tracker_error_tag: issue
  nohardlinks_tag: noHL
  share_limits_tag: ~share_limit
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has one or more of the tags defined here.
  - noHL
  - issue
  - cross-seed
directory:
  cross_seed: /data/torrents/cross-seed
  root_dir: /data/torrents/
  recycle_bin: /data/torrents/.RecycleBin
  torrents_dir: /qbittorrent/data/BT_backup/
  remote_dir: /data/torrents/
  orphaned_dir: /data/torrents/orphaned_data
cat:
  movies_c: /data/torrents/movies
  movies: /data/torrent/movies
  c4k-movies: /data/torrents/4k-movies
  c4k-series: /data/torrents/4k-series
  sonarr_c: /data/torrents/sonarr/
  sonarr: /data/torrents/sonarr
  race-tv: /data/torrents/race-tv
  race-movies: /data/torrents/race-movies
  music: /data/torrents/music/
  games: /data/torrents/games
cat_change:
  4k-movies.cross-seed: c4k-movies.cross-seed
  movies.cross-seed: movies_c.cross-seed
  4k-series.cross-seed: c4k-series.cross-seed
  sonarr.cross-seed: sonarr_c.cross-seed
tracker:
MY TRACKERS
nohardlinks:
  # Tag Movies/Series that are not hard linked
  # Mandatory to fill out directory parameter above to use this function (root_dir/remote_dir)
  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
- movies_c
- c4k-movies
- c4k-series
- sonarr_c

share_limits:
  # naming: {tracker / group} {type: all, tv, movie} {NoHL or HL}

MY SHARE LIMITS

recyclebin:
  enabled: true
  empty_after_x_days: 1
  save_torrents: true
  split_by_category: true
orphaned:
  # Orphaned files are those in the root_dir download directory that are not referenced by any active torrents.
  # File patterns that will not be considered orphaned files. Handy for generated files that aren't part of the torrent but belong with the torrent's files
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'
  - '**/_unpackerred'
  empty_after_x_days: 14
notifiarr:
  # Notifiarr integration with webhooks
  # Leave Empty/Blank to disable
  # Mandatory to fill out API Key
  apikey: 
  # <OPTIONAL> Set to a unique value (could be your username on notifiarr for example)
  instance:

webhooks:
  # Webhook notifications:
  # Possible values:
  # Set value to notifiarr if using notifiarr integration
  # Set value to apprise if using apprise integration
  # Set value to a valid webhook URL
  # Leave Empty/Blank to disable
  error: 
    
  run_start: notifiarr
  run_end: apprise
  function:
    cross_seed: 
      
    recheck: notifiarr
    cat_update: apprise
    tag_update: notifiarr
    rem_unregistered: notifiarr
    tag_tracker_error: notifiarr
    rem_orphaned: notifiarr
    tag_nohardlinks: notifiarr
    empty_recyclebin: notifiarr

    share_limits: notifiarr
bhd:
  apikey:
```

### Logs

https://gist.github.com/Quafley/449201fdd62fe58a6be2ee96bbcc7f3f

### Installation

Unraid

### Version Number

4.0.3

### What branch are you on?

master
