### ISSUE TITLE
[Bug]: Cleanup not deleting content, only torrents

### ISSUE THREAD

**Issue by jsaltzman** [StuffAnThings/qbit_manage#416]
### Describe the Bug

I am trying to use the share limits function to delete torrents in a certain category that have met a certain seed time. I have my parameters setup correctly, and when I --run the script, it detects files that meet the parameters. Cleanup is set to true. When it goes to cleanup the torrent, however, it says "Deleted .torrent but NOT content files." The torrent is not cross-seeded. I believe this is a bug. Someone on the discord had the same issue about a month ago.

### Config

```yaml
autobrr:
    priority: 2
    categories:
    - autobrr
    - autobrr.cross-seed
    max_seeding_time: 4500
    min_seeding_time: 4400
    resume_torrent_after_change: true
    add_group_to_tag: true
    cleanup: true
```

My folders are mapped as followed
```cross_seed: /data/torrents/torrents
  root_dir: /data/torrents
  remote_dir: /mnt/user/data/torrents/
  recycle_bin: /data/torrents/.RecycleBin
  torrents_dir: /qbittorrent/data/BT_backup
  orphaned_dir: /data/torrents/orphaned_data
```
If I cd to /data/torrents within the container, I see all my files so I am confident I have this mapped correctly.

My volume mounts in docker are as follows (I use unraid, but showing a portainer screenshot):
<img width="1484" alt="image" src="https://github.com/StuffAnThings/qbit_manage/assets/2000982/3209c0d2-65dd-4c63-9591-32806ddfa9f4">

### Logs

https://gist.github.com/jsaltzman/9cb91643ed7c5fd0274bb5bb6a554c9d

### Installation

Unraid

### Version Number

4.0.4

### What branch are you on?

master
