### ISSUE TITLE
[Bug]: Last_Active reading wrong time

### ISSUE THREAD

**Issue by GinSoakedBoy** [StuffAnThings/qbit_manage#426]
### Describe the Bug

The new 'last_active' flag is showing different values for last active time on a torrent. 

`[2023-10-19 14:58:00,991] [_has_reached_last_active_time_limit:464] [INFO]     |         Min inactive time not met: 2:23:54 <= 2 days, 0:00:00. Removing Share Limits so qBittorrent can continue seeding.`

The torrent this was for has is over a week under 'Last Activity' in qBittorrent.

This is what I have under 'share_limits' in the config.

```
priority: 2
    categories:
    - games
    exclude_any_tags:
    - MaM,OPS,uploaded
    max_ratio: -1
    min_seeding_time: 10080
    max_seeding_time: 10080
    last_active: 2880
    cleanup: true
    resume_torrent_after_change: true
    add_group_to_tag: true
```

### Logs

https://gist.github.com

### Installation

Docker

### Version Number

4.0.5

### What branch are you on?

master
