### ISSUE TITLE
[Bug]: ETA infinity shown for some torrents

### ISSUE THREAD

**Issue by pentago** [StuffAnThings/qbit_manage#447]
### Describe the Bug

Even though torrents are tagged with tracker name and have `max_seeding_time` defined for the tracker, ETA is shown as an infinity symbol instead of how much time there's left for seeding.

![image](https://github.com/StuffAnThings/qbit_manage/assets/876756/b7b56500-1e3e-4135-8b7f-5f558f34cb63)

Most torrents get tagged and handled properly (deletion upon reaching max_seeding_time) but some aren't and I'd like to know the reason so I don't need to do this manually if possible.

Thanks in advance!

### Config

```yaml
# This is an example configuration file that documents all the options.
# It will need to be modified for your specific use case.
# Please refer to the link below for more details on how to set up the configuration file
# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

commands:
  # The commands defined below will IGNORE any commands used in command line and docker env variables.
  dry_run: false
  cross_seed: false
  recheck: false
  cat_update: true
  tag_update: true
  rem_unregistered: true
  tag_tracker_error: true
  rem_orphaned: false
  tag_nohardlinks: true
  share_limits: true
  skip_qb_version_check: false
  skip_cleanup: true

qbt:
  # qBittorrent parameters
  host: [redacted]
  user: [redacted]
  pass: [redacted]

settings:
  force_auto_tmm: false # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: issue # Will set the tag of any torrents that do not have a working tracker.
  nohardlinks_tag: noHL # Will set the tag of any torrents with no hardlinks.
  share_limits_tag: ~share_limit # Will add this tag when applying share limits to provide an easy way to filter torrents by share limit group/priority for each torrent
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has at least one or more of the tags defined here. Otherwise torrents will not be tagged if tags exist.
  - noHL
  - issue
  - cross-seed
  - freeleech
  - custom
  - learning

directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  # root_dir var: </your/path/here/>  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  # <OPTIONAL> remote_dir var: </your/path/here/>  # Path of docker host mapping of root_dir.
  # Must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # <OPTIONAL> torrents_dir var: </your/path/here/>  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin
  # <OPTIONAL> orphaned_dir var: </your/path/here/>  # Path of the the Orphaned Data folder. This is similar to RecycleBin, but only for orphaned data.
  cross_seed: ''
  root_dir: /home/[redacted]/downloads/qbittorrent
  remote_dir: /home/[redacted]/downloads/qbittorrent
  recycle_bin: /home/[redacted]/downloads/qbittorrent/.RecycleBin
  torrents_dir: /home/[redacted]/.local/share/qBittorrent/BT_backup
  orphaned_dir: /home/[redacted]/downloads/qbittorrent/orphaned_data

cat:
  # Category & Path Parameters
  # <Category Name> : <save_path>  # Path of your save directory.
  movies: /home/[redacted]/downloads/qbittorrent/movies
  tv: /home/[redacted]/downloads/qbittorrent/tv
  music: /home/[redacted]/downloads/qbittorrent/music
  books: /home/[redacted]/downloads/qbittorrent/books
  mma: /home/[redacted]/media/UFC
  learning: /home/[redacted]/media/Learning
  freeleech: /home/[redacted]/downloads/qbittorrent/freeleech
  custom: /home/[redacted]/downloads/qbittorrent/custom

cat_change:
  # This moves all the torrents from one category to another category. This executes on --cat-update
  # WARNING: if the paths are different and Default Torrent Management Mode is set to automatic the files could be moved !!!
  # <Old Category Name> : <New Category>
  # Radarr-HD.cross-seed: movies-hd
  # Radarr-UHD.cross-seed: movies-uhd
  # movies-hd.cross-seed: movies-hd
  # movies-uhd.cross-seed: movies-uhd
  tv.cross-seed: tv
  movies.cross-seed: movies
  freeleech.cross-seed: freeleech
  music.cross-seed: music
  custom.cross-seed: custom
  books.cross-seed: books

tracker:
  # Mandatory
  # Tag Parameters
  # <Tracker URL Keyword>:    # <MANDATORY> This is the keyword in the tracker url. You can define multiple tracker urls by splitting with `|` delimiter
  # <MANDATORY> Set tag name. Can be a list of tags or a single tag
  #   tag: <Tag Name>
  # <OPTIONAL> Set this to the notifiarr react name. This is used to add indexer reactions to the notifications sent by Notifiarr
  #   notifiarr: <notifiarr indexer>
  digitalcore:
    tag: DCC
  hdts:
    tag: HDT
  privatehd:
    tag: PHD
  torrentleech:
    tag: TL
  tleechreload:
    tag: TL
  immortalseed:
    tag: IS
  hd-space:
    tag: HDS
  iptorrents:
    tag: IPT
  routing.bgp.technology:
    tag: IPT
  empirehost:
    tag: IPT
  stackoverflow:
    tag: IPT
  mma-torrents:
    tag: MMA
  torrentseeds:
    tag: TS
  myanonamouse:
    tag: MAM
  filelist:
    tag: FL
  flro:
    tag: FL
  blu:
    tag: BLU
  beyond-hd:
    tag: BHD
  blutopia:
    tag: BT
  landof.tv:
    tag: BTN
  passthepopcorn:
    tag: PTP
  # The "other" key is a special keyword and if defined will tag any other trackers that don't match the above trackers into this tag
  other:
    tag: other

nohardlinks:
  # Tag Movies/Series that are not hard linked outside the root directory
  # Mandatory to fill out directory parameter above to use this function (root_dir/remote_dir)
  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
- movie:
      # <OPTIONAL> exclude_tags var: Will exclude torrents with any of the following tags when searching through the category.
    exclude_tags:
    - xxx
    - yyy
  # Can have additional categories set with separate ratio/seeding times defined.
- tv:
      # <OPTIONAL> exclude_tags var: Will exclude torrents with any of the following tags when searching through the category.
    exclude_tags:
    - xxx
    - yyy
- music:
      # <OPTIONAL> exclude_tags var: Will exclude torrents with any of the following tags when searching through the category.
    exclude_tags:
    - xxx
    - yyy
- mma:
      # <OPTIONAL> exclude_tags var: Will exclude torrents with any of the following tags when searching through the category.
    exclude_tags:
    - xxx
    - yyy

share_limits:
  # Control how torrent share limits are set depending on the priority of your grouping
  # Each torrent will be matched with the share limit group with the highest priority that meets the group filter criteria.
  # Each torrent can only be matched with one share limit group
  # This variable is mandatory and is a text defining the name of your grouping. This can be any string you want
  noHL:
    # <MANDATORY> priority: <int/float> # This is the priority of your grouping. The lower the number the higher the priority
    priority: 1
    # <OPTIONAL> include_all_tags: <list> # Filter the group based on one or more tags. Multiple include_all_tags are checked with an AND condition
    # All tags defined here must be present in the torrent for it to be included in this group
    include_all_tags:
    - noHL
    # <OPTIONAL> include_any_tags: <list> # Filter the group based on one or more tags. Multiple include_any_tags are checked with an OR condition
    # Any tags defined here must be present in the torrent for it to be included in this group
    include_any_tags:
    - noHL
    # <OPTIONAL> exclude_all_tags: <list> # Filter by excluding one or more tags. Multiple exclude_all_tags are checked with an AND condition
    # This is useful to combine with the category filter to exclude one or more tags from an entire category
    # All tags defined here must be present in the torrent for it to be excluded in this group
    exclude_all_tags:
    - xxx
    # <OPTIONAL> exclude_any_tags: <list> # Filter by excluding one or more tags. Multiple exclude_any_tags are checked with an OR condition
    # This is useful to combine with the category filter to exclude one or more tags from an entire category
    # Any tags defined here must be present in the torrent for it to be excluded in this group
    exclude_any_tags:
    - xxx
    # <OPTIONAL> categories: <list> # Filter by including one or more categories. Multiple categories are checked with an OR condition
    # Since one torrent can only be associated with a single category, multiple categories are checked with an OR condition
    categories:
    # - movies
    # - tv
    # - music
    # - mma
    # <OPTIONAL> max_ratio <float>: Will set the torrent Maximum share ratio until torrent is stopped from seeding/uploading.
    # Will default to -1 (no limit) if not specified for the group.
    # max_ratio: 5.0
    # <OPTIONAL> max_seeding_time <int>: Will set the torrent Maximum seeding time (minutes) until torrent is stopped from seeding.
    # Will default to -1 (no limit) if not specified for the group.
    # max_seeding_time: 129600
    # <OPTIONAL> min_seeding_time <int>: Will prevent torrent deletion by cleanup variable if torrent has not yet minimum seeding time (minutes).
    # If the torrent has not yet reached this minimum seeding time, it will change the share limits back to no limits and resume the torrent to continue seeding.
    # Will default to 0 if not specified for the group.
    # min_seeding_time: 43200
    # <OPTIONAL> Limit Upload Speed <int>: Will limit the upload speed KiB/s (KiloBytes/second) (`-1` : No Limit)
    limit_upload_speed: 0
    # <OPTIONAL> cleanup <bool>: WARNING!! Setting this as true Will remove and delete contents of any torrents that satisfies the share limits
    cleanup: true
    # <OPTIONAL> resume_torrent_after_change <bool>: This variable will resume your torrent after changing share limits. Default is true
    resume_torrent_after_change: true
    # <OPTIONAL> add_group_to_tag <bool>: This adds your grouping as a tag with a prefix defined in settings . Default is true
    # Example: A grouping defined as noHL will have a tag set to ~share_limit.noHL (if using the default prefix)
    add_group_to_tag: false
    # <OPTIONAL> min_num_seeds <int>: This will prevent torrent deletion by cleanup variable if the number of seeds is less than the value set here.
    # If the torrent has less number of seeds than the min_num_seeds, the share limits will be changed back to no limits and resume the torrent to continue seeding.
    # Will default to 0 if not specified for the group.
    min_num_seeds: 0
  cross-seed:
    priority: 2
    include_all_tags:
    - cross-seed
    max_seeding_time: 2880 # 2d
    add_group_to_tag: false
    cleanup: true
  DCC:
    include_all_tags:
    - DCC
    max_seeding_time: 8640 # 6d
    add_group_to_tag: false
    priority: 10
    cleanup: true
  HDT:
    include_all_tags:
    - HDT
    max_seeding_time: 8640 # 6d
    add_group_to_tag: false
    priority: 11
    cleanup: true
  PHD:
    include_all_tags:
    - PHD
    max_seeding_time: 15840 # 11d
    add_group_to_tag: false
    priority: 12
    cleanup: true
  TL:
    include_all_tags:
    - TL
    max_seeding_time: 11520 # 8d
    add_group_to_tag: false
    priority: 13
    cleanup: true
  IS:
    include_all_tags:
    - IS
    max_seeding_time: 2880 # 2d
    add_group_to_tag: false
    priority: 14
    cleanup: true
  HDS:
    include_all_tags:
    - HDS
    max_seeding_time: 4320 # 3d
    add_group_to_tag: false
    priority: 15
    cleanup: true
  IPT:
    include_all_tags:
    - IPT
    max_seeding_time: 21600 # 15d
    add_group_to_tag: false
    priority: 16
    cleanup: true
  MMA:
    include_all_tags:
    - MMA
    max_seeding_time: 4320 # 3d
    add_group_to_tag: false
    priority: 17
    cleanup: false
  TS:
    include_all_tags:
    - TS
    max_seeding_time: 8640 # 6d
    add_group_to_tag: false
    priority: 18
    cleanup: true
  MAM:
    include_all_tags:
    - MAM
    max_seeding_time: 4350 # 3d
    add_group_to_tag: false
    priority: 19
    cleanup: true
  FL:
    include_all_tags:
    - FL
    max_seeding_time: 10100 # 7d
    add_group_to_tag: false
    priority: 20
    cleanup: true
  default:
    priority: 1000
    max_ratio: -1
    add_group_to_tag: false
    max_seeding_time: -1
    cleanup: true

recyclebin:
  # Recycle Bin method of deletion will move files into the recycle bin (Located in /root_dir/.RecycleBin) instead of directly deleting them in qbit
  # By default the Recycle Bin will be emptied on every run of the qbit_manage script if empty_after_x_days is defined.
  enabled: true
  # <OPTIONAL> empty_after_x_days var:
  # Will automatically remove all files and folders in recycle bin after x days. (Checks every script run)
  # If this variable is not defined it, the RecycleBin will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 0
  # <OPTIONAL> save_torrents var:
  # If this option is set to true you MUST fill out the torrents_dir in the directory attribute.
  # This will save a copy of your .torrent and .fastresume file in the recycle bin before deleting it from qbittorrent
  save_torrents: true
  # <OPTIONAL> split_by_category var:
  # This will split the recycle bin folder by the save path defined in the `cat` attribute
  # and add the base folder name of the recycle bin that was defined in the `recycle_bin` sub-attribute under directory.
  split_by_category: true

orphaned:
  # Orphaned files are those in the root_dir download directory that are not referenced by any active torrents.
  # Will automatically remove all files and folders in orphaned data after x days. (Checks every script run)
  # If this variable is not defined it, the orphaned data will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 0
  # File patterns that will not be considered orphaned files. Handy for generated files that aren't part of the torrent but belong with the torrent's files
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - '**/*.!qB'
  - '**/*_unpackerred'
  - '**/cross-seed-torrents/*'
  - '**/cross-seed-links/*'

# apprise:
#   # Apprise integration with webhooks
#   # Leave Empty/Blank to disable
#   # Mandatory to fill out the url of your apprise API endpoint
#   api_url:
#   # Mandatory to fill out the notification url/urls based on the notification services provided by apprise. https://github.com/caronc/apprise/wiki
#   notify_url:

notifiarr:
  # Notifiarr integration with webhooks
  # Leave Empty/Blank to disable
  # Mandatory to fill out API Key
  apikey: [redacted]
  # <OPTIONAL> Set to a unique value (could be your username on notifiarr for example)
  instance: [redacted]

webhooks:
  # Webhook notifications:
  # Possible values:
  # Set value to notifiarr if using notifiarr integration
  # Set value to apprise if using apprise integration
  # Set value to a valid webhook URL
  # Set value to nothing (leave Empty/Blank) to disable
  error: notifiarr
  run_start:
  run_end:
  function:
    cross_seed:
    recheck: notifiarr
    cat_update: notifiarr
    tag_update: notifiarr
    rem_unregistered: notifiarr
    tag_tracker_error: notifiarr
    rem_orphaned: notifiarr
    tag_nohardlinks: notifiarr
    cleanup_dirs: notifiarr
    share_limits: notifiarr

# bhd:
#   # BHD Integration used for checking unregistered torrents
#   apikey:
```

### Logs

https://gist.githubusercontent.com/pentago/dd8f72ef96998e37dfcb83ddc6a2c3c8/raw/5233e318b5449831a9b858e0870292e3f6846866/gistfile1.txt

### Installation

Local

### Version Number

4.0.6

### What branch are you on?

master
