### ISSUE TITLE
Mapping issue - not finding torrent folder

### ISSUE THREAD

**Issue by sardinemaster** [StuffAnThings/qbit_manage#45]
Hello!
I'm either not mapping the root_dir correctly, or something is wrong.
I just ran another dry-run and I get this:
> Did not move 4602 Orphaned files to /data/torrents/orphaned_data

This makes no sense, since I have about that amount of torrents in qBittorrent. I believe that the script is currently thinking that all my torrents are orphaned.

These are currently my configurations:

_Qbit_manage_ container mapping: `/mnt/user/data/torrents/:/data/torrents/`
_Qbit_manage config.yml_
```
directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/> #Output directory of cross-seed
  # root_dir var: </your/path/here/> #Root downloads directory used to check for orphaned files and used in RecycleBin
  # <OPTIONAL> remote_dir var: </your/path/here/> # Path of docker host mapping of root_dir. Must be set if you are using docker!
  # cross_seed: "/mnt/user/data/torrents/torrent_files/output"
  root_dir: "/data/torrents/"
  # remote_dir: "/mnt/user/data/torrents/"
```
NOTE: The `cross_seed` variable is commented out because I have set my cross_seed container to "inject".

```
cat:
  # <Category Name> : <save_path> #Path of your save directory. Can be a keyword or full path
  4k-movies-completed: "/data/torrents/4k-movies-completed"
  movies-completed: "/data/torrents/movies-completed"
  4k-tv-completed: "/data/torrents/4k-tv-completed"
  tv-completed: "/data/torrents/tv-completed"
  books-completed: "/data/torrents/books-completed"
  random-completed: "/data/torrents/random-completed"
  sports: "/data/torrents/sports"
  4k-movies: "/data/torrents/4k-movies"
  movies: "/data/torrents/movies"
  4k-tv: "/data/torrents/4k-tv"
  tv: "/data/torrents/tv"
  books: "/data/torrents/books"
  random: "/data/torrents/random"
```

_Qbittorrent_ container mapping:  `/mnt/user/data/torrents/:/data/torrents/`
_Qbittorrent_ default download path `/data/torrents/`
Each category is mapped as follows: /data/torrents/4k-movies        (4k-movies is changed to whatever is relevant)
