### ISSUE TITLE
[Bug]: Share limit tags do not update

### ISSUE THREAD

**Issue by akesher123** [StuffAnThings/qbit_manage#457]
### Describe the Bug

On unraid, if you don't stop qbit_manage from running during move, it will at some point tag torrents as no HL and put them in the associated share limits group and tag them as such. This is not an issue for my setup, since even no HL cross-seeds have a min seeding time longer than between mover runs, however it has caused me to notice that the tags for share limits are not updating.

For example, this image is just after a fresh run:

![image](https://github.com/StuffAnThings/qbit_manage/assets/110856441/cafe7116-4b17-41bc-bdb4-c9de05f0e371)

You can see there are only 27 true no HL torrents, however the group `cross-seed-noHL`  (requires all tags: noHL and cross-seed) is larger with 60. I have two additional no HL share limit tags with 106 and 18 torrents. It seems evident these tags are not getting updated.

If I remove the share limit tag from the torrent, it appears it is never retagged with the share limit (I only verified by dry run and didn't see it).

I thought this might be an issue with ignoreTags_onUpdate (I'm not really clear on what this actually does), but upon removing all tags from that config it repopulated them right away, so I suppose that's unrelated.

### Config

```yaml
# This is an example configuration file that documents all the options.
# It will need to be modified for your specific use case.
# Please refer to the link below for more details on how to set up the configuration file
# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

commands:
  # The commands defined below will IGNORE any commands used in command line and docker env variables.
  dry_run: false
  cross_seed: false
  recheck: false
  cat_update: false
  tag_update: true
  rem_unregistered: false
  tag_tracker_error: true
  rem_orphaned: true
  tag_nohardlinks: true
  skip_cleanup: false
  share_limits: true
  skip_qb_version_check: false

qbt:
  # qBittorrent parameters
  host: #
  user: #
  pass: #

settings:
  force_auto_tmm: false  # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: issue  # Will set the tag of any torrents that do not have a working tracker.
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has one or more of the tags defined here.
  - noHL
  - issue
  - cross-seed
  nohardlinks_tag: noHL
  share_limits_tag: ~share_limit

directory:
  root_dir: /data/torrents/
  torrents_dir: /qbittorrent/data/BT_backup
  orphaned_dir: /data/torrents/orphaned_data
  cross_seed:
  remote_dir: /data/torrents/

cat:
  # Category & Path Parameters
  # <Category Name> : <save_path>  # Path of your save directory.
  radarr-complete: /data/torrents/movies
  radarr-complete.cross-seed: /data/torrents/movies
  cross-seed-data.cross-seed: /data/torrents/cross_seed_links
  cross-seed-data: /data/torrents/cross_seed_links
  tv-sonarr-complete: /data/torrents/tv
  tv-sonarr-complete.cross-seed: /data/torrents/tv
  tv-sonarr.cross-seed: /data/torrents/tv
  radarr: /data/torrents/movies
  tv-sonarr: /data/torrents/tv

  music: /data/torrents/music/
cat_change:

tracker:
  www.hawke.uno:
    tag: HUNO
  aither.cc:
    tag: AIT
...
  nyaa.tracker.wf:
    tag: NYA

nohardlinks:
  # Tag Movies/Series that are not hard linked
  # Mandatory to fill out directory parameter above to use this function (root_dir/remote_dir)
  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
- radarr-complete
- radarr-complete.cross-seed
- tv-sonarr-complete
- tv-sonarr.cross-seed
- tv-sonarr-complete.cross-seed
- cross-seed-data.cross-seed
- cross-seed-data

share_limits:
  cross-seed-noHL:
    priority: 1
    include_all_tags:
    - noHL
    - cross-seed
    max_ratio: 0
    max_seeding_time: 0
    min_seeding_time: 2880
    limit_upload_speed: 128
    cleanup: true
    add_group_to_tag: true

  short-seedtime:
    priority: 2
    include_any_tags:
    - NYA
    max_ratio: 0
    min_seeding_time: 1440
    limit_upload_speed: 128
    cleanup: true
    add_group_to_tag: true

  unlimited-noHL:
    priority: 3
    include_any_tags:
    - BHD
      ...
    include_all_tags:
    - noHL
    exclude_any_tags:
    - RED
    - MAM
    max_ratio: 0
    min_seeding_time: 10080
    cleanup: true
    add_group_to_tag: true

  unlimited:
    priority: 4
    include_any_tags:
    - BHD
      ...
    max_ratio: -1
    max_seeding_time: -1
    limit_upload_speed: -1
    cleanup: false
    add_group_to_tag: true

  limited-noHL:
    priority: 5
    include_all_tags:
    - noHL
    max_ratio: 0
    min_seeding_time: 10080
    limit_upload_speed: 128
    cleanup: true
    add_group_to_tag: true

  limited:
    priority: 6
    categories:
    max_ratio: -1
    max_seeding_time: -1
    limit_upload_speed: 256
    cleanup: false
    add_group_to_tag: true



recyclebin:
  # Recycle Bin method of deletion will move files into the recycle bin (Located in /root_dir/.RecycleBin) instead of directly deleting them in qbit
  # By default the Recycle Bin will be emptied on every run of the qbit_manage script if empty_after_x_days is defined.
  enabled: false
  # <OPTIONAL> empty_after_x_days var:
  # Will automatically remove all files and folders in recycle bin after x days. (Checks every script run)
  # If this variable is not defined it, the RecycleBin will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 60
  # <OPTIONAL> save_torrents var:
  # If this option is set to true you MUST fill out the torrents_dir in the directory attribute.
  # This will save a copy of your .torrent and .fastresume file in the recycle bin before deleting it from qbittorrent
  save_torrents: true
  # <OPTIONAL> split_by_category var:
  # This will split the recycle bin folder by the save path defined in the `cat` attribute
  # and add the base folder name of the recycle bin that was defined in the `recycle_bin` sub-attribute under directory.
  split_by_category: false

orphaned:
  # Orphaned files are those in the root_dir download directory that are not referenced by any active torrents.
  # Will automatically remove all files and folders in orphaned data after x days. (Checks every script run)
  # If this variable is not defined it, the orphaned data will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 0
  # File patterns that will not be considered orphaned files. Handy for generated files that aren't part of the torrent but belong with the torrent's files
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'
  - '**/music/**'

webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    cleanup_dirs:
    share_limits:
```

### Logs

https://gist.github.com/akesher123/d7f00b29745f1457da0c82b1a46ba484

### Installation

Unraid

### Version Number

4.0.6

### What branch are you on?

master
