### ISSUE TITLE
[FR]: Size check for share limits

### ISSUE THREAD

**Issue by NLZ** [StuffAnThings/qbit_manage#472]
### Is your feature request related to a problem? Please elaborate.

Some trackers have different seeding time requirements based on the size of the torrents, like AR says 72h under 48GB and 168h above.

### Describe the solution you'd like

Would be nice if I could set the share limits accomodate this, maybe like this:
```yaml
  AR-large:
    priority: 10
    include_all_tags: [AR]
    include_bigger_than: 48 # GB
    max_ratio: 1.0
    max_seeding_time: 10080 # 7 days
  AR-small:
    priority: 11
    include_all_tags: [AR]
    max_ratio: 1.0
    max_seeding_time: 4320 # 3 days
```
Not sure what would be the best config name for it, `min_torrent_size` could also work.
Or maybe defining max size instead of min on the other share limit group.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

As of now I just have to use the highest requirement to be sure.

### Who will this benefit?

Everyone who are on trackers that have size dependent seeding requirements and want to minimize seeding time.
