### ISSUE TITLE
[Bug]: Qbit_manage deleting Recycle bin root directory

### ISSUE THREAD

**Issue by someguy3013** [StuffAnThings/qbit_manage#479]
### Describe the Bug

Qbit_manage has recently started deleting the root directory for the recycle bin. This seems to only occur if the files it is cleaning up are the last remaining in the directory. 

I am not sure when this change in behavior started, but it was within the last month or so. 

### Config

```yaml
# This is an example configuration file that documents all the options.
# It will need to be modified for your specific use case.
# Please refer to the link below for more details on how to set up the configuration file
# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

commands:
  # The commands defined below will IGNORE any commands used in command line and docker env variables.
  dry_run: false
  cross_seed: false
  recheck: false
  cat_update: false
  tag_update: true
  rem_unregistered: true
  tag_tracker_error: true
  rem_orphaned: true
  tag_nohardlinks: true
  skip_cleanup: false
  share_limits: true
  skip_qb_version_check: false
  startup_delay: 30

qbt:
  # qBittorrent parameters
  host: $host
  user: $user
  pass: $password

settings:
  force_auto_tmm: false  # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: issue  # Will set the tag of any torrents that do not have a working tracker.
  ignoreTags_OnUpdate: # When running tag-update function, it will update torrent tags for a given torrent even if the torrent has one or more of the tags defined here.
  - noHL
  - issue
  - cross-seed
  nohardlinks_tag: noHL
  share_limits_tag: ~share_limit
directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  # root_dir var: </your/path/here/>  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  # <OPTIONAL> remote_dir var: </your/path/here/>  # Path of docker host mapping of root_dir.
  # Must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # <OPTIONAL> torrents_dir var: </your/path/here/>  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin

  #cross_seed: "/your/path/here/"
  root_dir: /Downloads
  recycle_bin: /Downloads/Recycle
  torrents_dir: /torrents
  orphaned_dir: /Downloads/Orphaned
  remote_dir: /Downloads/
  cross_seed:
cat:
  # Category & Path Parameters
  # <Category Name> : <save_path>  # Path of your save directory.
  #XSeedRadarr: /Downloads/radarr
  #XSeedSonarr: /Downloads/tv-sonarr
  radar.cross-seed: /Downloads/radarr
  tv-sonarr.cross-seed: /Downloads/tv-sonarr
  radarr: /Downloads/radarr
  tv-sonarr: /Downloads/tv-sonarr


  Downloads: /Downloads/
cat_change:
  # This moves all the torrents from one category to another category. This executes on --cat-update
  # WARNING: if the paths are different and Default Torrent Management Mode is set to automatic the files could be moved !!!
  # <Old Category Name> : <New Category>
  radarr.cross-seed: XSeedRadarr
  tv-sonarr.cross-seed: XSeedSonarr


tracker:
  # Tag Parameters
  # <Tracker URL Keyword>:    # <MANDATORY> This is the keyword in the tracker url
  # <MANDATORY> Set tag name. Can be a list of tags or a single tag
  #   tag: <Tag Name>
  aither.cc:
    tag: aither
  ssl.empirehost.me:
    tag: ipt
  privatehd:
    tag: privatehd
  torrentleech|tleechreload:
    tag: tleech

  localhost.stackoverflow.tech:
    tag: localhost.stackoverflow.tech
  routing.bgp.technology:
    tag: routing.bgp.technology
nohardlinks:
  # Tag Movies/Series that are not hard linked
  # Mandatory to fill out directory parameter above to use this function (root_dir/remote_dir)
  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
- tv-sonarr
- radarr
- tv-sonarr.cross-seed
- radarr.cross-seed


share_limits:
  noHL:
    priority: 1
    include_all_tags:
    - noHL
    categories:
    - tv-sonarr
    - radarr
    - tv-sonarr.cross-seed
    - radarr.cross-seed
    min_seeding_time: 30240
    max_seeding_time: 43200
    cleanup: true

recyclebin:
  # Recycle Bin method of deletion will move files into the recycle bin (Located in /root_dir/.RecycleBin) instead of directly deleting them in qbit
  # By default the Recycle Bin will be emptied on every run of the qbit_manage script if empty_after_x_days is defined.
  enabled: true
  # <OPTIONAL> empty_after_x_days var:
  # Will automatically remove all files and folders in recycle bin after x days. (Checks every script run)
  # If this variable is not defined it, the RecycleBin will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 3
  # <OPTIONAL> save_torrents var:
  # If this option is set to true you MUST fill out the torrents_dir in the directory attribute.
  # This will save a copy of your .torrent and .fastresume file in the recycle bin before deleting it from qbittorrent
  save_torrents: true
  # <OPTIONAL> split_by_category var:
  # This will split the recycle bin folder by the save path defined in the `cat` attribute
  # and add the base folder name of the recycle bin that was defined in the `recycle_bin` sub-attribute under directory.
  split_by_category: false
orphaned:
  # Orphaned files are those in the root_dir download directory that are not referenced by any active torrents.
  # Will automatically remove all files and folders in orphaned data after x days. (Checks every script run)
  # If this variable is not defined it, the orphaned data will never be emptied.
  # WARNING: Setting this variable to 0 will delete all files immediately upon script run!
  empty_after_x_days: 7
  # File patterns that will not be considered orphaned files. Handy for generated files that aren't part of the torrent but belong with the torrent's files
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - '**/*.!qB'
  - /Downloads/#recycle
  - /Downloads/#snapshot
  - /Downloads/cross-seed
  - /Downloads/torrent-blackhole
  - /Downloads/@eaDir
  #Tried adding Recycle to see if it prevents the recycle bin from being deleted, while allowing it to work properly. Recycle bin is still deleted with the last files in the directory. 
  - /Downloads/Recycle


# apprise:
#   # Apprise integration with webhooks
#   # Leave Empty/Blank to disable
#   # Mandatory to fill out the url of your apprise API endpoint
#   api_url:
#   # Mandatory to fill out the notification url/urls based on the notification services provided by apprise. https://github.com/caronc/apprise/wiki
#   notify_url:

# notifiarr:
#   # Notifiarr integration with webhooks
#   # Leave Empty/Blank to disable
#   # Mandatory to fill out API Key
#   apikey: apikey
#   # <OPTIONAL> Set to a unique value (could be your username on notifiarr for example)
#   instance:

# webhooks:
#   # Webhook notifications:
#   # Possible values:
#   # Set value to notifiarr if using notifiarr integration
#   # Set value to apprise if using apprise integration
#   # Set value to a valid webhook URL
#   # Leave Empty/Blank to disable
#   error: notifiarr
#   run_start: notifiarr
#   run_end: notifiarr
#   function:
#     cross_seed:
#     recheck: notifiarr
#     cat_update: notifiarr
#     tag_update: notifiarr
#     rem_unregistered: notifiarr
#     tag_tracker_error: notifiarr
#     rem_orphaned: notifiarr
#     tag_nohardlinks: notifiarr
#     cleanup_dirs: notifiarr

webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    share_limits:
    cleanup_dirs:
```

### Logs

https://gist.github.com/someguy3013/b9c77ede205be8cfc347f55ef55ad08a

### Installation

Docker

### Version Number

4.0.8

### What branch are you on?

master
