### ISSUE TITLE
Unexpected tag value using Format 2

### ISSUE THREAD

**Issue by mousecloak** [StuffAnThings/qbit_manage#49]
I'm using the latest `develop` Docker image. My `tags` config is as follows:
```yaml
tags:
  flacsfor.me:
    tag: Redacted
  localhost.stackoverflow.tech:
    tag: IPTorrents    
    max_ratio: 5.0
    max_seeding_time: 30240
  routing.bgp.technology:
    tag: IPTorrents
    max_ratio: 5.0
    max_seeding_time: 30240
  ru.org:
    tag: RuTracker
  ssl.empirehost.me:
    tag: IPTorrents
    max_ratio: 5.0
    max_seeding_time: 30240
```

For some reason I think the app is parsing this config as if it were tags Format 1. I see this in the logs:
```
|    Torrent Name: a_torrent                                                                         |
|         New Tag: {'tag': 'IPTorrents', 'max_ratio': 5.0, 'max_seeding_time': 30240}                |
|         Tracker: https://localhost.stackoverflow.tech                                              |
```

Sure enough, the torrent in qBittorrent is tagged with `tag`, `max_ratio`, `max_seeding_time`, and `noHL`.
