### ISSUE TITLE
[Bug]: Unable to run on `4.0.10-beta.1`

### ISSUE THREAD

**Issue by foux** [StuffAnThings/qbit_manage#510]
### Describe the Bug

When running on the `nightly`hotio branch (version `4.0.10-beta1), I run into the error in the logs

### Config

```yaml
commands:
  dry_run: false
  cross_seed: false
  recheck: false
  cat_update: true
  tag_update: true
  rem_unregistered: true
  tag_tracker_error: true
  rem_orphaned: true
  tag_nohardlinks: true
  share_limits: true
  skip_qb_version_check: false
  skip_cleanup: false
qbt:
  host: https://my.qbit.fqdn:443
  user: user
  pass: pass
settings:
  force_auto_tmm: true
  tracker_error_tag: issue
  nohardlinks_tag: noHL
  share_limits_tag: ~share_limit
  ignoreTags_OnUpdate:
  - noHL
  - issue
  - cross-seed
  cross_seed_tag: cross-seed
  cat_filter_completed: true
  share_limits_filter_completed: true
  tag_nohardlinks_filter_completed: true
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
directory:
  cross_seed: /datas/medias/Downloads/torrents/cross-seed/
  root_dir: /datas/medias/Downloads/torrents/completed/
  remote_dir: /datas/medias/Downloads/torrents/completed/
  recycle_bin: /datas/medias/Downloads/torrents/completed/.RecycleBin
  torrents_dir:
  orphaned_dir: /datas/medias/Downloads/torrents/completed/orphaned_data
cat:
  lidarr: /datas/medias/Downloads/torrents/completed/Lidarr/
  lidarr-imported: /datas/medias/Downloads/torrents/completed/lidarr-imported
  prowlarr: /datas/medias/Downloads/torrents/completed/Prowlarr/
  radarr: /datas/medias/Downloads/torrents/completed/Radarr/
  radarr-imported: /datas/medias/Downloads/torrents/completed/radarr-imported
  sonarr: /datas/medias/Downloads/torrents/completed/Sonarr/
  sonarr-imported: /datas/medias/Downloads/torrents/completed/sonarr-imported
  completed: /datas/medias/Downloads/torrents/completed/
tracker:
  tracker1:
    tag: tracker1
  tracker2:
    tag: tracker2
  tracker3:
    tag: tracker3
  tracker4:
    tag: tracker4
    max_ratio: 1
nohardlinks:
  # Mandatory to fill out directory parameter above to use this function (root_dir/remote_dir)
  # This variable should be set to your category name of your completed movies/completed series in qbit. Acceptable variable can be any category you would like to tag if there are no hardlinks found
  lidarr-imported:
    exclude_tags:
    - tracker4
  radarr-imported:
    exclude_tags:
    - tracker4
  sonarr-imported:
    exclude_tags:
    - tracker4
  prowlarr:
    exclude_tags:
    - tracker4
share_limits:
  noHL:
    priority: 1
    include_all_tags:
    - noHL
    max_seeding_time: 28800
    min_seeding_time: 20160
    cleanup: true
    min_num_seeds: 1
    resume_torrent_after_change: true
    add_group_to_tag: true
  longSeeds:
    priority: 2
    include_any_tags:
    - tracker1
    - tracker2
    - tracker3
    cleanup: true
    max_ratio: 20
    min_seeding_time: 30240
    max_seeding_time: -1
    min_num_seeds: 5
    last_active: 10080
    resume_torrent_after_change: true
recyclebin:
  enabled: false
  empty_after_x_days: 60
  save_torrents: false
  split_by_category: false
orphaned:
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - '**/*.!qB'
  - '**/.donttouch'
  - '**/*_unpackerred/*'

# Apprise integration with webhooks
# Leave Empty/Blank to disable
# apprise:
  # Mandatory to fill out the url of your apprise API endpoint
  # api_url: http://apprise-api:8000
  # notify_url:
  empty_after_x_days:
notifiarr:
  # Mandatory to fill out API Key
  apikey: my-api-key
webhooks:
  error: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  function:
    cross_seed: notifiarr
    recheck: notifiarr
    cat_update: notifiarr
    tag_update: notifiarr
    rem_unregistered: notifiarr
    rem_orphaned: notifiarr
    tag_nohardlinks: notifiarr
    empty_recyclebin: notifiarr
    tag_tracker_error: notifiarr
    share_limits: notifiarr
```

### Logs

https://gist.github.com/foux/8f207555703b42c53fb703ba85740edb

### Installation

Docker

### Version Number

4.0.10-beta1

### What branch are you on?

develop
