### ISSUE TITLE
[Bug]: time duration format does not work as expected

### ISSUE THREAD

**Issue by sgtsquiggs** [StuffAnThings/qbit_manage#543]
### Describe the Bug

```Config Error: share_limits->cross-seed sub-attribute min_seeding_time must an integer >= 0```

### Config

```yaml
share_limits:
  cross-seed:
    priority: 2
    include_all_tags:
    - cross-seed
    min_seeding_time: 12w
    cleanup: false
```

### Logs

https://gist.github.com/sgtsquiggs/53a806993ed25df158a796cf915162a7

### Installation

Docker

### Version Number

4.1.2

### What branch are you on?

master
