### ISSUE TITLE
[Bug]: Multiple share limit tags applied

### ISSUE THREAD

**Issue by ineednewpajamas** [StuffAnThings/qbit_manage#546]
### Describe the Bug

Since 4.1.3 (at least I didn't notice it before), some torrents are getting tagged with multiple share_limit tags. For example both "~share_limit_2.noHL" and "~share_limit_999.default". I don't have concrete proof but my guess is that it's torrents that have switched between either having or not having hard links since I updated to 4.1.3.

Example to find in the logs `The.Daily.Show.2024.05.07.Lexi.Freiman.1080p.WEB.h264-EDITH[EZTVx.to].mkv[eztvx.to]`.

### Config

```yaml
commands:
  dry_run: false
  cross_seed: false
  recheck: false
  cat_update: false
  tag_update: true
  rem_unregistered: false
  tag_tracker_error: false
  rem_orphaned: false
  tag_nohardlinks: true
  share_limits: true
  skip_qb_version_check: false
  skip_cleanup: false

qbt:
  host: qbittorrent:8080
  user:
  pass:

settings:
  force_auto_tmm: false
  tracker_error_tag: issue
  nohardlinks_tag: noHL
  share_limits_tag: ~share_limit
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
  cross_seed_tag: cross-seed
  cat_filter_completed: true
  share_limits_filter_completed: true
  tag_nohardlinks_filter_completed: true
  
directory:
  cross_seed:
  root_dir: /data/torrents/
  remote_dir: /data/torrents/
  recycle_bin: /data/torrents/.RecycleBin
  torrents_dir: /qbittorrent/data/BT_backup
  orphaned_dir: /data/torrents/orphaned_data

cat:
  movies: /data/torrents/movies
  tv: /data/torrents/tv
  audiobooks: /data/torrents/audiobooks
  books: /data/torrents/books
  manual: /data/torrents/manual
  music: /data/torrents/music
  prowlarr: /data/torrents/prowlarr

cat_change:

tracker:
  myanonamouse:
    tag: MaM
  other:
    tag: other

nohardlinks:
  # books: # Calibre doesn't hard link
  #   exclude_tags:
  #     - MaM
  audiobooks:
    exclude_tags:
      - MaM
  movies:
  tv:
  manual:
  music:
  prowlarr:

share_limits:
  MaM:
    priority: 1
    include_all_tags:
      - MaM
    max_ratio: -1
    max_seeding_time: -1
    cleanup: false
  noHL:
    priority: 2
    include_all_tags:
      - noHL
    max_ratio: 1
    max_seeding_time: -1
    min_num_seeds: 5
    cleanup: false
  default:
    priority: 999
    max_ratio: 2
    max_seeding_time: -1
    min_num_seeds: 10
    cleanup: false

recyclebin:
  enabled: true
  empty_after_x_days: 60
  save_torrents: true
  split_by_category: true

orphaned:
  empty_after_x_days: 60
  exclude_patterns:

webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    share_limits:
    cleanup_dirs:
```

### Logs

https://gist.github.com/ineednewpajamas/d70a3cc3bd22eb31baa5828183b8ce83

### Screenshots

<img width="455" alt="Screen Shot 2024-05-08 at 8 22 38 PM" src="https://github.com/StuffAnThings/qbit_manage/assets/73252768/455206ba-0766-4061-a0a5-fc484fdba7d2">

### Installation

Docker

### Version Number

4.1.3

### What branch are you on?

master
