### ISSUE TITLE
[Bug]: Categorize only with the first letter

### ISSUE THREAD

**Issue by imTHAI** [StuffAnThings/qbit_manage#560]
### Describe the Bug

Hello,
I use this app since a long time without any problem. But today I discovered that it changes the category only with the first letter of the category name.

I've reseted the category of one torrent and restarted the container. In the logs:
```
====== Updating Categories ========|
|    Torrent Name: Hazel-5.3.2 U2B P.dmg                                                     |
|    New Category: i                                                                                           |
|         Tracker: https://tracker.iexample.app                                                    |
| Updated 1 new categories.                                                                            |
|= Tagging Torrents with Tracker Errors and Removing Unregistered Torrents =|
| No unregistered torrents found.    
```

Rmq: I obviously replaced the name of the tracker with "example" even if you probably recognized the real one. 
Rmq2: I gave one example but it does the same with all trackers.

Consequently, if several names of trackers start with the same letter, they are mixed. For example I have several trackers that start with T, so they are all categorized under this letter.

I'm running  your 'develop' branch since many months (since it was mandatory to get the compatibility when developers released the last major version of qbt) without any problem. Although, to be sure it isn't related to the 'develop' branch, I came back to the 'latest' one but it doesn't solve the problem.
Also, I didn't touch the configuration since many months, it was working like a charm.

Thks for your help,

### Config

```yaml
commands:
# The commands defined below will IGNORE any commands used in command line and docker env variables.
  cross_seed: false
  recheck: true
  cat_update: true
  tag_update: false
  rem_unregistered: true
  tag_tracker_error: true
  tag_nohardlinks: false
  skip_cleanup: false
  skip_qb_version_check: false
  share_limits: true
  rem_orphaned: false
  dry_run: false
qbt:
  # qBittorrent parameters
  host: x.x.x.x
  user:
  pass:

settings:
  force_auto_tmm: true
  tracker_error_tag: issue
  nohardlinks_tag: noHL

  share_limits_tag: ~share_limit
  ignoreTags_OnUpdate:
  - noHL
  - issue
  - cross-seed
  cross_seed_tag: cross-seed
  cat_filter_completed: true
  share_limits_filter_completed: true
  tag_nohardlinks_filter_completed: true
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
  force_retag_all: false
directory:
  root_dir: /downloads
  remote_dir: /downloads/
  cross_seed:
  #orphaned_dir: /downloads/orphaned_data
  torrents_dir: /downloads/torrent_files
  recycle_bin: /downloads/.RecycleBin

cat:
  iExample: /downloads/IEXAMPLE


tracker:
  iexample.app:
    tag: private
    cat: iExample
```

### Logs

https://gist.github.com/imTHAI/711280319792922438a483fb43b3953b

### Installation

Unraid

### Version Number

4.1.5

### What branch are you on?

master
