### ISSUE TITLE
[Bug]: Recyclebin filename can be too long for the filesystem

### ISSUE THREAD

**Issue by m-wynn** [StuffAnThings/qbit_manage#604]
### Describe the Bug

I'm on btrfs which, like many linux filesystems, has a max filename length of 255 bytes.  When trying to save torrents with long names to the recyclebin, it often fails [opening the file](https://github.com/StuffAnThings/qbit_manage/blob/4e08f62aafe9f43314a9e50aec99339786270610/modules/util.py#L662-L666) with "Filename too long"

### Config

```yaml
recyclebin:
  enabled: true
  empty_after_x_days: 60
  save_torrents: true
  split_by_category: false
```

### Logs

https://gist.github.com/m-wynn/1cd66a98564f9f54fc083b676461a7dc

### Installation

Docker

### Version Number

4.1.7

### What branch are you on?

master
