### ISSUE TITLE
[Bug] - Blank Notification config should not cause errors

### ISSUE THREAD

**Issue by bakerboy448** [StuffAnThings/qbit_manage#62]
```yml
#Apprise integration with webhooks
apprise:
  #Mandatory to fill out the url of your apprise API endpoint
  api_url: http://apprise-api:8000
  #Mandatory to fill out the notification url/urls based on the notification services provided by apprise. https://github.com/caronc/apprise/wiki
  notify_url:

#Notifiarr integration with webhooks
notifiarr:
  #Mandatory to fill out API Key
  apikey: ####################################
  #<OPTIONAL> Set to a unique value (could be your username on notifiarr for example)
  instance:

# Webhook notifications: 
# Possible values: 
# Set value to notifiarr if using notifiarr integration
# Set value to apprise if using apprise integration
# Set value to a valid webhook URL
webhooks:
  error: https://mywebhookurl.com/qbt_manage
  run_start: notifiarr
  run_end: apprise
  function:
    cross_seed: https://mywebhookurl.com/qbt_manage
    recheck: notifiarr
    cat_update: apprise
    tag_update: notifiarr
    rem_unregistered: notifiarr
    rem_orphaned: notifiarr
    tag_nohardlinks: notifiarr
    empty_recyclebin: notifiarr
```

leaving any of the above attributes blank should not cause errors

blank should mean disabled
