### ISSUE TITLE
[Bug]: Removing newly empty directories bypasses exclude patterns

### ISSUE THREAD

**Issue by washedszn** [StuffAnThings/qbit_manage#624]
### Describe the Bug

Exclude pattern will not prevent `rem_orphaned` from deleting empty directories within a directory that `rem_orphaned` is run on. Kinda difficult explaining so I'll use an example:

A user has the following directory:
```/data/torrents/tv/links```

They want to ignore the following folder inside links:
```/data/torrents/tv/links/cross-seed```

So they add the exclude pattern:
```/data/torrents/*/links/cross-seed/**```

This successfully prevents qbitmanage from deleting any files inside ```/data/torrents/*/links/cross-seed/```. However, if that directory is empty and `rem_orphaned` removes a file inside `/data/torrents/*/links/`, then the functionality of removing newly empty directories will delete the cross-seed folder - despite it being excluded.

I'd say this is pretty much the result of a bad user setup, although I still think this is a bug. Also, to confirm this I created an isolated environment to test with - just to make it faster creating/deleting files etc. Let me know if you want that to reproduce the bug.

### Logs

N/A

### Installation

Docker

### Version Number

4.1.7

### What branch are you on?

master

**Comment by appiekap653** [comment]
To add onto this issue, I also noticed a related strange bug.
I used the removed orphans function and at the end, it was trying to delete the root folder.

My folder setup on the Host:
```
├── media/data/downloads/
│   ├── watch/
│   └── torrents/
│       ├── .RecycleBin/
│       ├── cross_seeds_files/
│       ├── orphaned_data/
│       ├── private/
│       │   ├── games/
│       │   ├── movies/
│       │   ├── music/
│       │   ├── prowlarr/
│       │   └── series/
│       └── public/
│           ├── games/
│           ├── movies/
│           ├── music/
│           ├── prowlarr/
│           └── series/
```

Docker mappings of qBittorrent and qBit_Manage:
```
  qbitmanage:
    volumes:
      - $DOCKERDIR/data/qbitmanage:/config:rw
      - $DOCKERDIR/data/qbittorrent/data/BT_backup:/qbittorrent/data/BT_backup:ro
      - /media/data/downloads:/data/downloads:rw
  qbittorrent:
    volumes:
      - $DOCKERDIR/data/qbittorrent:/config:rw
      - /media/data/downloads:/data/downloads:rw
```

Root_dir config in qBit_Manage:
```
directory:
  cross_seed: /data/downloads/torrents/cross_seeds_files
  root_dir: /data/downloads/
  remote_dir: /data/downloads/
  recycle_bin: /data/downloads/torrents/.RecycleBin
  torrents_dir: /qbittorrent/data/BT_backup
  orphaned_dir: /data/downloads/torrents/orphaned_data
```

Log from qBit_Manage:
```
[2024-10-09 21:28:13,573] [rem_orphaned:82]           [INFO]     | Deleting 1362 Orphaned files                                                                       |
[2024-10-09 21:29:07,597] [rem_orphaned:105]          [INFO]     | Removing newly empty directories                                                                   |
[2024-10-09 21:29:08,390] [remove_empty_directories:506] [WARNING]  | [Errno 13] Permission denied: '/data/downloads' : Unable to delete folder /data/downloads as it has permission issues. Skipping... |
[2024-10-09 21:29:08,391] [remove_empty_directories:517] [WARNING]  | [Errno 13] Permission denied: '/data/downloads' :  Unable to delete folder /data/downloads as it has permission issues. Skipping... |
[2024-10-09 21:29:08,391] [finished_run:468]          [INFO]     |     Scheduled Mode: Running every 30 minutes.              
```

After the run, it had deleted all directories except the ones that still had torrent files in them, but that also included deleting the `.RecycleBin` folder, the `cross_seeds_files` folder and some `category` folders (when currently not have torrents).
And afterwards it was even trying to delete the whole `root_dir` folder according to the log.

Do I have something wrong with this configuration of directories?

Why would qBit_Manage delete it's own `.RecycleBin` folder and `cross_seeds_files` folder? (shouldn't it automatically exclude all the folders that are stated in the `directory` section of the config file).

And trying to delete the whole `root_dir` folder should never even be considered Wright?
