### ISSUE TITLE
[Bug?]: Tagging torrents for cleanup after the criteria is met doesn't delete the files.

### ISSUE THREAD

**Issue by daviddanko** [StuffAnThings/qbit_manage#625]
### Describe the Bug

Tagging a torrent with a criteria for cleanup which is already met (for example max_seeding_time=1m, ratio=0.01,... ) doesn't remove the files from the disk, only the .torrent from the client. 

So when I start downloading something and I plan to delete it after let's say it reaches ratio 2.0, but I have the scheduler run only every 24 hour, if I already reached a ratio 2+, and THEN scheduler tags it with that rule, the torrent is deleted, however the file stays on the disk. 

Not sure if that's intended though. 

### Config

```yaml
# This is an example configuration file that documents all the options.
# It will need to be modified for your specific use case.
# Please refer to the link below for more details on how to set up the configuration file
# https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup

commands:
  # The commands defined below will IGNORE any commands used in command line and docker env variables.
  dry_run: false
  cross_seed: false
  recheck: false
  cat_update: false
  tag_update: true
  rem_unregistered: true
  tag_tracker_error: false
  rem_orphaned: false
  tag_nohardlinks: false
  share_limits: true
  skip_qb_version_check: false
  skip_cleanup: false

qbt:
  # qBittorrent parameters
  host: 
  user:
  pass:

settings:
  force_auto_tmm: false # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: issue # Will set the tag of any torrents that do not have a working tracker.
  nohardlinks_tag: noHL # Will set the tag of any torrents with no hardlinks.
  share_limits_tag: seed_limit # Will add this tag when applying share limits to provide an easy way to filter torrents by share limit group/priority for each torrent
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached # Tag to be added to torrents that have not yet reached the minimum seeding time
  share_limits_min_num_seeds_tag: MinSeedsNotMet # Tag to be added to torrents that have not yet reached the minimum number of seeds
  share_limits_last_active_tag: LastActiveLimitNotReached # Tag to be added to torrents that have not yet reached the last active limit
  cross_seed_tag: cross-seed # Will set the tag of any torrents that are added by cross-seed command
  cat_filter_completed: false # Filters for completed torrents only when running cat_update command
  share_limits_filter_completed: false # Filters for completed torrents only when running share_limits command
  tag_nohardlinks_filter_completed: true # Filters for completed torrents only when running tag_nohardlinks command
  cat_update_all: true # Checks and udpates all torrent categories if set to True when running cat_update command, otherwise only update torrents that are uncategorized

directory:
  root_dir: /media/downloads/
  cross_seed:
  recycle_bin: '' #/media/downloads/.RecycleBin
  torrents_dir: '' #/config/qbittorrent/qBittorrent/BT_backup
  orphaned_dir: '' #/media/downloads/orphaned_data
  remote_dir: ''

cat:
  movie-radarr: /media/movies/
  show-sonarr: /media/shows/

cat_change:

tracker:
  ncore:
    tag: nCore
  other:
    tag: other

nohardlinks:

share_limits:
  nCore:
    priority: 1
    include_any_tags:
    - nCore
    max_seeding_time: 30d
    cleanup: true
  default:
    priority: 2
    max_seeding_time: 30d
    max_ratio: 2
    cleanup: true

recyclebin:
  enabled: false
  empty_after_x_days:
  save_torrents: false
  split_by_category: false

orphaned:
  empty_after_x_days: 10
  exclude_patterns:

apprise:

notifiarr:

webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    share_limits:
    cleanup_dirs:
```

### Logs

https://gist.github.com/daviddanko/44093e58e9bcef8ef65e830d4ba92a54

### Installation

Docker

### Version Number

4.1.7

### What branch are you on?

master
