### ISSUE TITLE
[FR]: Use multiple config files in 1 instance

### ISSUE THREAD

**Issue by Minituff** [StuffAnThings/qbit_manage#629]
### Is your feature request related to a problem? Please elaborate.

No problem. Requesting an extension of features

### Describe the solution you'd like

I have been looking through the Wiki and this may be possible already, but I would love an example to get me started.

I see this in the [commands](https://github.com/StuffAnThings/qbit_manage/wiki/Config-Setup#commands) section of the wiki

> Useful if you want to run qbm with multiple configurations files that execute different commands for each qbt instance.

I would love the ability to tell QBM to run on a schedule and look at 2 different `config.yml` files -- or have the ability to have the same `config.yml` manage 2 different Qbittorrent instances. 

### Does your solution involve any of the following?

- [ ] New config option
- [X] New command option

### Describe alternatives you've considered

I could run 2 completely separate instances of QBM. This would work, but will use more resources.

### Who will this benefit?

Anyone with multiple qbit instances.

### Additional Information

I am using the Docker instance.
This may be possible already. If so, I would love an example added to the Wiki :)

**Comment by bobokun** [comment]
I think we can probably improve the wiki to include an example but

Ex) config1.yml and config2.yml

For the env variable you put config*.yml and it'll read both of those configs. Hope that helps

**Comment by Minituff** [comment]
Thank you @bobokun, I can confirm this does work.

Here's a little more of my config if anyone else comes across this.
```yml
services:
  qbit_manage:
    image: ghcr.io/stuffanthings/qbit_manage:latest
    volumes:
      - /opt/docker_volumes/qbit_manage:/config:rw
    volumes:
      - /opt/docker_volumes/qbit_manage:/config:rw
    environment:
      - QBT_CONFIG=config*.yml
```

 `/opt/docker_volumes/qbit_manage` directory:
```
config1.yml
config2.yml
```

I can see both YML's getting processed by the logs.
