### ISSUE TITLE
[Bug]: Everything getting marked as `orphan`

### ISSUE THREAD

**Issue by Minituff** [StuffAnThings/qbit_manage#631]
## Description
Every time Qbitmanage runs it marks all Torrents as orphans and moves them to the orphaned directory.

My guess is that there is some mismatch with the `/qbittorrent/` directory -- as it thinks there are no torrents actually there to match with files on in /data/torrents` folder.

Any help would be appreciated.

### Docker Setup
```yaml

version: "3.7"
services:
  qbit_manage:
    image: ghcr.io/stuffanthings/qbit_manage:latest
    container_name: qbit_manage
    hostname: qbit_manage
    volumes:
      - /opt/docker_volumes/qbit_manage:/config:rw
      - /mnt/nfs/torrents:/data/torrents:rw
      # This is the directory where the Qbit docker container also saves to
      - /opt/docker_volumes/qbittorrent/qBittorrent/BT_backup:/qbittorrent/:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - QBT_SCHEDULE=60 # Schedule to run every x minutes or choose customize schedule via cron. (Default set to 1440 (1 day))
      - QBT_LOG_LEVEL=INFO
      - QBT_CONFIG=config*.yml # Will pickup any file matching this pattern
    restart: on-failure:2
```

### Config `config.yml`

```yaml
# Remove other parts of config for brevity
directory:
  #* Do not remove these. They must be defined even if not used
  # root_dir var: </your/path/here/>  
  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  root_dir: /data/torrents/

  # <OPTIONAL> remote_dir var: </your/path/here/>  
  # Path of docker host mapping of root_dir.
  # remote_dir must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # remote_dir should not be set if qbit_manage is running in a container
  # not required if running qbit_manage in a container
  # remote_dir: /data/torrents # /mnt/user/data/torrents/ 

  # <OPTIONAL> recycle_bin var: </your/path/here/>   
  # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  recycle_bin: /data/torrents/.RecycleBin # /mnt/user/data/torrents/.RecycleBin

  # <OPTIONAL> torrents_dir var: </your/path/here/>  
  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin

  # Docker mount - /opt/docker_volumes/qbittorrent/qBittorrent/BT_backup:/qbittorrent/:ro
  torrents_dir: /qbittorrent #/qbittorrent/data/BT_backup

  # <OPTIONAL> orphaned_dir var: </your/path/here/>  
  # Path of the the Orphaned Data folder. This is similar to RecycleBin, but only for orphaned data.
  orphaned_dir: /data/torrents/orphaned_data

  # Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  cross_seed: /data/torrents/cross_seed_unused
```

### Troubleshooting
This is some logs exec into the qbm container. I can see the torrents there, so I dont know why it's not matching.

```console
qbit_manage:/qbittorrent# pwd
/qbittorrent
qbit_manage:/qbittorrent# ls -la
total 108
drwxr-xr-x 2 1000 1000 28672 Aug  5 16:09 .
drwxr-xr-x 1 root root  4096 Aug  5 04:01 ..
-rw-r--r-- 1 1000 1000  1971 Aug  5 16:07 86f0d587e36ecd0061b5ab885c97c35f3d524fc4.fastresume
-rw-r--r-- 1 1000 1000  4472 Aug  5 16:09 caa385c23ba160de57a3e4051f4b4990cc9887c4.fastresume
-rw-r--r-- 1 1000 1000 57095 Aug  5 16:06 caa385c23ba160de57a3e4051f4b4990cc9887c4.torrent
-rwxr-xr-x 1 1000 1000    82 Aug  5 16:06 queue
qbit_manage:/qbittorrent# 
```

### Logs

https://gist.github.com/Minituff/d78f15ae2c58b462d56cae3fed6f310d

### Screenshots

4.1.7

### Installation

Docker

### Version Number

4.1.7

### What branch are you on?

master
