### ISSUE TITLE
[Bug]: Optional directories are not really optional

### ISSUE THREAD

**Issue by Minituff** [StuffAnThings/qbit_manage#632]
### Describe the Bug

I am looking though the config template and I see the following `directory` values are optional:
- remote_dir
- recycle_bin
- torrents_dir
- orphaned_dir
- cross_seed

However, if I comment them out, QBM will automatically fill in a default value for them. I'm fine with this action, but I'm a little confused why they are labeled optional. 

The [Docker instructions](https://github.com/StuffAnThings/qbit_manage/wiki/Docker-Installation) also specifically mention this: 

> remote_dir: is not required and can be commented out with #

### Config

This config shows my values all populated.
```yaml
directory:
  #* Do not remove these. They must be defined even if not used
  # root_dir var: </your/path/here/>  
  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  root_dir: /data/torrents

  # <OPTIONAL> remote_dir var: </your/path/here/>  
  # Path of docker host mapping of root_dir.
  # remote_dir must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # remote_dir should not be set if qbit_manage is running in a container
  # Not required if running qbit_manage in a container
  remote_dir: /data/torrents # /mnt/user/data/torrents/

  # <OPTIONAL> recycle_bin var: </your/path/here/>   
  # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  recycle_bin: /data/torrents/.RecycleBin # /mnt/user/data/torrents/.RecycleBin

  # <OPTIONAL> torrents_dir var: </your/path/here/>  
  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin
  # Docker mount - /opt/docker_volumes/qbittorrent/qBittorrent/BT_backup:/qbittorrent/:ro
  torrents_dir: /qbittorrent #/qbittorrent/data/BT_backup

  # <OPTIONAL> orphaned_dir var: </your/path/here/>  
  # Path of the the Orphaned Data folder. This is similar to RecycleBin, but only for orphaned data.
  orphaned_dir: /data/torrents/orphaned_data

  # <OPTIONAL> Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  # cross_seed: /data/torrents/cross_seed_unused
```
This config all the optional values commented out.

```yaml
directory:
  #* Do not remove these. They must be defined even if not used
  # root_dir var: </your/path/here/>  
  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  root_dir: /data/torrents

  # <OPTIONAL> remote_dir var: </your/path/here/>  
  # Path of docker host mapping of root_dir.
  # remote_dir must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # remote_dir should not be set if qbit_manage is running in a container
  # Not required if running qbit_manage in a container
  # remote_dir: /data/torrents # /mnt/user/data/torrents/

  # <OPTIONAL> recycle_bin var: </your/path/here/>   
  # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # recycle_bin: /data/torrents/.RecycleBin # /mnt/user/data/torrents/.RecycleBin

  # <OPTIONAL> torrents_dir var: </your/path/here/>  
  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin
  # Docker mount - /opt/docker_volumes/qbittorrent/qBittorrent/BT_backup:/qbittorrent/:ro
  # torrents_dir: /qbittorrent #/qbittorrent/data/BT_backup

  # <OPTIONAL> orphaned_dir var: </your/path/here/>  
  # Path of the the Orphaned Data folder. This is similar to RecycleBin, but only for orphaned data.
  # orphaned_dir: /data/torrents/orphaned_data

  # <OPTIONAL> Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  # cross_seed: /data/torrents/cross_seed_unused
```

### Logs
```text
| Locating config... 
| Using /config/config-local.yml as config 
| Commands found in config-local.yml, ignoring env variables and using config commands instead
| Config Warning: directory sub-attribute remote_dir not found
| directory sub-attribute remote_dir added to config
| Config Warning: directory sub-attribute remote_dir not found, using /data/torrents/ as defaul
| Config Warning: directory sub-attribute cross_seed not found
| directory sub-attribute cross_seed added to config
| Connecting to Qbittorrent...
| Qbt Connection Successful
```

### Installation

Docker

### Version Number

4.1.7 

### What branch are you on?

master
