### ISSUE TITLE
[Bug]: recycle_bin directory setting not being respected (regression? v4.1.9)

### ISSUE THREAD

**Issue by SawkeeReemo** [StuffAnThings/qbit_manage#651]
### Describe the Bug

The recycle_bin directory setting in config seems to be getting ignored on this latest update [v4.1.9]

My directory structure:
```
video \
      downloads \
      orphaned \
      recycle \
               downloads \
               torrents \
               torrents_json \
```

qbm config:
`root_dir: /video`
`recycle_bin: /video/recycle`
`orphaned_dir: /video/orphaned`

The volume is mount the same in both the qbit and qbm containers: `${DOWNLOADS}:/video`

The orphaned files setting still works as expected.  But for recycles I'm noticing that qbm is creating a new directory `/video/downloads/recycle`[etc] instead of using the directory I've told it to. This used to work fine until couple days ago with this new release, but now it's suddenly putting things in this new folder. Did something change there? Regression?

### Config

```yaml
directory:
  cross_seed: /cross-seed
  root_dir: /video
  remote_dir: /video
  recycle_bin: /video/recycle
  torrents_dir: /qbtmisc_config/qBittorrent/BT_backup
  orphaned_dir: /video/orphaned
```

### Logs

https://gist.github.com/SawkeeReemo/2c286c70013b3c57e4c9a60afaf1f524

### Installation

Docker

### Version Number

4.1.9

### What branch are you on?

master
