### ISSUE TITLE
[FR] Add Options for ensuring Automatic Torrent Management is enabled

### ISSUE THREAD

**Issue by bakerboy448** [StuffAnThings/qbit_manage#66]
- x-seed
- all torrents

**Comment by bobokun** [comment]
What about having it set by tracker?
```yaml
  beyond-hd:
    tag: Beyond-HD
    notifiarr: BeyondHD
    auto_tmm: True
```
