### ISSUE TITLE
[Bug]: 'Remove Empty Directories' function, from 'Remove_Orphaned' command, deletes directories at a higher level then Orphaned_dir.

### ISSUE THREAD

**Issue by appiekap653** [StuffAnThings/qbit_manage#673]
### Describe the Bug

To add onto this issue #624 , I also noticed a related strange bug.
I used the removed orphans function and at the end, it was trying to delete the root folder.

My folder setup on the Host:
```
├── media/data/downloads/
│   ├── watch/
│   └── torrents/
│       ├── .RecycleBin/
│       ├── cross_seeds_files/
│       ├── orphaned_data/
│       ├── private/
│       │   ├── games/
│       │   ├── movies/
│       │   ├── music/
│       │   ├── prowlarr/
│       │   └── series/
│       └── public/
│           ├── games/
│           ├── movies/
│           ├── music/
│           ├── prowlarr/
│           └── series/
```

Docker mappings of qBittorrent and qBit_Manage:
```
  qbitmanage:
    volumes:
      - $DOCKERDIR/data/qbitmanage:/config:rw
      - $DOCKERDIR/data/qbittorrent/data/BT_backup:/qbittorrent/data/BT_backup:ro
      - /media/data/downloads:/data/downloads:rw
  qbittorrent:
    volumes:
      - $DOCKERDIR/data/qbittorrent:/config:rw
      - /media/data/downloads:/data/downloads:rw
```

Root_dir config in qBit_Manage:
```
directory:
  cross_seed: /data/downloads/torrents/cross_seeds_files
  root_dir: /data/downloads/
  remote_dir: /data/downloads/
  recycle_bin: /data/downloads/torrents/.RecycleBin
  torrents_dir: /qbittorrent/data/BT_backup
  orphaned_dir: /data/downloads/torrents/orphaned_data
```

Log from qBit_Manage:
```
[2024-10-09 21:28:13,573] [rem_orphaned:82]           [INFO]     | Deleting 1362 Orphaned files                                                                       |
[2024-10-09 21:29:07,597] [rem_orphaned:105]          [INFO]     | Removing newly empty directories                                                                   |
[2024-10-09 21:29:08,390] [remove_empty_directories:506] [WARNING]  | [Errno 13] Permission denied: '/data/downloads' : Unable to delete folder /data/downloads as it has permission issues. Skipping... |
[2024-10-09 21:29:08,391] [remove_empty_directories:517] [WARNING]  | [Errno 13] Permission denied: '/data/downloads' :  Unable to delete folder /data/downloads as it has permission issues. Skipping... |
[2024-10-09 21:29:08,391] [finished_run:468]          [INFO]     |     Scheduled Mode: Running every 30 minutes.              
```

After the run, it had deleted all directories except the ones that still had torrent files in them, but that also included deleting the `.RecycleBin` folder, the `cross_seeds_files` folder and some `category` folders (when currently not have torrents).
And afterwards it was even trying to delete the whole `root_dir` folder according to the log.

Do I have something wrong with this configuration of directories?

Why would qBit_Manage delete it's own `.RecycleBin` folder and `cross_seeds_files` folder? (shouldn't it automatically exclude all the folders that are stated in the `directory` section of the config file).

And trying to delete the whole `root_dir` folder should never even be considered right? 

Should the `remove_empty_directories` function have some sort of safety check to never traverse to a higher level then the `Orphaned_dir` (or any other directory given to the function in other situations)?

### Logs

https://gist.github.com/appiekap653/a322f65f04ff39a8612bf5ebdfbe4e18

### Installation

Docker

### Version Number

4.1.11

### What branch are you on?

master
