### ISSUE TITLE
[BUG] - Cross Seed torrents aren't being categorized with correct category

### ISSUE THREAD

**Issue by afraazali** [StuffAnThings/qbit_manage#69]
When I get a cross seed for tv or movies, the script used to categorize them as `cross-seed-tv` or `cross-seed-movies`. Now they're categorized as tv or movies. This is problematic because the *arrs continually try to keep importing the files. I don't move the torrents into a `tv-completed` or `movies-completed` category because I like that the *arrs delete the torrent afterwards. Here's an excerpt of my config:

```
cat:
  # <Category Name> : <save_path> #Path of your save directory. Can be a keyword or full path
  cross-seed-movies: /data/torrents/movies
  cross-seed-tv: /data/torrents/tv
```

Is this a bug, since this used to work before, or do I need to configure qbit-manager differently?

**Comment by bobokun** [comment]
when your cross seed torrent gets added does it get added to `/data/torrents/tv` and `/data/torrents/movies` save directory? Can you also share the entire `cat` section of your config?

**Comment by bakerboy448** [comment]
Are you using cross-seed's inject function? Or saving the torrents and having Qbit add them?

it seems a bug exists in cross-seed so that even with a delay so \*arrs import them, it still adds them to the wrong category

**Comment by afraazali** [comment]
@bobokun,

The workflow for tv and movies goes like this:

1) *arr initiates a grab. The *arrs categorize the torrent in movies or tv respectively
2) Upon import/upgrade, I have a custom script, through *arrs that makes a request to cross seed daemon
3) Cross seed daemon initiates a search for the torrent
4) If cross seed daemon finds torrents, it'll save the torrents in a results directory (not inject it)
5) Next time qbit-manage runs, it'll pick up the torrents from the results directory. It's at this point where qbit_manage **used to** add the torrents with the correct category (either cross-seed-tv or cross-seed-movie), but not it adds it as tv or movies

My config file: https://0bin.net/paste/Wa2kKHOD#+fsfPGuiu8tBhDl5INjlpR+tM7Pi42Y6Pn+TRFQbXkV

@bakerboy448 I have cross configured to save the torrents. I couldn't figure out how to get cross seed to inject with the correct categories. qbit_manage knew/knows how to inject the torrent with the correct category.

**Comment by afraazali** [comment]
I _think_ I see the issue. In the `cross_seed` function, it's using the original torrent's save path, whereas before it would call `get_category` with the original torrent's save path to get the correct category from the `cat` config. I _think_ it'll resolve itself on the next `cat_update` call, but I don't think it's good to wait for the next run, since it throws the *arrs in a loop of deleting/importing.

**Comment by bobokun** [comment]
Thanks for finding the bug! I'll implement a fix tomorrow as I'm out with family tonight 🙂

**Comment by afraazali** [comment]
All good. I've got a fix running on my docker container, so I can definitely wait. Thank you again.

**Comment by afraazali** [comment]
Thank you @bobokun. In my testing, the call to `config.get_category` would `raise` an `IndexError` if the path didn't exist in the `cat` config dict. After the `raise` though, the `config.get_category` would create a an entry in the `cat` config property, not raising again. On my local modifications, I've wrapped the `get_category` in a `try/except` so that if it does `raise`, I use the original torrent's save path.

**Comment by bobokun** [comment]
Thanks for testing more thoroughly. Will make the changes!

**Comment by bobokun** [comment]
> Thank you @bobokun. In my testing, the call to `config.get_category` would `raise` an `IndexError` if the path didn't exist in the `cat` config dict. 

I can't seem to replicate the `IndexError` error you're seeing. What file and line is this erroring at? I tried to remove all the categories in my config and run `--cross-seed` flag and it ran without running into any issues. Can you tell me how do you reproduce this error? Ideally I want to fix this error in the `get_category`.

**Comment by afraazali** [comment]
```
Config Warning: cat sub-attribute whatz not found using /data/torrents/whatz/ as default
Traceback (most recent call last):
  File "/app/foo.py", line 6, in <module>
    cat =cfg.get_category("/data/torrents/whatz")
  File "/app/modules/config.py", line 254, in get_category
    category = self.util.check_for_attribute(self.data, default_cat, parent="cat",default=path)
  File "/app/modules/util.py", line 147, in check_for_attribute
    print_multiline(f"Config Warning: {message}", "warning")
  File "/app/modules/util.py", line 186, in print_multiline
    logger.handlers[1].setFormatter(logging.Formatter(" " * 65 + "| %(message)s"))
IndexError: list index out of range
```

So I called the function with a path I knew didn't exist, and it came back with this error, but I noticed, it put this path in my config.yml afterwards:

Before raise:

```
cat:
  # <Category Name> : <save_path> #Path of your save directory. Can be a keyword or full path
  cross-seed-movies: /data/torrents/movies
  cross-seed-tv: /data/torrents/tv
  cross-seed-permaseed: /data/torrents/permaseed
  Educational: /data/torrents/education
  Software: /data/torrents/software
```

```
cat:
  # <Category Name> : <save_path> #Path of your save directory. Can be a keyword or full path
  cross-seed-movies: /data/torrents/movies
  cross-seed-tv: /data/torrents/tv
  cross-seed-permaseed: /data/torrents/permaseed
  Educational: /data/torrents/education
  Software: /data/torrents/software
  whatz: /data/torrents/whatz/
```

Notice the **whatz** category and path.
