### ISSUE TITLE
[Bug]: Cat in Config does not respect fuzzy matching

### ISSUE THREAD

**Issue by bakerboy448** [StuffAnThings/qbit_manage#695]
### Describe the Bug

```
cat:
  # <Category Name> : <save_path> # Path of your save directory. Can be a keyword or full path
  audiobooks: /mnt/data/torrents/audiobooks
  books: /mnt/data/torrents/books
  movies: /mnt/data/torrents/movies
  movies4k: /mnt/data/torrents/movies4k
  prowlarr: /mnt/data/torrents/prowlarr
  tv: /mnt/data/torrents/tv
  tv4k: /mnt/data/torrents/tv4k
  seeds-audiobooks: /mnt/data/torrents/seeds-audiobooks
  seeds-books: /mnt/data/torrents/seeds-books
  seeds-movies: /mnt/data/torrents/seeds-movies
  seeds-movies4k: /mnt/data/torrents/seeds-movies4k
  seeds-tv: /mnt/data/torrents/seeds-tv
  seeds-tv4k: /mnt/data/torrents/seeds-tv4k
  seeds-movies.cross-seed: /mnt/data/torrents/seeds-movies
  seeds-movies4k.cross-seed: /mnt/data/torrents/seeds-movies4k
  seeds-tv.cross-seed: /mnt/data/torrents/seeds-tv
  seeds-tv4k.cross-seed: /mnt/data/torrents/seeds-tv4k
  movies.cross-seed: /mnt/data/torrents/seeds-movies
  movies4k.cross-seed: /mnt/data/torrents/seeds-movies4k
  tv.cross-seed: /mnt/data/torrents/seeds-tv
  seeds: /mnt/data/torrents/seeds/
  seeds-data: seeds-data
```

expected that `seeds-data` matches any torrents with path like `seeds-data`
however this does not work instead it adds every save path as a cat

```
cat:
  # <Category Name> : <save_path> # Path of your save directory. Can be a keyword or full path
  audiobooks: /mnt/data/torrents/audiobooks
  books: /mnt/data/torrents/books
  movies: /mnt/data/torrents/movies
  movies4k: /mnt/data/torrents/movies4k
  prowlarr: /mnt/data/torrents/prowlarr
  tv: /mnt/data/torrents/tv
  tv4k: /mnt/data/torrents/tv4k
  seeds-audiobooks: /mnt/data/torrents/seeds-audiobooks
  seeds-books: /mnt/data/torrents/seeds-books
  seeds-movies: /mnt/data/torrents/seeds-movies
  seeds-movies4k: /mnt/data/torrents/seeds-movies4k
  seeds-tv: /mnt/data/torrents/seeds-tv
  seeds-tv4k: /mnt/data/torrents/seeds-tv4k
  seeds-movies.cross-seed: /mnt/data/torrents/seeds-movies
  seeds-movies4k.cross-seed: /mnt/data/torrents/seeds-movies4k
  seeds-tv.cross-seed: /mnt/data/torrents/seeds-tv
  seeds-tv4k.cross-seed: /mnt/data/torrents/seeds-tv4k
  movies.cross-seed: /mnt/data/torrents/seeds-movies
  movies4k.cross-seed: /mnt/data/torrents/seeds-movies4k
  tv.cross-seed: /mnt/data/torrents/seeds-tv
  seeds: /mnt/data/torrents/seeds/
  seeds-data: seeds-data
  PrivateHD: /mnt/data/torrents/seeds-data/PrivateHD/
  BroadcastheNet: /mnt/data/torrents/seeds-data/BroadcastheNet/
```

note that
  PrivateHD: /mnt/data/torrents/seeds-data/PrivateHD/
  BroadcastheNet: /mnt/data/torrents/seeds-data/BroadcastheNet/

were added

additonally it is impossible to ignore more than 1 path with the Uncategorized keyword as all keys must be distinct

### Config

```yaml
https://logs.notifiarr.com/?35bc79bc57beb353#GpbkEWwdrdHMdtCPWmSi8PTEJKPqEtcykb6n8wAytWep
```

### Logs

N/A

### Installation

Nix

### Version Number

4.1.14-develop2

### What branch are you on?

develop
