### ISSUE TITLE
[Docs]: Incorrect Docker Paths

### ISSUE THREAD

**Issue by 0xEmma** [StuffAnThings/qbit_manage#702]
### What is the improvement or update you wish to see?

The example docker config says to mount the config into /config/config.yml, however the container expects it to be at /app/config.yml

### Is there any context that might help us understand?

Update the mounts

**Comment by nichols89ben** [comment]
Came here to find an answer for this as well, the issue is happening to me

**Comment by ph1387** [comment]
As far as I can tell the paths did not change.
Check whether you mounted your qBittorrent path to the same location as your qBitManage configuration. I had the same issue today and realized, that I mounted them both to "/config". This resulted in the actual config not showing up and only the example one being present. In my case I now use the following mounts:

```    
    volumes:
      - type: volume
        source: qbittorrent-downloads
        target: /data/torrents/completed
        volume:
          nocopy: true
          subpath: data/torrents/completed
        bind:
          selinux: z # Bind mount is shared by multiple containers.
      - type: volume
        source: qbittorrent-manage
        target: /config
        volume:
          nocopy: true
          subpath: config
      - type: volume
        source: qbittorrent-config
        target: /qbittorrent
        read_only: true
        volume:
          nocopy: true
        bind:
          selinux: z # Bind mount is shared by multiple containers.
```

qBittorrent downloads are mounted to "/data/torrents/completed", the qBittorrent configuration is mounted to "/qbittorrent" and the actual qBitManage configuration is mounted to "/config"
