### ISSUE TITLE
[Bug]: data of incomplete torrents gets moved to orphaned data folder

### ISSUE THREAD

**Issue by OddMagnet** [StuffAnThings/qbit_manage#728]
### Describe the Bug

I noticed that qbit_manage moved files from an active but incomplete torrent to the orphaned data directory, resulting in Sonarr/Radarr not being able to import.

I'm not sure if this is expected behavior when qBittorrent is configured to use a specific directory for incomplete torrents, but I'd assume that shouldn't be a problem.

### Config

```yaml
qbt:
  # qBittorrent parameters
  host: qbittorrent.internal:8080
  user: USER
  pass: PASSWORD

settings:
  force_auto_tmm: false # Will force qBittorrent to enable Automatic Torrent Management for each torrent.
  tracker_error_tag: issue # Will set the tag of any torrents that do not have a working tracker.
  nohardlinks_tag: noHL # Will set the tag of any torrents with no hardlinks.
  share_limits_tag: ~share_limit # Will add this tag when applying share limits to provide an easy way to filter torrents by share limit group/priority for each torrent
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached # Tag to be added to torrents that have not yet reached the minimum seeding time
  share_limits_min_num_seeds_tag: MinSeedsNotMet # Tag to be added to torrents that have not yet reached the minimum number of seeds
  share_limits_last_active_tag: LastActiveLimitNotReached # Tag to be added to torrents that have not yet reached the last active limit
  cross_seed_tag: cross-seed # Will set the tag of any torrents that are added by cross-seed command
  cat_filter_completed: true # Filters for completed torrents only when running cat_update command
  share_limits_filter_completed: true # Filters for completed torrents only when running share_limits command
  tag_nohardlinks_filter_completed: false # Filters for completed torrents only when running tag_nohardlinks command
  cat_update_all: true

  force_auto_tmm_ignore_tags: []
  disable_qbt_default_share_limits: true

directory:
  cross_seed:
  root_dir: /data/torrents/
  remote_dir:
  recycle_bin: /data/torrents/.RecycleBin
  torrents_dir:
  orphaned_dir: /data/torrents/orphaned_data

cat:
  # omitted for brevity

tracker:
  # omitted for brevity

nohardlinks:
  # omitted for brevity

recyclebin:
  enabled: true
  empty_after_x_days: 30
  save_torrents: false
  split_by_category: false

orphaned:
  empty_after_x_days: 30
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - /data/torrents/temp/**
  - /data/torrents/files/**
  - '**/*.!qB'
  - '**/*_unpackerred'
  max_orphaned_files_to_delete: 50

notifiarr:
  apikey: A-P-I-K-E-Y
  instance:

webhooks:
  error: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  function:
    cross_seed: notifiarr
    recheck: notifiarr
    cat_update: notifiarr
    tag_update: notifiarr
    rem_unregistered: notifiarr
    tag_tracker_error: notifiarr
    rem_orphaned: notifiarr
    tag_nohardlinks: notifiarr
    share_limits: notifiarr
    cleanup_dirs: notifiarr
```

### Logs

https://gist.github.com/OddMagnet/3fbac9f20fca6556e596cdd6b831d4cf

### Installation

Docker

### Version Number

4.1.14

### What branch are you on?

master
