### ISSUE TITLE
[Bug]: Nohardlink Error: Unable to open the folder /media/downloads/

### ISSUE THREAD

**Issue by kristianvmd** [StuffAnThings/qbit_manage#729]
### Describe the Bug

I have carefully checked all the parameters and paths, so why is there still an error?

### Config

```yaml
commands:
  dry_run: false
  cross_seed: false
  recheck: false
  cat_update: false
  tag_update: false
  rem_unregistered: false
  tag_tracker_error: false
  rem_orphaned: false
  tag_nohardlinks: false
  share_limits: false
  skip_qb_version_check: false
  skip_cleanup: false

qbt:
  host: 172.17.0.1:8085
  user: admin
  pass: 20202021ab

settings:
  force_auto_tmm: false 
  force_auto_tmm_ignore_tags: 
  - cross-seed
  - Upload
  tracker_error_tag: issue 
  nohardlinks_tag: noHL
  share_limits_tag: ~share_limit
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
  cross_seed_tag: cross-seed
  cat_filter_completed: true
  share_limits_filter_completed: true
  tag_nohardlinks_filter_completed: true
  cat_update_all: true
  disable_qbt_default_share_limits: true

directory:
  cross_seed: /your/path/here/
  root_dir: /data/torrents/
  remote_dir: /data/torrents/
  recycle_bin: /data/torrents/.RecycleBin
  torrents_dir: /qbittorrent/data/BT_backup
  orphaned_dir: /data/torrents/orphaned_data

cat:
  movie: /data/torrents/movie
  tv: /data/torrents/tv

cat_change:
  Radarr-HD.cross-seed: movies-hd
  Radarr-UHD.cross-seed: movies-uhd
  movies-hd.cross-seed: movies-hd
  movies-uhd.cross-seed: movies-uhd

tracker:
  animebytes.tv:
    tag: AnimeBytes
    notifiarr: animebytes
  avistaz:
    tag:
    - Avistaz
    - tag2
    - tag3
    notifiarr: avistaz
  beyond-hd:
    tag: [Beyond-HD, tag2, tag3]
    cat: movies
    notifiarr: beyondhd
  blutopia:
    tag: Blutopia
    notifiarr: blutopia
  cartoonchaos:
    tag: CartoonChaos
  digitalcore:
    tag: DigitalCore
    notifiarr: digitalcore
  gazellegames:
    tag: GGn
  hdts:
    tag: HDTorrents
  landof.tv:
    tag: BroadcasTheNet
    notifiarr: broadcasthenet
  myanonamouse:
    tag: MaM
  passthepopcorn:
    tag: PassThePopcorn
    notifiarr: passthepopcorn
  privatehd:
    tag: PrivateHD
    notifiarr:
  torrentdb:
    tag: TorrentDB
    notifiarr: torrentdb
  torrentleech|tleechreload:
    tag: TorrentLeech
    notifiarr: torrentleech
  tv-vault:
    tag: TV-Vault
  other:
    tag: other

nohardlinks:
  movie:
    exclude_tags:
    - Beyond-HD
    - AnimeBytes
    - MaM
    - keep
  tv:
    exclude_tags:
    - Beyond-HD
    - BroadcasTheNet
    - keep
    ignore_root_dir: true

share_limits:
  noHL:
    priority: 1
    include_all_tags:
    - noHL
    include_any_tags:
    - noHL

exclude_all_tags:
- Beyond-HD
exclude_any_tags:
- Beyond-HD
categories:
- RadarrComplete
- SonarrComplete
max_ratio: 5.0
max_seeding_time: 90d
min_seeding_time: 30d
last_active: 30d
limit_upload_speed: 0
enable_group_upload_speed: false
cleanup: false
resume_torrent_after_change: true
add_group_to_tag: true
min_num_seeds: 0
custom_tag: sharelimits_noHL
cross-seed:
  priority: 2
  include_all_tags:
  - cross-seed
  max_seeding_time: 7d
  cleanup: false
PTP:
  priority: 3
  include_all_tags:
  - PassThePopcorn
  max_ratio: 2.0
  max_seeding_time: 90d
  cleanup: false
default:
  priority: 999
  max_ratio: -1
  max_seeding_time: -1
  cleanup: false

recyclebin:
  enabled: true
  empty_after_x_days: 3
  save_torrents: false
  split_by_category: false

orphaned:
  empty_after_x_days: 0
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - '**/*.!qB'
  - '**/*_unpackerred'
  - /data/torrents/temp/**
  max_orphaned_files_to_delete: -1

apprise:
  api_url:
  notify_url:

notifiarr:
  apikey: ####################################
  instance:

webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck: notifiarr
    cat_update: apprise
    tag_update: notifiarr
    rem_unregistered: notifiarr
    tag_tracker_error: notifiarr
    rem_orphaned: notifiarr
    tag_nohardlinks: notifiarr
    share_limits: notifiarr
    cleanup_dirs: notifiarr
```

### Logs

https://gist.github.com/kristianvmd/6eec2a607cf47fc275f58d662e94c6e5#file-gistfile1-txt

### Installation

Docker

### Version Number

latest

### What branch are you on?

master
