### ISSUE TITLE
[FR]: Limit upload speed after share ratio is reached

### ISSUE THREAD

**Issue by pentago** [StuffAnThings/qbit_manage#731]
### Is your feature request related to a problem? Please elaborate.

Currently, me as well as ton of other users have seedboxes with fixed monthly bandwidth allowance.

To be continue to seed evenly across a number of trackers that are more important to me, I don't want to waste upload bandwidth further if torrent reached say ratio of 5.0.

For example, this morning I woke up and noticed 1 torrent took 5TB of upload overnight, effectively gutting 25% of bandwidth allowance in less than a day so I have to manually inspect and set upload speed on individual torrents so this doesn't get out of hand quickly.

Currently, we only have the option to limit upload speed from the start and proposed config option would limit after ratio is reached.

### Describe the solution you'd like

I'd prefer a `share_limits` config option, let's say `limit_upload_speed_on_ratio: 1024KB` or similar which allows users to define ratio which when reached by a torrent, limits upload speed on said torrent to 1024KB, optionally/preferably, until the other limit like `max_ratio` is reached.

### Does your solution involve any of the following?

- [x] New config option
- [ ] New command option

### Describe alternatives you've considered

Manual work or custom scripting.

I also tried this but after max_ratio is reached, torrents just stop (_do not resume_):

```
share_limits:
  limited:
    priority: 1
    include_any_tags:
    - FL
    - TL
    max_ratio: 5.0
    limit_upload_speed: 100
    resume_torrent_after_change: true
    add_group_to_tag: true
    custom_tag: limited
    cleanup: false
```

### Who will this benefit?

Everyone with smaller bandwidth allowance.
For example, my monthly allowance is 20TB and I was left without any bandwidth multiple times in previous months and had to either purchase additional or just limit all torrents upload speed until month ends.
