### ISSUE TITLE
[FR]: Tag torrents by age and\or last activity

### ISSUE THREAD

**Issue by Barina** [StuffAnThings/qbit_manage#788]
### Is your feature request related to a problem? Please elaborate.

Not really a problem but will be nice to have old (and ancient) torrents tagged based on their age or their last activity.

### Describe the solution you'd like

According to "added_on", tag all torrents that are n years old. 
It can be based on "added_on" (if supported) or "last_activity" (the date of last leech or seed) and can act as a filter so we can add multiple filters, like older than 2 years will get a "old" tag but older than 5 year will get an "ancient" tag (and the "old" tag removed) etc.

### Does your solution involve any of the following?

- [ ] New config option
- [ ] New command option

### Describe alternatives you've considered

I tried adding the following snippet to the config file, but looks like "added_on" isn't a supported key yet:
```
  custom:
    - tag: ancient
      remove_tag: old
      custom_filter:
        - added_on:
            less_than: "{{ now() - timedelta(days=1825) }}" # 1825 days = 5 years
    - tag: old
      custom_filter:
        - added_on:
            less_than: "{{ now() - timedelta(days=730) }}" # 730 days = 2 years
        - added_on:
            greater_than: "{{ now() - timedelta(days=1825) }}"
```

### Who will this benefit?

Anyone who likes to keep he's stuff neat.
Will make our life easier if we have lots of torrents, we'll be able to focus on the old stuff for managing, especially the "last activity" approach.
