### ISSUE TITLE
[Bug]: Jobs being skipped without apparent reason

### ISSUE THREAD

**Issue by AN1MATEK** [StuffAnThings/qbit_manage#789]
### Describe the Bug

Hello there,

I noticed I had a bunch of torrents that should have long been deleted and after closer inspection I see that qbit_manage is skipping these jobs, specifically `PnD` and `ANT` in my config file:

I tried changing the priorities (before I had numbers like 1.0001) but it did not help.

Docker 4.2.1 on unRAID.

### Config

```yaml
commands:
  dry_run: false
  cross_seed: false
  recheck: false
  cat_update: false
  tag_update: true
  rem_unregistered: false   # 24h run
  tag_tracker_error: false
  rem_orphaned: false       # 24h run
  tag_nohardlinks: false    # 24h run
  skip_cleanup: true        # 24h run
  share_limits: true
  skip_qb_version_check: true

qbt:
  host: http://10.1.3.20:8888
  user: qbt
  pass: uLQV-AoK7_

settings:
  force_auto_tmm: true
  tracker_error_tag: issue
  nohardlinks_tag: noHL
  share_limits_tag: ~qbm
  ignoreTags_OnUpdate:
  - ANIMATEK
  - PnD
  - issue
  - noHL
  - cross-seed
  - seasonpackarr
  - upgraderr
  - LastActiveLimitNotReached
  - MinSeedsNotMet
  - MinSeedTimeNotReached

  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
  cross_seed_tag: cross-seed
  cat_filter_completed: true
  share_limits_filter_completed: true
  tag_nohardlinks_filter_completed: true
  force_retag_all: false
  cat_update_all: true
  force_auto_tmm_ignore_tags: []
  disable_qbt_default_share_limits: true

  tag_stalled_torrents: true
  rem_unregistered_ignore_list: []
  rem_unregistered_filter_completed: false
directory:
  root_dir: /media/torrents
  remote_dir: /media/torrents
  recycle_bin: /media/torrents/.bin
  torrents_dir: /BT_backup
  orphaned_dir: /media/torrents/.orphaned
  cross_seed: /media/torrents/.cross-seed

cat:
  TV: /media/torrents/tv
  TV-Imported: /media/torrents/tv
  TV-Imported.cross-seed: /media/torrents/tv
  Movies: /media/torrents/movies
  Movies-Imported: /media/torrents/movies
  Movies-Imported.cross-seed: /media/torrents/movies
  AudioBooks: /media/torrents/books
  AudioBooks-Imported: /media/torrents/books
  Music: /media/torrents/music
  Music-Imported: /media/torrents/music
  eBooks: /media/torrents/books
  eBooks-Imported: /media/torrents/books
  Software: /media/torrents/software
  Uncategorized: /media/torrents/uncategorized/

cat_change:

tracker: # Mandatory
  anthelion:
    tag: '[ANT]'
  alpharatio:
    tag: '[AR]'
  aither:
    tag: '[ATH]'
  btarg:
    tag: '[ARG]'
  animetorrents:
    tag: '[AT]'
  blutopia:
    tag: '[BLU]'
  cinemaz:
    tag: '[CZ]'
  fearnopeer:
    tag: '[FNP]'
  filelist:
    tag: '[FL]'
  gazellegames:
    tag: '[GGn]'
  hdts-announce:
    tag: '[HDT]'
  hawke:
    tag: '[HUNO]'
  ianon:
    tag: '[IAN]'
  empirehost:
    tag: '[IPT]'
  immortalseed:
    tag: '[IS]'
  lat-team:
    tag: '[LAT]'
  lst.gg:
    tag: '[LST]'
  myanonamouse:
    tag: '[MAM]'
  morethantv:
    tag: '[MTV]'
  opsfet:
    tag: '[OPS]'
  oldtoons:
    tag: '[OTW]'
  privatehd:
    tag: '[PHD]'
  flacsfor.me:
    tag: '[RED]'
  reelflix:
    tag: '[RFX]'
  torrentleech:
    tag: '[TL]'
  tv-vault:
    tag: '[TVV]'
  uhdbits:
    tag: '[UHD]'
  other:
    tag: '[PUB]'

nohardlinks:
- TV-Imported
- Movies-Imported
- AudioBooks-Imported
- eBooks-Imported
- Music-Imported

share_limits:
  ANIMATEK:
    priority: 1
    include_all_tags:
    - ANIMATEK
    exclude_any_tags:
    - noHL
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    last_active: 0
    max_seeding_time: -1
    add_group_to_tag: false
    cleanup: false

  ANIMATEK.noHL:
    priority: 1.1
    include_all_tags:
    - ANIMATEK
    - noHL
    categories:
    - TV-Imported
    - Movies-Imported
#    - AudioBooks-Imported
#    - eBooks-Imported
#    - Music-Imported
    last_active: 3d
    max_seeding_time: 100d
    add_group_to_tag: false
    cleanup: true

  PnD:
    priority: 1.2
    include_all_tags:
    - PnD
    categories:
    - TV-Imported
    - Movies-Imported
    - Music-Imported
    last_active: 0
    max_seeding_time: 10d12h
    add_group_to_tag: false
    cleanup: true

  ANT:
    priority: 2
    include_any_tags:
    - '[ANT]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    last_active: 0
    max_seeding_time: -1 # 7 days but permaseeding
    min_num_seeds: 1
    add_group_to_tag: false
    cleanup: false

  ATH:
    priority: 3
    include_any_tags:
    - '[ATH]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    last_active: 0
    min_num_seeds: 1
    max_seeding_time: -1 # 30d 12h but permaseeding
    add_group_to_tag: false
    cleanup: false

  ARG:
    priority: 4
    include_all_tags:
    - '[ARG]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    last_active: 6h
    max_seeding_time: 7d
    min_num_seeds: 1
    add_group_to_tag: false
    cleanup: false

  AR:
    priority: 5
    include_any_tags:
    - '[AR]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    last_active: 0
    max_seeding_time: 14d
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  AT:
    priority: 6
    include_any_tags:
    - '[AT]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    last_active: 0
    max_seeding_time: -1 # 7d - no hay reglas, solo ratio positivo
    min_num_seeds: 1
    add_group_to_tag: false
    cleanup: false

  BLU:
    priority: 7
    include_any_tags:
    - '[BLU]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    last_active: 0
    max_seeding_time: -1 # 7 days but permaseeding
    min_num_seeds: 1
    add_group_to_tag: false
    cleanup: false

  CZ:
    priority: 8
    include_any_tags:
    - '[CZ]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    last_active: 0
    max_seeding_time: 14d6h
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  FNP:
    priority: 9
    include_all_tags:
    - '[FNP]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    - Music-Imported
    - Software
    limit_upload_speed: 1024
    last_active: 6h
    max_seeding_time: 7d
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  FL:
    priority: 10
    include_any_tags:
    - '[FL]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    last_active: 0
    max_seeding_time: 7d
    min_num_seeds: 1
    add_group_to_tag: false
    cleanup: false

  GGn:
    priority: 11
    include_any_tags:
    - '[GGn]'
    exclude_any_tags:
#    - noHL
#    - cross-seed
#    - upgraderr
    categories:
    - Software
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    last_active: 0
    max_seeding_time: -1
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  HDT:
    priority: 12
    include_all_tags:
    - '[HDT]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    last_active: 24h
    max_seeding_time: 31d
    min_num_seeds: 3
    add_group_to_tag: false
    cleanup: false

  HUNO:
    priority: 13
    include_all_tags:
    - '[HUNO]'
    exclude_any_tags:
    - noHL
    - upgraderr
    - cross-seed
    categories:
    - TV-Imported
    - Movies-Imported
    last_active: 0
    max_seeding_time: -1 # Permaseeding
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  IAN:
    priority: 14
    include_all_tags:
    - '[IAN]'
    categories:   # Software won't ever have hard-links 
    - Software
    last_active: 0
    max_seeding_time: -1 # Permaseeding
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  IPT:
    priority: 15
    include_all_tags:
    - '[IPT]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    last_active: 0
    limit_upload_speed: 100
    max_seeding_time: 14d6h
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false
    
  IS:
    priority: 16
    include_all_tags:
    - '[IS]'
    exclude_any_tags:
    - noHL
#    - cross-seed
#    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    last_active: 0
    limit_upload_speed: 100
    max_seeding_time: 14d6h
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  LAT:
    priority: 17
    include_all_tags:
    - '[LAT]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    limit_upload_speed: 1024
    last_active: 6h
    max_seeding_time: 7d
    min_num_seeds: 1
    add_group_to_tag: false
    cleanup: false

  LST:
    priority: 18
    include_all_tags:
    - '[LST]'
    exclude_any_tags:
    - noHL
#    - cross-seed
#    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    last_active: 0
    max_seeding_time: -1 # 3d minimum https://lst.gg/pages/1
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  MAM:
    priority: 19
    include_any_tags:
    - '[MAM]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - AudioBooks-Imported
    - eBooks-Imported
    last_active: 0
    max_seeding_time: -1
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  MTV:
    priority: 20
    include_any_tags:
    - '[MTV]'
    exclude_any_tags:
    - noHL
#    - cross-seed 
#    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    last_active: 0
    max_seeding_time: -1
    min_num_seeds: 1
    add_group_to_tag: false
    cleanup: false

  OPS:
    priority: 21
    include_all_tags:
    - '[OPS]'
#    exclude_any_tags:
#    - noHL
#    - cross-seed
#    - upgraderr
    categories:
    - Music-Imported
    last_active: 0
    max_seeding_time: -1
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  OTW:
    priority: 22
    include_all_tags:
    - '[OTW]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    limit_upload_speed: 1024
    last_active: 6h
    max_seeding_time: 3d
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  PHD:
    priority: 23
    include_any_tags:
    - '[PHD]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    last_active: 6h
    max_seeding_time: 14d # https://privatehd.to/rules/hit-run-rules
    min_num_seeds: 1
    add_group_to_tag: false
    cleanup: false

  RED:
    priority: 24
    include_all_tags:
    - '[RED]'
#    exclude_any_tags:
#    - noHL
#    - cross-seed
#    - upgraderr
    categories:
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    - Software
    last_active: 0
    max_seeding_time: -1
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  RFX:
    priority: 25
    include_any_tags:
    - '[RFX]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - Movies-Imported
    last_active: 0
    max_seeding_time: -1 # RATIO BUILDING
    min_num_seeds: 1
    add_group_to_tag: false
    cleanup: false

  TL:
    priority: 26
    include_all_tags:
    - '[TL]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    - Software
    last_active: 0
    limit_upload_speed: 1024
    max_seeding_time: 6d6h # https://wiki.torrentleech.org/doku.php/hnr
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  TVV:
    priority: 27
    include_all_tags:
    - '[TVV]'
    exclude_any_tags:
    - noHL
#    - cross-seed
#    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    - Software
    last_active: 0
    max_seeding_time: -1 # 5d6h https://torrentseeds.org/pages/1
    min_num_seeds: 1
    add_group_to_tag: false
    cleanup: false

  UHD:
    priority: 28
    include_all_tags:
    - '[UHD]'
    exclude_any_tags:
    - noHL
    - cross-seed
    - upgraderr
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    - Software
    last_active: 0
    max_seeding_time: -1 # No seed time, just ratio above 0.2
    min_num_seeds: 1
    add_group_to_tag: false
    cleanup: false

  PUB:
    priority: 29
    include_all_tags:
    - '[PUB]'
    exclude_any_tags:
    - noHL
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    - Software
    limit_upload_speed: 512
    last_active: 0
    max_ratio: 5
    max_seeding_time: 3d
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  xseed.t0:
    priority: 30
    include_any_tags:
    - '[ANT]'
    - '[ATH]'
    - '[BLU]'
    - '[MTV]'
    - '[LST]'
    - '[HUNO]'
    include_all_tags:
    - cross-seed
    exclude_all_tags:
    - noHL
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    last_active: 0
    max_seeding_time: -1
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  xseed.t1:
    priority: 31
    include_any_tags:
    - '[ARG]'
    - '[LAT]'
    - '[RFX]'
    - '[MAM]'
    - '[RED]'
    include_all_tags:
    - cross-seed
    exclude_all_tags:
    - noHL
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    limit_upload_speed: 256
    last_active: 0 # 24h
    max_seeding_time: -1 # 7d
    min_num_seeds: 0 # 1
    add_group_to_tag: false
    cleanup: false

  xseed.t2:
    priority: 32
    include_any_tags:
    - '[AT]'
    - '[AR]'
    - '[HDT]'
    - '[FL]'
    - '[PHD]'
    - '[TVV]'
    - '[UHD]'
    include_all_tags:
    - cross-seed
    exclude_all_tags:
    - noHL
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    limit_upload_speed: 256
    last_active: 6h
    max_seeding_time: 3d
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  xseed.t3:
    priority: 33
    include_any_tags:
    - '[ABT]'
    - '[CZ]'
    - '[DCC]'
    - '[OTW]'
    - '[IS]'
    include_all_tags:
    - cross-seed
    exclude_all_tags:
    - noHL
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    limit_upload_speed: 128
    last_active: 1h
    max_seeding_time: 24h
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  xseed.t5:
    priority: 34
    include_any_tags:
    - '[FNP]'
    - '[IPT]'
    - '[SCD]'
    - '[TL]'
    include_all_tags:
    - cross-seed
    exclude_all_tags:
    - noHL
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    limit_upload_speed: 64
    last_active: 0
    max_seeding_time: 0  # Just add, don't seed
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: false

  noHL.100d:
    priority: 35
    include_any_tags:
    - '[ATH]'
    - '[BLU]'
    - '[GGn]'
    - '[RED]'
    include_all_tags:
    - noHL
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    last_active: 7d
    max_seeding_time: 100d
    min_num_seeds: 1
    add_group_to_tag: false
    cleanup: true

  noHL.31d:
    priority: 36
    include_any_tags:
    - '[LST]'
    - '[MTV]'
    - '[TVV]'
    include_all_tags:
    - noHL
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    last_active: 7d
    max_seeding_time: 31d
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: true

  noHL.14d:
    priority: 37
    include_any_tags:
    - '[ANT]'
    - '[ABT]'
    - '[AT]'
    - '[AR]'
    - '[CZ]'
    - '[HUNO]'
    - '[HDT]'
    - '[RFX]'
    - '[IPT]'
    - '[IS]'
    - '[MAM]'
    - '[PHD]'
    include_all_tags:
    - noHL
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    limit_upload_speed: 1024
    last_active: 0
    max_seeding_time: 14d12h
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: true

  noHL.7d:
    priority: 38
    include_any_tags:
    - '[DCC]'
    - '[LAT]'
    - '[TL]'
    include_all_tags:
    - noHL
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    limit_upload_speed: 1024
    last_active: 0
    max_seeding_time: 7d4h
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: true

  noHL.3d:
    priority: 39
    include_any_tags:
    - '[ARG]'
    - '[FL]'
    - '[FNP]'
    - '[OTW]'
    - '[SCD]'
    - '[UHD]'
    - '[PUB]'
    include_all_tags:
    - noHL
    categories:
    - TV-Imported
    - Movies-Imported
    - AudioBooks-Imported
    - eBooks-Imported
    - Music-Imported
    - Software
    limit_upload_speed: 1024
    last_active: 0
    max_seeding_time: 3d4h
    min_num_seeds: 0
    add_group_to_tag: false
    cleanup: true

recyclebin:
  enabled: true
  empty_after_x_days: 7
  save_torrents: true
  split_by_category: false

orphaned:
  empty_after_x_days: 7
  exclude_patterns:
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/@eaDir'
  - '**/*.!qB'
  - '**/_unpackerred'
  - /media/torrents/.bin/*
  - /media/torrents/.cross-seed/*
  - /media/torrents/.torrents/*
  - /media/torrents/.queue/*
  max_orphaned_files_to_delete: -1

webhooks:
  run_start:
  run_end:
  error:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    cleanup_dirs:
    share_limits:
```

### Logs

https://gist.github.com/AN1MATEK/9e4ab620484ee63828b17307a7740dbf

### Installation

Docker

### Version Number

4.2.1

### What branch are you on?

master
