### ISSUE TITLE
[Bug]: Keeps adding a tracker to the tags

### ISSUE THREAD

**Issue by OFark** [StuffAnThings/qbit_manage#799]
### Describe the Bug

I can't remove tracker.opentrackr.org from the config. Every time I restart the app it adds it back into the config again.

### Config

```yaml
qbt:
  # qBittorrent parameters
  # Pass environment variables to the config via !ENV tag
  host: 
  user:
  pass:
directory:
  # Do not remove these
  # root_dir var: </your/path/here/>  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  # <OPTIONAL> remote_dir var: </your/path/here/>  # Path of docker host mapping of root_dir.
  # remote_dir must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # remote_dir should not be set if qbit_manage is running in a container
  # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # <OPTIONAL> torrents_dir var: </your/path/here/>  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin
  # <OPTIONAL> orphaned_dir var: </your/path/here/>  # Path of the the Orphaned Data folder. This is similar to RecycleBin, but only for orphaned data.
  root_dir: ' /data/downloads/'
  # remote_dir: "/host/path/to/torrents/ifdocker/torrents/"
  # recycle_bin: "/path/to/.RecycleBin"
  # torrents_dir: "/path/to/qbitAppData/BT_backup"
  # orphaned_dir: "/path/to/orphaned_data"
  recycle_bin: ' /data/downloads/.RecycleBin'
  torrents_dir:
tracker:
  # Mandatory
  # Tag Parameters
  # <Tracker URL Keyword>:    # <MANDATORY> This is the keyword in the tracker url. You can define multiple tracker urls by splitting with `|` delimiter
  # <MANDATORY> Set tag name. Can be a list of tags or a single tag
  #   tag: <Tag Name>
  # <OPTIONAL> Set the category based on tracker URL. This category option takes priority over the category defined by save directory
  #   cat: <Category Name>
  # <OPTIONAL> Set this to the notifiarr react name. This is used to add indexer reactions to the notifications sent by Notifiarr
  #   notifiarr: <notifiarr indexer>
  animebytes.tv:
    tag: AnimeBytes
  digitalcore:
    tag: DCC
  myanonamouse:
    tag: MAM
  seedpool:
    tag: Seed
  tracker.opentrackr.org:
    tag: tracker.opentrackr.org
settings:
  force_auto_tmm: false
  tracker_error_tag: issue
  nohardlinks_tag: noHL
  share_limits_tag: ~share_limit
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
  cat_filter_completed: true
  share_limits_filter_completed: true
  tag_nohardlinks_filter_completed: true
  rem_unregistered_filter_completed: false
  cat_update_all: true
  force_auto_tmm_ignore_tags: []
  disable_qbt_default_share_limits: true
  tag_stalled_torrents: false
  rem_unregistered_ignore_list: []
webhooks:
  error:
  run_start:
  run_end:
  function:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    share_limits:
    cleanup_dirs:
recyclebin:
  enabled: true
  empty_after_x_days:
  save_torrents: false
  split_by_category: false
orphaned:
  empty_after_x_days:
  exclude_patterns:
  max_orphaned_files_to_delete: 50
```

### Logs

https://gist.github.com/OFark/4067d2fbc18b3f28bddd3f9f1fd440b6

### Installation

Unraid

### Version Number

Version: 4.2.2 (Docker)

### What branch are you on?

master
