### ISSUE TITLE
[Bug]: Using -2 as a max ratio target causes qbit_manage to repeatedly update a torrent's share limits

### ISSUE THREAD

**Issue by chrisfosterelli** [StuffAnThings/qbit_manage#831]
### Describe the Bug

When using the `share_limits` functionality, a `max_ratio` of `-2` is intended to allow the Global Limit. However, using `-2` will cause qbit_manage to identify every torrent for update on every run.

The functionality I'm trying to achieve is to have torrents completed by either of:
1. A maximum ratio of 10, or
2. A max seed time of 90 days if the item is no longer in plex

I am trying to achieve this by setting qbittorrent to have a global maximum ratio of 10 in the settings, and then using `share_limits` to set `max_seeding_time: 90d` on torrents that are identified by `nohardlinks`. Ideally my maximum ratio can be specified in only one place, so it's easy to change if I need.

If I don't specify _any_ `max_ratio`, then qbittorrent seems to interpret items as deleted from plex to have no maximum ratio, only a max seed time. So I then tried to set `-2` as I saw that available in the docs, however it tries to update every matching torrent on every run. You can see this occur in the trace logs as it compares `-2` directly against the global seed limit:

```
Config Max Ratio vs Torrent Max Ratio:-2.0 vs 10
check_max_ratio: True
```

Example config excerpt:

```
share_limits:
  Cross Seed:
    priority: 3
    include_any_tags:
    - not-in-plex
    categories:
    - Cross Seed
    max_ratio: -2
    max_seeding_time: 90d
    add_group_to_tag: false
    cleanup: true
```

I can work around this by setting the actual limit to set to 10, but that gives a few extra places to remember to update. Not a huge deal either way but thought it was worth a report as I did not realize at first that it might _not_ be intended to print out every torrent on each run and that could be a fair bit of extraneous requests for large seeders.

In my log file I have included two back-to-back runs of qbit_manage which shows that the application repeats all share limit operations.

### Config

```yaml
commands:
  dry_run: false
  recheck: false
  cat_update: false
  tag_update: true
  rem_unregistered: false
  tag_tracker_error: false
  rem_orphaned: true
  tag_nohardlinks: true
  share_limits: true
  skip_cleanup: false
  skip_qb_version_check: false
qbt:
  host: qbittorrent:8080
  user: chrisfosterelli
  pass: ****
settings:
  force_auto_tmm: false
  tracker_error_tag: issue
  nohardlinks_tag: not-in-plex
  stalled_tag: stalledDL
  share_limits_tag: ~share_limit
  share_limits_min_seeding_time_tag: MinSeedTimeNotReached
  share_limits_min_num_seeds_tag: MinSeedsNotMet
  share_limits_last_active_tag: LastActiveLimitNotReached
  cat_filter_completed: true
  share_limits_filter_completed: true
  tag_nohardlinks_filter_completed: true
  rem_unregistered_filter_completed: false
  cat_update_all: true
  force_auto_tmm_ignore_tags: []
  disable_qbt_default_share_limits: false
  tag_stalled_torrents: false
  rem_unregistered_ignore_list: []
directory:
  root_dir: /data/torrents/
  torrents_dir:
  orphaned_dir: /data/torrents/orphaned_data
cat:
  Cross Seed:
  Movies: /downloads/movies
  TV: /downloads/tv
tracker:
  ****
  other:
    tag: public-tracker
nohardlinks:
  Movies:
  TV:
  Cross Seed:
share_limits:
  Movies:
    priority: 1
    include_any_tags:
    - not-in-plex
    categories:
    - Movies
    max_ratio: -2
    max_seeding_time: 90d
    add_group_to_tag: false
    cleanup: false
  TV:
    priority: 2
    include_any_tags:
    - not-in-plex
    categories:
    - TV
    max_ratio: -2
    max_seeding_time: 90d
    add_group_to_tag: false
    cleanup: false
  Cross Seed:
    priority: 3
    include_any_tags:
    - not-in-plex
    categories:
    - Cross Seed
    max_ratio: -2
    max_seeding_time: 90d
    add_group_to_tag: false
    cleanup: true
recyclebin:
  enabled: false
  empty_after_x_days:
  save_torrents: false
  split_by_category: false
webhooks:
  error:
  run_start:
  run_end:
  function:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    share_limits:
    cleanup_dirs:
orphaned:
  empty_after_x_days: 90
  exclude_patterns:
  max_orphaned_files_to_delete: 50
```

### Logs

https://gist.github.com/chrisfosterelli/99574140578a8ce0916e5587bae1e198

### Installation

Docker

### Version Number

4.3.0

### What branch are you on?

master
