### ISSUE TITLE
[FR]: Set seed time / ratio for a specific tag 

### ISSUE THREAD

**Issue by quorn23** [StuffAnThings/qbit_manage#88]
### Is your feature request related to a problem? Please elaborate.

No

### Describe the solution you'd like

would it be possible to add the possibility to set a seed-time via qbit-manage for a specific tag? So i could just set the seeding time for "cross-seed" tagged torrents to 6 days for example?

> TABLE — Today at 11:21 PM
> Something like that would probably suit my issue the other day regarding having a long term seeding tag thats > ignored/permaseed also
> Say I want to set a tracker specific seed time/ratio rule, but also have an lts (long term seeding) category I use that I just want > to exclude from automatic pausing so it can remain seeding perpetually even if the torrent is from that tracker. 

> As far as I can see from the config and some brief digging around github this isnt supported at the tracker tag level and I > would instead need to forego per tracker limits and just set those limits the same across all trackers per category under the > nohardlinks section? So that the lts category isnt being controlled by qbm?

These are two examples for the FR. Having the possibility to define those for tags we can specify in qbit-manage would help some use cases.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

Tried to set a tracker tag as "cross-seed" for my case as discussed in Discord. Didn't do the trick

### Who will this benefit?

Everyone that has the need to handle specific tags with specific times/ratios

**Comment by bobokun** [comment]
I'm thinking of implementing a priority feature for specifying share limits. Please take a look at the sample config to see if it would satisfy this requirements. This would mean that you will no longer be able to specify the share limits in the `tracker` or `nohardlinks` section of the config.yml and that would be deprecated and replaced with the following below, but that won't be an issue since anything you can do in the current config under those two sections would be able to be done in the new share_limits section.

```yaml
share_limits:
  priority:
    1:
      tags:
        - noHL
      exclude_tags:
        - Beyond-HD
      categories:
        - RadarrComplete
        - SonarrComplete
      max_ratio: 4.0
      max_seeding_time: 129600
      limit_upload_speed:
    2:
      tags:
        - cross-seed
      max_ratio: 1.0
      max_seeding_time: 10200
    3:
      tags:
        - PassThePopcorn
        - blutopia
      max_ratio: 2.0
      max_seeding_time: 130000

```
How this works is that when tagging new torrents, or tagging noHL/cross-seed, it will start from the first priority and if it matches any of the tags it will apply the share limits defined. If not it will move onto the  next priority etc...
