### ISSUE TITLE
[FR]: Tag Torrents with Existing Tags

### ISSUE THREAD

**Issue by HarryMuscle** [StuffAnThings/qbit_manage#95]
### Is your feature request related to a problem? Please elaborate.

I usually add several tags when initially adding torrents and according to the description qbit-manage will only add tracker based tags to torrents without tags.  That greatly reduces qbit-manage's usability in my situation and for others with a similar workflow.

### Describe the solution you'd like

It would be very helpful to have a configuration setting that would allow qbit-manage to add tags to torrents with already existing tags.

### Does your solution involve any of the following?

- [X] New config option
- [ ] New command option

### Describe alternatives you've considered

I've started looking into scripting a solution myself but having this ability in qbit-manage would be preferred.

### Who will this benefit?

Anyone who likes to tag their torrents right away but still wants them tagged by qbit-manage.

**Comment by HarryMuscle** [comment]
I was looking through the source code and I noticed that it's already setup to ignore certain hard coded tags.  I think a possible simpler and quicker solution that provides majority of the functionality of this request would be to allow configuring which tags to ignore.

The original request would be ideal but this might prove easier and faster to implement as the original request gets looked at.

**Comment by bobokun** [comment]
Sure let me see what I can come up with

**Comment by bobokun** [comment]
You can add a list of tags to update for each tracker now.
Examples:
```yaml
tracker:
  avistaz:
    tag:
      - Avistaz
      - tag2
      - tag3
  beyond-hd:
    tag: [Beyond-HD, tag2, tag3]
```

Also you can add igonre tags in settings
```yaml
settings:
  force_auto_tmm: true
  tracker_error_tag: issue
  ignoreTags_OnUpdate:
    - noHL
    - issue
    - cross-seed
```
